### ISSUE TITLE
Difference between radiant repositories

### ISSUE THREAD

**Issue by kmezhoud** [radiant-rstats/radiant#1]
Dear Dr Vincent,
Is there a doc that explain the the difference between radiant, radiant.data, and radiant.basics?
Thanks

**Comment by vnijs** [comment]
See the 'source code' section at https://radiant-rstats.github.io/docs/. Each radiant.something package is a menu. Everything builds on radiant.data. The radiant package just pulls the diffent menus together into one app. The simplest example of how to extend radiant.data is radiant.design
