### ISSUE TITLE
new installation fails with radiant.basics installation error

### ISSUE THREAD

**Issue by scuits22** [radiant-rstats/radiant#102]
I attempted to install Radiant on a machine that I had uninstalled the old version, and I also installed Radiant on a windows machine that had never had Radiant on it. In both instances, there was this message.
Failed with error: 'package 'radiant.basics' 0.9.7 was found, but >=0.9.7.3 is required by 'radiant''
Error in radiant.data::launch(package = "radiant", run = "browser", state, :
Calling radiant start function but radiant is not installed

**Comment by scuits22** [comment]
I attempted to install Radiant on a machine that I had uninstalled the old version, and I also installed Radiant on a windows machine that had never had Radiant on it. In both instances, there was this message.
Failed with error: 'package 'radiant.basics' 0.9.7 was found, but >=0.9.7.3 is required by 'radiant''
Error in radiant.data::launch(package = "radiant", run = "browser", state, :
Calling radiant start function but radiant is not installed

**Comment by vnijs** [comment]
Please use the commands below to get the latest versions. 

```
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```

For more information see the Install page linked below:

https://radiant-rstats.github.io/docs/install.html

**Comment by scuits22** [comment]
No improvement yet: attempting another clean uninstall/install. Which file could I manually change the version number in to see if that works?

**Comment by vnijs** [comment]
Are you using R 3.4.0 or newer? If so please run the commands below and post all output shown in Rstudio.

```
remove.packages("radiant.basics")
radiant.update::radiant.update()
sessionInfo()
```

**Comment by scuits22** [comment]
After a fresh install and running the above:

> radiant:::radiant()
Failed with error:  ‘package ‘radiant.basics’ 0.9.7 was found, but >= 0.9.7.3 is required by ‘radiant’’
Error in radiant.data::launch(package = "radiant", run = "browser", state,  : 
  Calling radiant start function but radiant is not installed.
> remove.packages("radiant.basics")
Removing package from ‘C:/Users/USER/OneDrive/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
> radiant.update::radiant.update()
Error in install.packages : Updating loaded packages

Testing if Radiant can be loaded ...

Radiant update was successful

Warning message:
In FUN(X[[i]], ...) :
  DESCRIPTION file of package 'radiant.basics' is missing or broken
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
Error in x[["Version"]] : subscript out of bounds
In addition: Warning message:
In FUN(X[[i]], ...) :
  DESCRIPTION file of package 'radiant.basics' is missing or broken

**Comment by vnijs** [comment]
That was very helpful! Thanks for reporting this issue @scuits22. Please run the command below again and the radiant.basics package should update appropriately. 

`radiant.update::radiant.update()`

**Comment by scuits22** [comment]
It's better! The browser opens; however, there is no connection. RStudio displays the following error:

Starting radiant in the default browser ...

Use radiant::radiant_viewer() in Rstudio to open radiant in the Rstudio viewer
or radiant::radiant_window() in Rstudio to open radiant in an Rstudio window

Listening on http://127.0.0.1:6295
Error in .Call("_later_execCallbacks", PACKAGE = "later", timeoutSecs,  : 
  Incorrect number of arguments (2), expecting 1 for '_later_execCallbacks'
Stopped Radiant

**Comment by scuits22** [comment]
If you just changed something, it worked! After updating again, no errors. Thank you!

**Comment by vnijs** [comment]
Glad to hear radiant is working now. Thanks again for reporting the issue @scuits22
