### ISSUE TITLE
Ubuntu 18.04 Radiant installation exits with "installation of package ‘radiant’ had non-zero exit status"

### ISSUE THREAD

**Issue by nikitawolfik** [radiant-rstats/radiant#103]
Ubuntu 18.04.1 LTS
R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
RStudio Version 1.1.463

When trying to install radiant through 
`install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/")` get an error

> installation of package ‘radiant’ had non-zero exit status

A handful of other packages have the same message. What might be the problem here?

**Comment by vnijs** [comment]
Can you provide more output? Also, did you follow all parts of the "Installing on Linux" section at https://radiant-rstats.github.io/docs/install.html ? 

You might also be interested in using docker here. See https://github.com/radiant-rstats/docker

**Comment by nikitawolfik** [comment]
Yep, I did follow this exact guide. As per more output, let me restart the process and I'll post all the log here.

**Comment by vnijs** [comment]
Thanks for the update. I'll review tonight (PT)

**Comment by nikitawolfik** [comment]
While installing through the guide you linked execution halts at the 
`sudo su -c "R -e \"source('https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R')\""
`

The output after `install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/")` is the following: 
> > install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/")
Installing package into ‘/home/nikita/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
also installing the dependencies ‘rio’, ‘rgexf’, ‘car’, ‘plotly’, ‘data.tree’, ‘DiagrammeR’, ‘radiant.data’, ‘radiant.design’, ‘radiant.basics’, ‘radiant.model’, ‘radiant.multivariate’

trying URL 'https://radiant-rstats.github.io/minicran/src/contrib/rio_0.5.16.tar.gz'
Content type 'application/gzip' length 420489 bytes (410 KB)
==================================================
downloaded 410 KB

trying URL 'https://radiant-rstats.github.io/minicran/src/contrib/rgexf_0.15.3.tar.gz'
Content type 'application/gzip' length 447723 bytes (437 KB)
==================================================
downloaded 437 KB

trying URL 'https://radiant-rstats.github.io/minicran/src/contrib/car_3.0-2.tar.gz'
Content type 'application/gzip' length 447952 bytes (437 KB)
==================================================
downloaded 437 KB

trying URL 'https://radiant-rstats.github.io/minicran/src/contrib/plotly_4.8.0.tar.gz'
Content type 'application/gzip' length 1860673 bytes (1.8 MB)
==================================================
downloaded 1.8 MB

trying URL 'https://radiant-rstats.github.io/minicran/src/contrib/data.tree_0.7.8.tar.gz'
Content type 'application/gzip' length 1896388 bytes (1.8 MB)
==================================================
downloaded 1.8 MB

trying URL 'https://radiant-rstats.github.io/minicran/src/contrib/DiagrammeR_1.0.0.tar.gz'
Content type 'application/gzip' length 1238545 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

trying URL 'https://radiant-rstats.github.io/minicran/src/contrib/radiant.data_0.9.8.10.tar.gz'
Content type 'application/gzip' length 1786428 bytes (1.7 MB)
==================================================
downloaded 1.7 MB

trying URL 'https://radiant-rstats.github.io/minicran/src/contrib/radiant.design_0.9.8.1.tar.gz'
Content type 'application/gzip' length 1068306 bytes (1.0 MB)
==================================================
downloaded 1.0 MB

trying URL 'https://radiant-rstats.github.io/minicran/src/contrib/radiant.basics_0.9.8.1.tar.gz'
Content type 'application/gzip' length 3001335 bytes (2.9 MB)
==================================================
downloaded 2.9 MB

trying URL 'https://radiant-rstats.github.io/minicran/src/contrib/radiant.model_0.9.8.9.tar.gz'
Content type 'application/gzip' length 6797341 bytes (6.5 MB)
==================================================
downloaded 6.5 MB

trying URL 'https://radiant-rstats.github.io/minicran/src/contrib/radiant.multivariate_0.9.8.2.tar.gz'
Content type 'application/gzip' length 4073298 bytes (3.9 MB)
==================================================
downloaded 3.9 MB

trying URL 'https://radiant-rstats.github.io/minicran/src/contrib/radiant_0.9.8.0.tar.gz'
Content type 'application/gzip' length 223815 bytes (218 KB)
==================================================
downloaded 218 KB

* installing *source* package ‘rio’ ...
** package ‘rio’ successfully unpacked and MD5 sums checked
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (rio)
* installing *source* package ‘rgexf’ ...
** package ‘rgexf’ successfully unpacked and MD5 sums checked
** libs
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-i39faS/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c edges.analysis.c -o edges.analysis.o
gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o rgexf.so edges.analysis.o -L/usr/lib/R/lib -lR
installing to /home/nikita/R/x86_64-pc-linux-gnu-library/3.5/rgexf/libs
** R
** data
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (rgexf)
* installing *source* package ‘plotly’ ...
** package ‘plotly’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded
* DONE (plotly)
* installing *source* package ‘car’ ...
** package ‘car’ successfully unpacked and MD5 sums checked
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (car)
* installing *source* package ‘DiagrammeR’ ...
** package ‘DiagrammeR’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (DiagrammeR)
* installing *source* package ‘data.tree’ ...
** package ‘data.tree’ successfully unpacked and MD5 sums checked
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (data.tree)
* installing *source* package ‘radiant.data’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (radiant.data)
* installing *source* package ‘radiant.design’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (radiant.design)
* installing *source* package ‘radiant.basics’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (radiant.basics)
* installing *source* package ‘radiant.model’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (radiant.model)
* installing *source* package ‘radiant.multivariate’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Warning: S3 methods ‘eigs.matrix’, ‘eigs.dgeMatrix’, ‘eigs.dgCMatrix’, ‘eigs.dgRMatrix’, ‘eigs.dsyMatrix’, ‘eigs.function’, ‘eigs_sym.matrix’, ‘eigs_sym.dgeMatrix’, ‘eigs_sym.dgCMatrix’, ‘eigs_sym.dgRMatrix’, ‘eigs_sym.function’, ‘svds.matrix’, ‘svds.dgeMatrix’, ‘svds.dgCMatrix’, ‘svds.dgRMatrix’, ‘svds.dsyMatrix’, ‘svds.function’ were declared in NAMESPACE but not found
Error in library.dynam(lib, package, package.lib) : 
  shared object ‘RSpectra.so’ not found
ERROR: lazy loading failed for package ‘radiant.multivariate’
* removing ‘/home/nikita/R/x86_64-pc-linux-gnu-library/3.5/radiant.multivariate’
Warning in install.packages :
  installation of package ‘radiant.multivariate’ had non-zero exit status
ERROR: dependency ‘radiant.multivariate’ is not available for package ‘radiant’
* removing ‘/home/nikita/R/x86_64-pc-linux-gnu-library/3.5/radiant’
Warning in install.packages :
  installation of package ‘radiant’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpdbKudr/downloaded_packages’

**Comment by vnijs** [comment]
Can you try installing RSpectra separately from CRAN? Then use radiant.update

**Comment by nikitawolfik** [comment]
Fails with the same result:

> install.packages('RSpectra', repos='http://cran.rstudio.com/')
Installing package into ‘/home/nikita/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/src/contrib/RSpectra_0.13-1.tar.gz'
Content type 'application/x-gzip' length 111032 bytes (108 KB)
==================================================
downloaded 108 KB

ERROR: failed to lock directory ‘/home/nikita/R/x86_64-pc-linux-gnu-library/3.5’ for modifying
Try removing ‘/home/nikita/R/x86_64-pc-linux-gnu-library/3.5/00LOCK-RSpectra’
Warning in install.packages :
  installation of package ‘RSpectra’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp7y6m5d/downloaded_packages’

**Comment by vnijs** [comment]
I just installed RSpectra on an ubuntu 18.04 box without issue. Try the below from a terminal:

rm -rf home/nikita/R/x86_64-pc-linux-gnu-library/3.5/00LOCK-RSpectra

and from R

remove.packages("RSpectra")
radiant.update::radiant.update()

If that doesn't work try posting an issue to the authors of the RSpectra package

**Comment by nikitawolfik** [comment]
Wow, the latest worked. Thanks a lot!

**Comment by vnijs** [comment]
Glad to hear that @NikitaNeganov. Have fun with Radiant :)
