### ISSUE TITLE
ggplot vs visualize

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#104]
What's the difference between visualize and ggplot?

For example, the following visualize() is the same as the ggplot() with format added.

```{r fig.width = 13.46, fig.height = 4.31, dpi = 144}
visualize(
  diamonds, 
  xvar = "price", 
  yvar = "carat", 
  type = "line", 
  color = "clarity", 
  fun = "sum", 
  custom = FALSE
)
```

```{r}
ggplot(diamonds, aes(x=price, y=carat, fill=clarity)) + 
    geom_line()
```

**Comment by josh1400** [comment]
That being said,  I can't simply do the following. Change line to area.  The following ggplot() works but the visualize() does not.

```{r fig.width = 13.46, fig.height = 4.31, dpi = 144}
visualize(
  diamonds, 
  xvar = "price", 
  yvar = "carat", 
  type = "area", 
  color = "clarity", 
  fun = "sum", 
  custom = FALSE
)
```

```{r}
ggplot(diamonds, aes(x=price, y=carat, fill=clarity)) + 
    geom_area()
```

**Comment by josh1400** [comment]
I want to use ggplot() since it has all the online help, but I'm not sure how to change or match the format of my current graphs which are created with visualize().

**Comment by vnijs** [comment]
`visualize` uses ggplot to create plots. It doesn't try to cover all aspects of ggplot because ggplot is HUGE. See the "Customizing plots in Report > Rmd" section @ https://radiant-rstats.github.io/docs/data/visualize.html on how you can customize plots generated using `visualize` with ggplot commands/code

**Comment by josh1400** [comment]
Makes sense. thanks

**Comment by vnijs** [comment]
OK. I'll close but re-open if needed
