### ISSUE TITLE
Save report as PowerPoint

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#106]
I see that Rmd now supports PowerPoint.

Will you be adding this as an option for saving reports?

**Comment by vnijs** [comment]
Nice idea. Working on it.

**Comment by vnijs** [comment]
Please upgrade and tryout the update to Report > Rmd with the new option to save a report as a power point file. If there are any issue please let me know

See the link below for more information on Rmarkdown for power point:
https://bookdown.org/yihui/rmarkdown/powerpoint-presentation.html

See the "Options" section in the page below about templates you could use for Word and Powerpoint files:
https://radiant-rstats.github.io/docs/data/report_rmd.html

**Comment by vnijs** [comment]
Power point is now available as an output option in _Report > Rmd_
