### ISSUE TITLE
Polygon edge not found

### ISSUE THREAD

**Issue by Liwa97** [radiant-rstats/radiant#107]
Hello,

The following message appears when I am trying to do a sensitivity analysis "Error: polygon edge not found", even though the plot visualization perfectly works.

What can I do?

Thank you

**Comment by vnijs** [comment]
If you can provide a reproducible example I will take a look

**Comment by vnijs** [comment]
@Liwa97 Can you share an example where this occurs? I haven't been able to reproduce yet.

**Comment by Liwa97** [comment]
Good morning,

Just to let you know the problem is solved. 
The following error message appeared in the RStudio console that I did not check at first:

**_Error in grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  Polygon edge not found
In addition: Warning messages:
1: In grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  no font could be found for family "Arial"
2: In grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  no font could be found for family "Arial"_**

I simply had to download the font Arial and make it available for all programs on my computer, it finally worked.

Thank you again

**Comment by vnijs** [comment]
Thanks for the update @Liwa97. Seems like a general problem related to ggplot2. Thanks for reporting and glad to hear things are working now!
