### ISSUE TITLE
Visualize Style Issue

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#108]
Changing the fill color in the style section of visualize doesn't change the actual fill color.

![image](https://user-images.githubusercontent.com/36533710/57396095-78527a80-717e-11e9-8c41-8c506405071f.png)

**Comment by vnijs** [comment]
It does (see below) but has no influence if you also use "Fill" in the "main" dropdown. Can you show a larger screenshot so I can see all settings you are using?

![image](https://user-images.githubusercontent.com/2998956/57409942-5ec12b00-719e-11e9-946b-88d7aafd5c53.png)

**Comment by josh1400** [comment]
You're right.  The issue is related to using fill in the main dropdown.

**Comment by vnijs** [comment]
OK. I'll close this for now.
