### ISSUE TITLE
Plot "Jotter" option distorting data

### ISSUE THREAD

**Issue by carbog** [radiant-rstats/radiant#109]
When plotting a numeric variable vs a factor - the jitter button distorts the data.  It seems like it jitters in the y direction as well

with jitter
![image](https://user-images.githubusercontent.com/50428414/57414506-3c82d980-71ad-11e9-9838-d86e6aefd821.png)

without jitter
![image](https://user-images.githubusercontent.com/50428414/57414522-4efd1300-71ad-11e9-95bc-cbdcadd292b6.png)

**Comment by vnijs** [comment]
Correct. The current settings are `position_jitter(width = 0.4, height = 0.05)`. I'll set `height` to 0 in the next release. Thanks for the suggestion.
