### ISSUE TITLE
Data | Explore returns error 'incompatible types, expecting a integer vector' with >1 integer group by variable

### ISSUE THREAD

**Issue by JMF-123** [radiant-rstats/radiant#11]
Hi, Thanks for radiant, it is a fantastic tool! Error details are below:

Example using houseprices example dataset, explore tab will allow several factor group by variables (e.g. brick & neighbourhood), and a single integer variable works  (e.g. bedrooms), but as soon as I add bedrooms and bathrooms as group by variables, I get 'Error: incompatible types, expecting a integer vector'. The same thing happens if I add either bedrooms or bathrooms to the two factor group by variables that were working together (e.g. brick & neighbourhood). Environment is CRAN R 3.3.2, on Linux Mint 18 using R Studio Server 0.99.903
Full error from RStudio console is below:

Warning: Error in mutate_impl: incompatible types, expecting a integer vector
Stack trace (innermost first):
    113: <Anonymous>
    112: stop
    111: mutate_impl
    110: mutate_.tbl_df
    109: mutate_
    108: mutate_each_
    107: dplyr::mutate_each
    106: mutate_each
    105: <Anonymous>
    104: do.call
    103: withCallingHandlers
    102: suppressMessages
    101: withCallingHandlers
    100: suppressWarnings
     99: sshhr
     98: eval [/home/jonathan/R/x86_64-pc-linux-gnu-library/3.3/radiant.data/app/tools/data/explore_ui.R#118]
     97: eval
     96: withProgress
     95: <reactive:.explore> [/home/jonathan/R/x86_64-pc-linux-gnu-library/3.3/radiant.data/app/tools/data/explore_ui.R#117]
     84: .explore
     83: exprFunc [/home/jonathan/R/x86_64-pc-linux-gnu-library/3.3/radiant.data/app/tools/data/explore_ui.R#139]
     82: widgetFunc
     81: func
     80: origRenderFunc
     79: renderFunc
     78: origRenderFunc
     77: output$explore
      2: shiny::runApp
      1: radiant

**Comment by vnijs** [comment]
Hi @JMF-123. I can't replicate the problem you described. Could you post a screen shot so I can see all the settings? Also, the statefile would be useful (i.e., click the floppy icon in the navbar and then 'save state'). 

If you are using Radiant in Rstudio, could you click on Update Radiant from the Addins dropdown and see if that resolves the problem?

**Comment by JMF-123** [comment]
Hello again, thanks for your reply.  I did as you suggested and updated Radiant from the RStudio Addins menu; now that I have done that I am no longer able to replicate the issue. My env was a fresh install from CRAN yesterday, but guess there was a more up to date version available.  Thanks again for the support and the Radiant package.

**Comment by vnijs** [comment]
Thanks for letting me know @JMF-123. `Update Radiant` gets the latest version of Radiant and it's sub-packages from the repo linked below. These packages are not on CRAN yet but will be soon.

https://github.com/radiant-rstats/minicran
