### ISSUE TITLE
Loading data into radiant from computer

### ISSUE THREAD

**Issue by nemery1** [radiant-rstats/radiant#111]
Hi,
When I click the load button to load a csv from my computer, I see someone else's computer, not my own laptop. Unsure of how to upload a csv file from my own computer. This will be a big issue when we have 400 students using radiant this fall semester... :)
Cheers,
Nate

**Comment by vnijs** [comment]
It seems I missed your post @nemery1. Please provide more information about your setup. If you are running radiant from Rstudio on a server it will default to look for data on the users account on the server. Is that not what you wanted? It is possible to change these setting but I need more information about what your setup is.

**Comment by djb9999** [comment]
Hi Vincent @vnijs ,

I have a similar requirement like this. I'm planning to run Radiant from RStudio on a server and I want to change it from default setting to access and upload local files from end user. Please let me know how to change this setting.

Regards,
John

**Comment by vnijs** [comment]
That is an unusual combination. Why not run radiant shiny server then?

**Comment by djb9999** [comment]
@vnijs The requirement is to run Radiant within a private on-prem network. So, we have planned to host it in a local server by running Radiant from RStudio and provide access to end users to upload data. Is it possible to change the setting?

**Comment by djb9999** [comment]
@vnijs I was going through the code flow and somehow solved the issue by changing the settings as below.

options(radiant.sf_volumes = "")
options(radiant.shinyFiles = FALSE)
Sys.setenv("SHINY_PORT") == port_number)

**Comment by djb9999** [comment]
@vnijs was going through the code flow and somehow solved the issue by changing the settings as below.

options(radiant.sf_volumes = "")
options(radiant.shinyFiles = FALSE)
Sys.setenv("SHINY_PORT" = port_number)

**Comment by djb9999** [comment]
@vnijs I was going through the code flow and somehow solved the issue by changing the settings as below.

options(radiant.sf_volumes = "")
options(radiant.shinyFiles = FALSE)
Sys.setenv(SHINY_PORT = port_number)
Sys.setenv(RSTUDIO = "")

**Comment by vnijs** [comment]
Nice! It *should* have worked with only but doesn't. This is a pretty unusual request and I don't recommend it. It would be better to put/move specific data to the server so you can use Rstudio projects (link below). That is the best way to develop reproducible analytics (see also 2nd link below).

`options(radiant.shinyFiles = FALSE)`

https://support.rstudio.com/hc/en-us/articles/200526207-Using-RStudio-Projects

https://www.youtube.com/watch?v=pNNQc2lHR8Q

**Comment by djb9999** [comment]
Thanks @vnijs!

**Comment by vnijs** [comment]
@djb9999 Closing for now. If new issues come up, let me know
