### ISSUE TITLE
Problem with Transform -> Change Type

### ISSUE THREAD

**Issue by koushr89** [radiant-rstats/radiant#112]
Hello,

In the recent version of Radiant I am facing some issues with "changing type" of variables. Almost all "change type" transformations are not doing anything to the variables. For example, I am trying to transform the "host_id" variable into integer format or character (1st image). Both transformations result in the exact same variable as the original variable (2nd image).
Now interestingly, after doing the transformation, if I click on the "report results" button and then click on "knit report (Rmd)" both of those transformations will apply (3rd image).
![image](https://user-images.githubusercontent.com/54371813/63453900-a69b5380-c417-11e9-9079-aa68a35bcbe3.png)
![image](https://user-images.githubusercontent.com/54371813/63454071-13aee900-c418-11e9-86c2-3404f9820ccb.png)
![image](https://user-images.githubusercontent.com/54371813/63454383-bb2c1b80-c418-11e9-8531-d71b8801efd6.png)

**Comment by vnijs** [comment]
Thanks for reporting @koushr89. Small bug but annoying consequences. I'll push a new release to CRAN asap. In the mean time you can use Addins > Update Radiant from Rstudio to get the fixed version.
