### ISSUE TITLE
Feature Request: tidyverse code generation

### ISSUE THREAD

**Issue by AtharKharal** [radiant-rstats/radiant#113]
tidyverse is current, base R seems outdated now. Is it possible that Radiant generates a tidyverse code along with base R?

**Comment by vnijs** [comment]
Sorry @AtharKharal but I don't know what you are referring to. Radiant currently only supports R 3.5 and newer.

**Comment by AtharKharal** [comment]
oh yes, I asked a silly question. I am clear now after reading through 'programming' section in its docs. Thanks indeed.
