### ISSUE TITLE
Training Variable: same seed, different outputs

### ISSUE THREAD

**Issue by koushr89** [radiant-rstats/radiant#114]
Hi,

I was trying to teach validation analysis to my students, and although all students set the seed to a specific value (111), students got two different results on different computers. I am illustrating this using the Diamonds dataset. I go to Transform tab and use the "Training Variable" option for Transformation Type. I choose size to be 0.6 and seed=111. Here is what my training variable would look like for the first few observations of the data:
![image](https://user-images.githubusercontent.com/54371813/66066083-d52c4400-e516-11e9-892b-b41fff1eb348.png)

While some of my students got the same training variable, others got a totally different training variable even though they specified the same size and seed value. Here is what it looks like for them:
![image](https://user-images.githubusercontent.com/54371813/66066178-0a389680-e517-11e9-822f-b58177cf6852.png)

I don't think this issue existed last year because none of my 170+ students brought up this issue.

Thanks for checking this.

**Comment by vnijs** [comment]
Thanks for the update @koushr89. This is due to a change in how random numbers are generated in R3.6.0 and above (see link below). If you ensure that you an all students are using the same version of R there shouldn't be any problems. If you have students use the install instructions linked below they should always get the latest version of R.

https://radiant-rstats.github.io/docs/install.html

https://blog.revolutionanalytics.com/2019/05/whats-new-in-r-360.html

I assume this information resolved the issue but feel free to re-open if needed.

**Comment by vnijs** [comment]
FYI I'm pushing an updated version of the `radiant.data` packages that will use the `complete_ra` and `block_ra` functions from the `randomizr` package to create a training variable (_Data > Transform > Training variable_). One of the really nice benefits of the `block_ra` function is that if you select, e.g., `survived` from the `titanic` dataset the function will try to ensure that the (exact) same proportion of survivors are in both the training and the test sample. See the `randomizr` vignette linked below for more information. There are also some changes in _Design > Random sampling_ and a new tool _Design > Random assignment_ that is also based on the `randomizr` packages.

The down-side of these change is that you may get a (slightly) different training and test set compared to what you obtained previously.

You can use `Update radiant` from the Addins dropdown in Rstudio or `radiant.update::radiant.update()` in the Rstudio console.

https://cran.r-project.org/web/packages/randomizr/vignettes/randomizr_vignette.html

**Comment by koushr89** [comment]
Thanks for the update Vincent.

**Comment by joniarroba** [comment]
Great news! I will try!
