### ISSUE TITLE
Apple Computer will not let me +store 

### ISSUE THREAD

**Issue by mlrosenbaum** [radiant-rstats/radiant#115]
I have updated my Radiant (to the most recent version) and refreshed. Under Data > Transform the + store button will not store my transformed data into the data set. Please see screenshots below. After I attempt to +store the data it does not show under my data>view tab as a new category. 

Additionally, when I do Model> evaluate regression, it will only show if I change "show test results" to test.

Has someone else had this issue? 

<img width="1126" alt="Screen Shot 2019-10-02 at 3 33 43 PM" src="https://user-images.githubusercontent.com/56091862/66075667-20038700-e52a-11e9-83ad-b7599a22d3f8.png">

**Comment by vnijs** [comment]
This is not valid input for _Data > Transform_. I think what you are looking for is `Create` from the `Transformation type` drop down. There you can enter a formula like the one you are trying to use in your screenshot as a variable name extension.

**Comment by mlrosenbaum** [comment]
Thank you- even with this change, the "store predictions" do not show my new variable

**Comment by vnijs** [comment]
Did you select a dataset to generate predictions for? Please show a screenshot

**Comment by mlrosenbaum** [comment]
Thank you- After speaking with my professor, we think the issue is resolved!

**Comment by vnijs** [comment]
OK. Closing this issue @mlrosenbaum
