### ISSUE TITLE
Radiant is not working anymore on my browser

### ISSUE THREAD

**Issue by sergioventurini** [radiant-rstats/radiant#116]
Hi, I just reinstalled radiant (version 0.9.9.1) in R (version 3.6.1) but when I start it using radiant::radiant() the browser pops up with the usual menu bar but without showing any data or command (see the attached picture). I also tried other browsers but I get the same problem. Hope you can solve this issue soon because I need the package for my projects. Thanks.

<img width="1015" alt="screenshot_675" src="https://user-images.githubusercontent.com/2522817/66293244-83a10200-e8e6-11e9-80d3-25473659420c.png">

**Comment by vnijs** [comment]
This is due to changes in the htmlwidgets package (see issue https://github.com/ramnathv/htmlwidgets/issues/348). Running the code below should get you back to a working setup. When shiny 1.4.0 is release everything should work without the need for this workaround.

```
remove.packages("htmlwidgets")
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```

**Comment by sergioventurini** [comment]
Thanks!

**Comment by vnijs** [comment]
Closing issue with reminder that updating will often resolve problems :)

```
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```
