### ISSUE TITLE
Error in system("wmic logicaldisk get Caption", intern = T) :    'wmic' not found

### ISSUE THREAD

**Issue by Woprates** [radiant-rstats/radiant#117]
How can I deal with this issue? I did the installation according your video, and show up this message.

**Comment by vnijs** [comment]
In 99.9% of Windows machines, the "wmic" function is in the system path. Not on your system unfortunately. You can add it to your path by following the instructions linked below.

https://superuser.com/a/1178758/922334

**Comment by vnijs** [comment]
This should be resolved now. Use the command below to get the latest version. Thanks for reporting @Woprates

`radiant.update::radiant.update()`

**Comment by Woprates** [comment]
Thanks for the update
