### ISSUE TITLE
Can't do anything, no response

### ISSUE THREAD

**Issue by webber792** [radiant-rstats/radiant#118]
The error message is as below

Registered S3 method overwritten by 'radiant.data':
  method       from  
  print.gtable gtable

![Screen Shot 2019-10-29 at 3 21 17 PM](https://user-images.githubusercontent.com/47879162/67905943-51bf3c00-fb30-11e9-9f8d-1f02a5983bd3.png)

**Comment by webber792** [comment]
Need to re-install in R instead of RStudio

**Comment by vnijs** [comment]
It seems this is likely due a corrupted package somewhere on your system. Please run the code below and send back the output. I expect that using `remove.packages("package-name")` to remove any corrupted packages, followed by `radiant.update::radiant.update()` should get you back to a working setup

```
allPackages <- installed.packages()[, 1]
findBrokenPackages <- function(packages) {
    for (p in packages) {
        tryCatch(ncol(asNamespace(p)$.__NAMESPACE__.$S3methods),
                 error = function(e) print(c(p, e)))
    }
}
findBrokenPackages(allPackages)
```

**Comment by webber792** [comment]
Hi Professor Vincent

I fixed it by re-install the radiant in R instead of RStudio.
Thank you !

Rick

**Comment by vnijs** [comment]
Good to hear @webber792. I'd still recommend you run the command below to ensure you have the latest version of all relevant packages installed.

```
radiant.update::radiant.update()
```
