### ISSUE TITLE
Data -- Pivot not showing graph

### ISSUE THREAD

**Issue by jav98** [radiant-rstats/radiant#120]
Hi, I'm using the Pivot section and when I click the box to show the Plot, nothing appears. I'm attaching a screenshot below. I've already checked that everything is updated, I've restarted RStudio and the browser, and I've even tried to run it in the RStudio Window and Viewer, but it still is not working. The graphs in other tools seem to be working fine.

<img width="1677" alt="Screenshot 2019-12-07 at 15 24 11" src="https://user-images.githubusercontent.com/47459030/70376131-0144b680-1906-11ea-8304-a9ecfa8435cd.png">

**Comment by vnijs** [comment]
Thanks for reporting @jav98. I can't replicate the issue so I think this has already been fixed. You can get the development versions of the radiant packages using the code below. However, if you are using radiant for a class, note that there is a breaking change in the (repeated) simulation module.

```
oop <- options()
options(repos = c(RSM = "https://rsm-compute-01.ucsd.edu:4242/rsm-msba/__linux__/bionic/latest", CRAN = "https://cloud.r-project.org"))
install.packages(c("radiant.data", "radiant.design", "radiant.basics", "radiant.model", "radiant.multivariate"))
options(oop)
```

**Comment by jav98** [comment]
I managed to get it to work by reinstalling RStudio and Radiant. Thanks!
