### ISSUE TITLE
Radiant Data View Screen Grey

### ISSUE THREAD

**Issue by ghost** [radiant-rstats/radiant#126]
On opening the Radiant Data>View tab the screen turns grey and I'm unable to return and run analyses on any other tab.

**Comment by vnijs** [comment]
I cannot replicate the issue and don't have enough information to help yet. Can you (1) run the commands below to make sure you are using the latest version of radiant and (2) make sure no data or code is loaded before you (re)start radiant. If radiant is "grayed out" you should still be able to click on the power icon and then on the "Refresh" button which will reset radiant to a "fresh" state.

If this does not address your issue, please post screen shots of radiant and show any messages print in the Rstudio console. Thanks

```
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```

**Comment by ghost** [comment]
Many thanks for your prompt reply. 

I ran (1) and made sure (2) applied. The View screen remained grey (English spelling of the word ;-)).The refresh button 'flashed' the View screen, but did not engage.

I'm not sure how to attach screen shots, but this is a copy and paste of the Rstudio console:

' R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from D:/GEORGE_NEW_VOLUME_FILES/RPROJECTS/.RData]

> radiant::radiant()

Starting radiant in the default browser ...

Use radiant::radiant_viewer() in Rstudio to open radiant in the Rstudio viewer
or radiant::radiant_window() in Rstudio to open radiant in an Rstudio window

Listening on http://127.0.0.1:4916'

When run in Window or Viewer everything vanishes when View is selected.

The 'red button' on the console is showing.

**Comment by vnijs** [comment]
Is there no additional message in Rstudio after you go into the View tab in Radiant? I do see that you have a previous workspace being loaded (see below). Perhaps that is where the problems is? Please make sure there is *nothing* loaded in memory before you start Radiant this time. FYI You can just drag-and-drop images into github issues or even copy-and-paste. I need more information to help

[Workspace loaded from D:/GEORGE_NEW_VOLUME_FILES/RPROJECTS/.RData]

**Comment by ghost** [comment]
There is no additional message after I go to the View tab.  I have checked the Environment tab and the message is 'Environment is Empty', so I guess nothing is being loaded into memory. Thanks for the FYI.

I'll try running the file on https://vnijs.shinyapps.io/radiant and see what happens.

**Comment by vnijs** [comment]
Wait. This happens when loading a specific file? That wasn't clear to me. In that case, can you share the file (e.g., through email)?

**Comment by ghost** [comment]
Yes, it happens when I load a specific file. 
It all worked fine on https://vnijs.shinyapps.io/radiant. I'll send you the file. Thanks.

**Comment by vnijs** [comment]
The issue seems to be that you have some non-UTF characters in your data (e.g., below) and, for some reason DT cannot handle some those. Please try out the code below. I'm not sure the best way to handle issues like this more generally without time-consuming conversions. If you have ideas/suggestions I'd be happy to hear them.

Jersey_Property_Unit _Trust(�JPUT�)

```
library(radiant.data)
DATA_2019_4_R <- readr::read_csv("/Users/vnijs/Desktop/radiant/DATA_2019_4_R.csv") %>%
  fix_names() %>%
  to_fct()

## won't work
# view_data(DATA_2019_4_R)

levels(DATA_2019_4_R$c2)
DATA_2019_4_R <- mutate(DATA_2019_4_R, c2 = fix_smart(c2))

## should work
view_data(DATA_2019_4_R)
```

**Comment by ghost** [comment]
Many thanks fgor identiying the problem. Perhaps I shoud I'll check the data fileds. I have no suggustions at this stage but if anything springs to mind I'll get back.

**Comment by Farmer02** [comment]
Many thanks fgor identiying the problem. Perhaps I shoud I'll check the data fileds. I have no suggustions at this stage but if anything springs to mind I'll get back.

**Comment by vnijs** [comment]
@ghost did you want to keep this issue open? I'm not sure I can think of a general strategy that will address these types of data issues to be honest.

**Comment by vnijs** [comment]
Closing for now ...
