### ISSUE TITLE
Error: [€-y] is a wrong regular expression. The reason is 'Invalid character range.'

### ISSUE THREAD

**Issue by Hokangss** [radiant-rstats/radiant#127]
I tried to use the decision analysis function on Radiant, but when I pressed 'calculate,' the message "Error: [€-y] is a wrong regular expression. The reason is 'Invalid character range.'" -the statement is roughly translated in English because it was in Korean- came up.
What is the reason this error pops up and how do I fix it?

**Comment by vnijs** [comment]
Can you provide a screenshot of the error and the .yaml file? Also, please run the commands below to ensure you are using the latest version of all relevant radiant packages.

```
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```

**Comment by Hokangss** [comment]
Thank you for your response.
I ran the commands and checked that I have the latest version of R, Rstudio, Radiant etc, but I still have the problem.
I am adding my .yaml file and a screenshot of the error that pops up.
It means, "Error: [€-y] is a wrong regular expression. The reason is 'Invalid character range.'" as I mentioned in my issue.

![error radiant](https://user-images.githubusercontent.com/62892036/78004292-ded31f00-7374-11ea-829d-c266d5a490a7.png)

[kcl-input.zip](https://github.com/radiant-rstats/radiant/files/4407646/kcl-input.zip)

This is what appeared on Rstudio when I calculated the decision tree.

Listening on http://127.0.0.1:7927
경고: Error in gsub: '[€-y]'은 잘못된 정규표현식입니다, 그 이유는 'Invalid character range'입니다
  164: gsub
  163: function_list[[i]]
  162: freduce
  161: _fseq
  160: eval
  159: eval
  157: %>%
  156: dtree_parser
  155: dtree
  151: eventReactiveHandler [c:/R/R-3.6.2/library/radiant.model/app/tools/analysis/dtree_ui.R#328]
  107: dtree_run
  103: renderPrint [c:/R/R-3.6.2/library/radiant.model/app/tools/analysis/dtree_ui.R#335]
  102: func
   86: origRenderFunc
   85: output$dtree_print
    5: shiny::runApp
    2: radiant.data::launch
    1: radiant:::radiant

**Comment by vnijs** [comment]
Thank you for the additional information. The files you sent run as intended on my computer without any errors. I expect this has something to do for (korean) encoding on Windows of data that is not in UTF format. Unfortunately, this will be difficult to fix if I cannot replicate the error. 

In the mean-time, at least for decision analysis, can you try radiant running at the link below? 

https://vnijs.shinyapps.io/radiant

**Comment by Hokangss** [comment]
I tried it with the link you sent me, and it finally worked!!!
It's too bad that this error can't be fixed easily, but thank you so much for the help.

**Comment by vnijs** [comment]
@Hokangss according to https://github.com/radiant-rstats/radiant/issues/128 the issue can be fixed without changes to Radiant code. Not sure yet how that was achieved however. If you do know, please post additional information. Thanks

**Comment by Hokangss** [comment]
I think the writer of #128 and I are in the same class haha It can be fixed by changing the laptop's language to English. Thanks for your help!
