### ISSUE TITLE
Error in gsub. Error: [€-y] is a wrong regular expression. The reason is 'Invalid character range.'

### ISSUE THREAD

**Issue by ycg02037** [radiant-rstats/radiant#128]
Hi, I am trying to learn Radiant under the instructions of my professor in Korea. 

I am going to learn Model-Decision Analysis-Decision Tree, and the professor has provided me with .yaml file for my learning.

However, whenever I load the .yaml file and try to calculate, the error message of "Error in gsub. Error: [€-y] is a wrong regular expression. The reason is 'Invalid character range.'" appears.

I downloaded the .yaml file via my professor's shared Dropbox folder, and my Windows account is created in English alphabet. 

It would be a huge help if anyone who knows how to resolve this issue.

**Comment by vnijs** [comment]
Can you provide a screenshot of the error and the .yaml file? Also, please run the commands below to ensure you are using the latest version of all relevant radiant packages.

```
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```

**Comment by ycg02037** [comment]
Hi, thank you for your comment.

I went through your recommended commands for latest updates of Radiant.

![스크린샷(153)](https://user-images.githubusercontent.com/62901978/78003123-26f14200-7373-11ea-94f4-e0d310359acd.png)

[[2014120123] KCL case input file error.state.zip](https://github.com/radiant-rstats/radiant/files/4407578/2014120123.KCL.case.input.file.error.state.zip)

[kcl-input.zip](https://github.com/radiant-rstats/radiant/files/4407596/kcl-input.zip)

I have attached the screenshot of Radiant with error code. It is in Korean, meaning "Error in gsub. Error: [€-y] is invalid regular expression. The reason is 'Invalid character range.'"

Listening on http://127.0.0.1:7469
경고: Error in gsub: '[€-y]'은 잘못된 정규표현식입니다, 그 이유는 'Invalid character range'입니다
  164: gsub
  163: function_list[[i]]
  162: freduce
  161: _fseq
  160: eval
  159: eval
  157: %>%
  156: dtree_parser
  155: dtree
  151: eventReactiveHandler [c:/R/R-3.6.2/library/radiant.model/app/tools/analysis/dtree_ui.R#328]
  107: dtree_run
  103: renderPrint [c:/R/R-3.6.2/library/radiant.model/app/tools/analysis/dtree_ui.R#335]
  102: func
   86: origRenderFunc
   85: output$dtree_print
    5: shiny::runApp
    2: radiant.data::launch
    1: radiant:::radiant

I include the source on R Studio for further information that might help you figure out for my problem.

Also, I attached the .zip file of .yaml file and .rda file of my assignments. .yaml file is provided by my professor, and .rda file was saved after the error code appeared on Radiant.

Once again, thank you for your support.

**Comment by ycg02037** [comment]
> Can you provide a screenshot of the error and the .yaml file? Also, please run the commands below to ensure you are using the latest version of all relevant radiant packages.
> 
> ```
> install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
> radiant.update::radiant.update()
> ```

Hi, thank you for your comment.

I went through your recommended commands for latest updates of Radiant.

[[2014120123] KCL case input file error.state.zip](https://github.com/radiant-rstats/radiant/files/4407634/2014120123.KCL.case.input.file.error.state.zip)

[kcl-input.zip](https://github.com/radiant-rstats/radiant/files/4407635/kcl-input.zip)

![스크린샷(153)](https://user-images.githubusercontent.com/62901978/78004041-8a2fa400-7374-11ea-87dd-d1850ddf21ee.png)

I have attached the screenshot of Radiant with error code. It is in Korean, meaning "Error in gsub. Error: [€-y] is invalid regular expression. The reason is 'Invalid character range.'"

Listening on http://127.0.0.1:7469
경고: Error in gsub: '[€-y]'은 잘못된 정규표현식입니다, 그 이유는 'Invalid character range'입니다
164: gsub
163: function_list[[i]]
162: freduce
161: _fseq
160: eval
159: eval
157: %>%
156: dtree_parser
155: dtree
151: eventReactiveHandler [c:/R/R-3.6.2/library/radiant.model/app/tools/analysis/dtree_ui.R#328]
107: dtree_run
103: renderPrint [c:/R/R-3.6.2/library/radiant.model/app/tools/analysis/dtree_ui.R#335]
102: func
86: origRenderFunc
85: output$dtree_print
5: shiny::runApp
2: radiant.data::launch
1: radiant:::radiant

I include the source on R Studio for further information that might help you figure out for my problem.

Also, I attached the .zip file of .yaml file and .rda file of my assignments. .yaml file is provided by my professor, and .rda file was saved after the error code appeared on Radiant.

Once again, thank you for your support.

**Comment by ycg02037** [comment]
> Can you provide a screenshot of the error and the .yaml file? Also, please run the commands below to ensure you are using the latest version of all relevant radiant packages.
> 
> ```
> install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
> radiant.update::radiant.update()
> ```

I was trying to look at the structure of the decision tree my professor made, but I couldn't due to that error. .rda file is saved after I loaded provided .yaml file and pressed calculate.

**Comment by vnijs** [comment]
Thank you for the additional information. The files you sent run as intended on my computer without any errors. I expect this has something to do for (korean) encoding on Windows of data that is not in UTF format. Unfortunately, this will be difficult to fix if I cannot replicate the error. 

In the mean-time, at least for decision analysis, can you try radiant running at the link below? 

https://vnijs.shinyapps.io/radiant

**Comment by ycg02037** [comment]
> Thank you for the additional information. The files you sent run as intended on my computer without any errors. I expect this has something to do for (korean) encoding on Windows of data that is not in UTF format. Unfortunately, this will be difficult to fix if I cannot replicate the error.
> 
> In the mean-time, at least for decision analysis, can you try radiant running at the link below?
> 
> https://vnijs.shinyapps.io/radiant

Thank you for your support. I tried the link you sent me and it worked as intended! I could see the decision tree and the plot.

Can you tell me what I should do to resolve this issue?

![스크린샷(154)](https://user-images.githubusercontent.com/62901978/78011870-23fc4e80-737f-11ea-8a7a-d9f2de9da11d.png)

**Comment by ycg02037** [comment]
> Thank you for the additional information. The files you sent run as intended on my computer without any errors. I expect this has something to do for (korean) encoding on Windows of data that is not in UTF format. Unfortunately, this will be difficult to fix if I cannot replicate the error.
> 
> In the mean-time, at least for decision analysis, can you try radiant running at the link below?
> 
> https://vnijs.shinyapps.io/radiant

Hi, vnijs

I found your link working, but I believe fixing the R Studio and Radiant itself would be better for my future works. I am sorry to say, but it is unrealistic for me to use the provided link every time I use R Studio and Radiant.

It seems like you know the critical point for my problem, can you tell me where you find problematic? 

Thank you for your effort and time.

**Comment by vnijs** [comment]
I agree that addressing the issue in Rstudio/Radiant would be better. However, the problem is specific to Windows so you could argue that an even better solution would be for Windows to properly support UTF as a standard :)

A more realistic option would be to use docker (see install instructions below). This is what we use with all our advanced business analytics students. Includes access to R, Rstudio, Radiant, Python, Jupyter, Postgres, etc.

https://github.com/radiant-rstats/docker/blob/master/install/rsm-msba-windows.md

**Comment by ycg02037** [comment]
> I agree that addressing the issue in Rstudio/Radiant would be better. However, the problem is specific to Windows so you could argue that an even better solution would be for Windows to properly support UTF as a standard :)
> 
> A more realistic option would be to use docker (see install instructions below). This is what we use with all our advanced business analytics students. Includes access to R, Rstudio, Radiant, Python, Jupyter, Postgres, etc.
> 
> https://github.com/radiant-rstats/docker/blob/master/install/rsm-msba-windows.md

I resolved the issue! Thank you so much for your time!

**Comment by vnijs** [comment]
Glad to hear that. Would you mind sharing how you resolved the issue to others can benefit from what you learned as well? Thanks!
