### ISSUE TITLE
Indent issues but I can't find any?

### ISSUE THREAD

**Issue by goldlamp95** [radiant-rstats/radiant#130]
So every time I calculate tree, the programme somehow cancels indents in my nodes... and says that there are indent issues?

<img width="466" alt="Screenshot 2020-04-09 at 11 58 52 AM" src="https://user-images.githubusercontent.com/47164731/78853319-8f1de300-7a59-11ea-87d8-0da1f8e4b244.png">
before.. I click calculate tree

<img width="509" alt="Screenshot 2020-04-09 at 11 58 56 AM" src="https://user-images.githubusercontent.com/47164731/78853324-934a0080-7a59-11ea-89bf-e008d86671b6.png">

after.. I click calculater tree

[decision tree.state.rda.zip](https://github.com/radiant-rstats/radiant/files/4453798/decision.tree.state.rda.zip)
and here's the state file for my decision tree.

**Comment by vnijs** [comment]
The "canceling of indents" is a bug that seems to occur only when you have blank lines. Please remove any fully empty lines for now and I'll fix the issue asap. However, the main issue in your (large) tree is that you are not indenting following the rules needed to evaluate the tree (see link below). Please start (much) smaller and the add components only when the smaller part works.

Some key issues issue I see in your tree: No node-type before "Before" (all node-names need a type). Only indent after a node name.

https://radiant-rstats.github.io/docs/model/dtree.html

Please also checkout the tutorial videos on decision analysis in radiant from the link below. Video 5 and 8 might be particularly useful in your setting.

https://radiant-rstats.github.io/docs/radiant-tutorial-series.html

**Comment by vnijs** [comment]
@goldlamp95 The issue you found in radiant when an empty line is present has now been fixed. If you want to install the updated version, please run the two commands below in the Rstudio console. The remaining indent issue in your decision tree input, you will have to fix on your own :)

```
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```
