### ISSUE TITLE
Radiant loading error "There was an error loading the data. Please make sure the data are in rda format."

### ISSUE THREAD

**Issue by Hokangss** [radiant-rstats/radiant#132]
I tried to open an rda file on Radiant, but the file wouldn't load, and an error message "There was an error loading the data. Please make sure the data are in rda format." appeared. I am sure the file is in rda format, and my classmates didn't have any problem opening it.
![Capture](https://user-images.githubusercontent.com/62892036/79820160-89fc5480-83c6-11ea-9cc2-dd03432d1860.PNG)

**Comment by vnijs** [comment]
Any error messages shown in R(studio)? Else, can you share the data to vnijs@ucsd.edu?

**Comment by vnijs** [comment]
The problem is that R(adiant) cannot find the file at that path due to character encoding (i.e., non-UTF). This is not something that I cannot fix but is rather an issue that many tools (e.g., R) struggle with on Windows computers. I believe a solution may be to add English as a language option for your OS.

**Comment by Hokangss** [comment]
Oh I actually found out that one of my folders (that lead to the rda. file) was in Korean. I changed the folder name into English, and the problem was solved! Thank you so much for your concern.

**Comment by vnijs** [comment]
Great! FYI This would most likely not be an issue on macOS or Linux. Windows makes working with different languages *very* complex unfortunately.

**Comment by pretty1020** [comment]
Hi @vnijs,

I got the same error using csv file.
<img width="564" alt="radiant_error" src="https://user-images.githubusercontent.com/74514827/210097570-55c52bd8-af14-4a97-b8af-424e41079b43.PNG">

 
Please help, Thanks!

**Comment by vnijs** [comment]
From the screenshot it looks like you set the separator to tab rather than "," and that you are using "." as the decimal separator. Is that what you wanted? If you can post the csv file, I can take a look.
