### ISSUE TITLE
Can't normalize by column when I can normalize by row?

### ISSUE THREAD

**Issue by goldlamp95** [radiant-rstats/radiant#133]
Hi, I'm having a problem with normalizing my pivot table.
Below are my results when I attempt to normalize my datatable by (in the order of) row and column.

<img width="836" alt="Screenshot 2020-05-09 at 11 40 04 AM" src="https://user-images.githubusercontent.com/47164731/81461927-0e820c00-91ea-11ea-877b-5803da455fad.png">
This is when I haven't normalized anything

<img width="820" alt="Screenshot 2020-05-09 at 11 40 10 AM" src="https://user-images.githubusercontent.com/47164731/81461929-10e46600-91ea-11ea-9fc7-280647c35b30.png">
This is when I normalized my data table by row

<img width="800" alt="Screenshot 2020-05-09 at 11 40 16 AM" src="https://user-images.githubusercontent.com/47164731/81461932-12ae2980-91ea-11ea-8e47-5e0bd14ae83a.png">
This is when I normalized my data table by column.

I'm also posting my radiant state file below.
The problem is my professor doesn't seem to have a problem when he normalized his data table (we're using the same datasets) by column and row with the variables in the same order.

H

[insurance pivot.state.rda.zip](https://github.com/radiant-rstats/radiant/files/4602509/insurance.pivot.state.rda.zip)

**Comment by vnijs** [comment]
Seems there was an issue with a package that Radiant depends on. Please run the command below and then restart radiant. You may need to restart Rstudio as well. 

`install.packages("tibble")`

**Comment by vnijs** [comment]
This should now also be fixed by updating Radiant (_Addins > Update radiant_). Thanks for reporting @goldlamp95

**Comment by goldlamp95** [comment]
> This should now also be fixed by updating Radiant (_Addins > Update radiant_). Thanks for reporting @goldlamp95

Thanks! I fixed the problem when I ran the install code. I updated radiant just in case.
