### ISSUE TITLE
installing Radiant on Mac OS Catalina

### ISSUE THREAD

**Issue by jlousada315** [radiant-rstats/radiant#134]
Installation not working properly when typing in Rstudio console:
install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/")

Following error pops:
ERROR: dependencies 'radiant.data', 'radiant.design', 'radiant.basics', 'radiant.model', 'radiant.multivariate' are not available for package 'radiant'
* removing '/Users/opt/anaconda3/lib/R/library/radiant'
Warning in install.packages :
  installation of package 'radiant' had non-zero exit status

The downloaded source packages are in
	'/private/var/folders/r1/6976wc_10_x3rtp63k8flh3w0000gn/T/RtmpF6OfbI/downloaded_packages'
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

**Comment by vnijs** [comment]
Please try the below first and see what issues pop up, if any. 

install.packages("radiant.data")

**Comment by jlousada315** [comment]
I got it, thanks. 

The problem is when you have Rstudio installed via Anaconda, it doesn't work. Installed RStudio from the website and it worked. 

What a great tool Radiant is, thank you.

**Comment by vnijs** [comment]
Thanks for the update @johnnylousas. I have never used Rstudio via Anaconda. Still strange that it wouldn't work there.
