### ISSUE TITLE
Ubuntu LINUX  18.04 Radiant install exits w/ "installation of package ‘radiant’ had non-zero exit status"

### ISSUE THREAD

**Issue by sfd99** [radiant-rstats/radiant#135]
**_Hi Vincent,_**

Tried Radiant online version.
_It's wonderful!._

I then tried to install the Radiant package 
in my Rstudio,
following the **_"LINUX INSTALLATION"_** instructions 
in page:
   https://radiant-rstats.github.io/docs/install.html

As prescribed, I entered:
   R -e "source('https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R')"

I get miles of messages with:
   "...had non-zero exit status",
and Radiant is not installed...

I also tried installing Radiant w/ the "Install" button
in the Rstudio Packages Pane.
Same miles of error messgs,
with : 
  "...had non-zero exit status".

**_btw:_**  have no problem 
installing any other R pkgs. _Argh_...

Help!.
**sfd99
SF
R 3.6.3 (latest)
Rstudio version 1.3.959 (latest)
Ubuntu Linux 18.04 64bits.**

**Comment by vnijs** [comment]
Did you install the required linux tools as well? From the install page:

```
## Install ... required linux tools
sudo apt-get install libssl-dev libcurl4-openssl-dev libxml2-dev libicu-dev \
  unixodbc-dev libpq-dev libgdal-dev libproj-dev libcairo2-dev cargo libgsl-dev
```

**Comment by sfd99** [comment]
ok, Vincent!
thanks f/the quick reply...
will try that right now and report to you.

**Comment by sfd99** [comment]
OK! 
# Finished Installing required linux tools with:
sudo apt-get install libssl-dev libcurl4-openssl-dev libxml2-dev libicu-dev \
  unixodbc-dev libpq-dev libgdal-dev libproj-dev libcairo2-dev cargo libgsl-dev

What is the command I should enter next
to install Radiant? .
_Thanks for your patience, Vincent..._

**sfd99
SF
R 3.6.3 (latest)
Rstudio version 1.3.959 (latest)
Ubuntu Linux 18.04 64bits.**

**Comment by vnijs** [comment]
`R -e "source('https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R')"`

And to double-check your have everything:

`R -e "radiant.update::radiant.update()"`

**Comment by sfd99** [comment]
**ok Vincent!** 
trying the above commands, 
right now.
Will report back shortly...

**Comment by sfd99** [comment]
**_from Terminal:_**

R -e "source('https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R')"

R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> source('https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R')

#################################################
Installing new packages
#################################################

Installing package into ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://rsm-compute-01.ucsd.edu:4242/rsm-msba/__linux__/bionic/latest/src/contrib/radiant_1.3.2.0.0.0.1589523726.tar.gz'
Content type 'application/x-gzip' length 996394 bytes (973 KB)
==================================================
downloaded 973 KB

ERROR: dependencies ‘radiant.data’, ‘radiant.design’, ‘radiant.basics’, ‘radiant.model’, ‘radiant.multivariate’ are not available for package ‘radiant’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6/radiant’

The downloaded source packages are in
	‘/tmp/RtmpCNyexJ/downloaded_packages’
Installing package into ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://rsm-compute-01.ucsd.edu:4242/rsm-msba/__linux__/bionic/latest/src/contrib/radiant.basics_1.3.4.0.0.0.1584989914.tar.gz'
Content type 'application/x-gzip' length 2969144 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

ERROR: dependency ‘radiant.data’ is not available for package ‘radiant.basics’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6/radiant.basics’

The downloaded source packages are in
	‘/tmp/RtmpCNyexJ/downloaded_packages’
Installing package into ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://rsm-compute-01.ucsd.edu:4242/rsm-msba/__linux__/bionic/latest/src/contrib/radiant.data_1.3.9.0.0.0.1592291950.tar.gz'
Content type 'application/x-gzip' length 1827868 bytes (1.7 MB)
==================================================
downloaded 1.7 MB

* installing *source* package ‘radiant.data’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘mnormt’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘radiant.data’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6/radiant.data’

The downloaded source packages are in
	‘/tmp/RtmpCNyexJ/downloaded_packages’
Installing package into ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://rsm-compute-01.ucsd.edu:4242/rsm-msba/__linux__/bionic/latest/src/contrib/radiant.design_1.3.5.0.0.0.1585038066.tar.gz'
Content type 'application/x-gzip' length 1355365 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

ERROR: dependency ‘radiant.data’ is not available for package ‘radiant.design’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6/radiant.design’

The downloaded source packages are in
	‘/tmp/RtmpCNyexJ/downloaded_packages’
Installing package into ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://rsm-compute-01.ucsd.edu:4242/rsm-msba/__linux__/bionic/latest/src/contrib/radiant.model_1.3.13.0.0.0.1594515540.tar.gz'
Content type 'application/x-gzip' length 7701179 bytes (7.3 MB)
==================================================
downloaded 7.3 MB

ERROR: dependencies ‘radiant.data’, ‘radiant.basics’ are not available for package ‘radiant.model’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6/radiant.model’

The downloaded source packages are in
	‘/tmp/RtmpCNyexJ/downloaded_packages’
Installing package into ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://rsm-compute-01.ucsd.edu:4242/rsm-msba/__linux__/bionic/latest/src/contrib/radiant.multivariate_1.3.5.0.0.0.1585094664.tar.gz'
Content type 'application/x-gzip' length 3825038 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

ERROR: dependencies ‘radiant.data’, ‘radiant.model’ are not available for package ‘radiant.multivariate’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6/radiant.multivariate’

The downloaded source packages are in
	‘/tmp/RtmpCNyexJ/downloaded_packages’

Testing if Radiant can be loaded ...

Radiant update attempt was unsuccessful. Please copy the source command below, restart R(studio), and then paste the command into the R(studio) console and press return. If the update is still not successful, please send an email to radiant@rady.ucsd.edu with screen shots of the output shown in R(studio).

source('https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R')

-------------------------------------------------------------------------------------

Warning messages:
1: In install.packages(p, repos = repos_fun, type = type, dependencies = FALSE) :
  installation of package ‘radiant’ had non-zero exit status
2: In install.packages(p, repos = repos_fun, type = type, dependencies = FALSE) :
  installation of package ‘radiant.basics’ had non-zero exit status
3: In install.packages(p, repos = repos_fun, type = type, dependencies = FALSE) :
  installation of package ‘radiant.data’ had non-zero exit status
4: In install.packages(p, repos = repos_fun, type = type, dependencies = FALSE) :
  installation of package ‘radiant.design’ had non-zero exit status
5: In install.packages(p, repos = repos_fun, type = type, dependencies = FALSE) :
  installation of package ‘radiant.model’ had non-zero exit status
6: In install.packages(p, repos = repos_fun, type = type, dependencies = FALSE) :
  installation of package ‘radiant.multivariate’ had non-zero exit status
7: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘radiant’


------------------------
# then...
R -e "radiant.update::radiant.update()"

R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> radiant.update::radiant.update()
trying URL 'https://rsm-compute-01.ucsd.edu:4242/rsm-msba/__linux__/focal/latest/src/contrib/radiant_1.3.2.0.0.0.1589523726.tar.gz'
Content type 'application/x-gzip' length 996394 bytes (973 KB)
==================================================
downloaded 973 KB

trying URL 'https://rsm-compute-01.ucsd.edu:4242/rsm-msba/__linux__/focal/latest/src/contrib/radiant.basics_1.3.4.0.0.0.1584989914.tar.gz'
Content type 'application/x-gzip' length 2969144 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

trying URL 'https://rsm-compute-01.ucsd.edu:4242/rsm-msba/__linux__/focal/latest/src/contrib/radiant.data_1.3.9.0.0.0.1592291950.tar.gz'
Content type 'application/x-gzip' length 1827868 bytes (1.7 MB)
==================================================
downloaded 1.7 MB

trying URL 'https://rsm-compute-01.ucsd.edu:4242/rsm-msba/__linux__/focal/latest/src/contrib/radiant.design_1.3.5.0.0.0.1585038066.tar.gz'
Content type 'application/x-gzip' length 1355365 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

trying URL 'https://rsm-compute-01.ucsd.edu:4242/rsm-msba/__linux__/focal/latest/src/contrib/radiant.model_1.3.13.0.0.0.1594515540.tar.gz'
Content type 'application/x-gzip' length 7701179 bytes (7.3 MB)
==================================================
downloaded 7.3 MB

trying URL 'https://rsm-compute-01.ucsd.edu:4242/rsm-msba/__linux__/focal/latest/src/contrib/radiant.multivariate_1.3.5.0.0.0.1585094664.tar.gz'
Content type 'application/x-gzip' length 3825038 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

* installing *source* package ‘radiant.data’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘mnormt’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘radiant.data’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6/radiant.data’
ERROR: dependency ‘radiant.data’ is not available for package ‘radiant.basics’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6/radiant.basics’
ERROR: dependency ‘radiant.data’ is not available for package ‘radiant.design’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6/radiant.design’
ERROR: dependencies ‘radiant.data’, ‘radiant.basics’ are not available for package ‘radiant.model’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6/radiant.model’
ERROR: dependencies ‘radiant.data’, ‘radiant.model’ are not available for package ‘radiant.multivariate’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6/radiant.multivariate’
ERROR: dependencies ‘radiant.data’, ‘radiant.design’, ‘radiant.basics’, ‘radiant.model’, ‘radiant.multivariate’ are not available for package ‘radiant’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6/radiant’

The downloaded source packages are in
	‘/tmp/RtmpgMa5bR/downloaded_packages’

Testing if Radiant can be loaded ...
Failed with error:  ‘there is no package called ‘radiant’’
In addition: Warning messages:
1: In install.packages(c("radiant", "radiant.basics", "radiant.data",  :
  installation of package ‘radiant.data’ had non-zero exit status
2: In install.packages(c("radiant", "radiant.basics", "radiant.data",  :
  installation of package ‘radiant.basics’ had non-zero exit status
3: In install.packages(c("radiant", "radiant.basics", "radiant.data",  :
  installation of package ‘radiant.design’ had non-zero exit status
4: In install.packages(c("radiant", "radiant.basics", "radiant.data",  :
  installation of package ‘radiant.model’ had non-zero exit status
5: In install.packages(c("radiant", "radiant.basics", "radiant.data",  :
  installation of package ‘radiant.multivariate’ had non-zero exit status
6: In install.packages(c("radiant", "radiant.basics", "radiant.data",  :
  installation of package ‘radiant’ had non-zero exit status

Radiant update attempt was unsuccessful. Please restart R(studio) and run the update (radiant.update::radiant.update()) or sync (radiant.update::sync_packages()) command again. If update (sync) is still not successful, please send an email to radiant@rady.ucsd.edu with screen shots of the output shown in R(studio).
============

**Comment by vnijs** [comment]
The "radiant" package will only install if radiant.data, etc. are already installed. Please try just installing radiant.data and report *all* message from that install if it doesn't succeed. Please also use "```", but without the quotes before and after your code/output so it is formatted properly. Check the "Preview" tab to see out the posted output will look.

**Comment by sfd99** [comment]
Ok, Vincent - tried to install just radiant.data
(+ now using 3 backticks,
 before & after code..sorry for that...).
RESULTS below:
```
> install.packages("radiant.data")
Installing package into ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/radiant.data_1.3.9.tar.gz'
Content type 'application/x-gzip' length 1845283 bytes (1.8 MB)
==================================================
downloaded 1.8 MB

* installing *source* package ‘radiant.data’ ...
** package ‘radiant.data’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘mnormt’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘radiant.data’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6/radiant.data’
Warning in install.packages :
  installation of package ‘radiant.data’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp1dOo3X/downloaded_packages’
```

**Comment by vnijs** [comment]
OK. Now see the message about "mnormt". For some reason, that failed so try the below. Repeat as needed :)

`install.packages('mnormt')`

**Comment by sfd99** [comment]
Ok...just a minute...

**Comment by sfd99** [comment]
**_Vincent - ALMOST THERE!_**

Below are ALL the **Installation steps** 
which _worked_ in my case,
(for posterity and those who might have similar install problems)...

Based on Vincent's patient advice in this thread:

**0)** Install several additional Linux tools f/ Terminal. 
In  Ubuntu 18.04 :

```
sudo apt-get install libssl-dev libcurl4-openssl-dev libxml2-dev libicu-dev \
  unixodbc-dev libpq-dev libgdal-dev libproj-dev libcairo2-dev cargo libgsl-dev
```

**1)**   Install the _previous version_ of pkg: 
mnormt - version 1.5.7,
(which does _not require version R >= 4.0_ 
unlike the latest mnormt 2.0.0!) 

I still have R 3.6.3, not R 4.00+...

> require(devtools)
> install_version("mnormt", version = "1.5-7", repos = "http://cran.us.r-project.org")

OK! mnormt 1.5.7 (prev version) installed fine. Yay!

**2)** Then...
> install.packages("radiant.data")
> library(radiant.data)

Now, Rstudio Package Pane shows these new pkgs:

radiant.basics
radiant.data
radiant.design
radiant.model
radiant.multivariate
radiant.update

Getting closer....

**3)** Then, RESTART Rstudio 
AND finally, from Terminal:

R -e "source('https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R')"

**RESULT:**
```
$ R -e "source('https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R')"

R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.   Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> source('https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R')

#################################################
Installing new packages
#################################################

Installing package into ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://rsm-compute-01.ucsd.edu:4242/rsm-msba/__linux__/bionic/latest/src/contrib/radiant_1.3.2.0.0.0.1589523726.tar.gz'
Content type 'application/x-gzip' length 996394 bytes (973 KB)
==================================================
downloaded 973 KB

* installing *source* package ‘radiant’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (radiant)

The downloaded source packages are in
        ‘/tmp/Rtmp5xOHIi/downloaded_packages’

Testing if Radiant can be loaded ...

Radiant update successfully completed

```

_AND_... radiant v. 132000 1589...
finally appears in my Rstudio Packages Pane. YAY!

**Ok Vincent.
How do I start the great Radiant in my Rstudio?.**
**Ans:**   > radiant::radiant()

**Comment by vnijs** [comment]
https://radiant-rstats.github.io/docs/install.html

"
Starting, Stopping, and Updating Radiant
I recommend you use Rstudio to run the Radiant application. When you open Rstudio you can start Radiant through the Addins menu at the top of the screen Start radiant (browser). If for some reason the Start radiant (browser) is not shown in the dropdown, enter radiant::radiant() in the Rstudio console. To close the application click the  icon in the navigation bar and then click Stop. The Radiant process will stop and the browser window will close or gray-out.

To add an option to upgrade Radiant easily, use the commands below to install the radiant.upgrade package. You should now see two new item in the Addins dropdown that you can use for future radiant upgrades.
"

**Comment by sfd99** [comment]
**GREAT! 
Radiant opened in Chrome browser.**

You wrote:
"To add an option to upgrade Radiant easily, use the commands below to install the radiant.upgrade package. "

but your last message was cut off 
after that sentence, above.

**_What are those commands you mention?_**

**Comment by sfd99** [comment]
Ok, found the last missing commands
in the Radiant instructions page.

**THANK YOU SO MUCH, Vincent!!!**
You (and Radiant...) are the greatest.
Stay safe down in San Diego, my friend!.
