### ISSUE TITLE
Radiant Launcher doesn't launch browser

### ISSUE THREAD

**Issue by emmerst** [radiant-rstats/radiant#136]
Hi,

I tried to install the Radiant launcher to my desktop, but every time I double click the .bat file (on Windows), it loads a bunch of packages and then disappears. The browser never launches. Does anyone know why this might be happening?

Appreciate any thoughts or support!

**Comment by vnijs** [comment]
@emmerst I haven't looked at the launcher code in a long time but I'll try to find some time to review soon. That said, I highly recommend you launch Radiant from Rstudio. See install instructions + video below.

https://youtu.be/16B5SvtW8Ks

https://radiant-rstats.github.io/docs/install.html

**Comment by vnijs** [comment]
@emmerst Thanks again for reporting. I was able to reproduce the problem on Windows and it should be fixed now. Please run the code below to get the fix and create a new launcher on your Desktop. If you still have problems, please reopen the issue. However, I still recommend you start Radiant from Rstudio.

```
install.packages("remotes")
remotes::install_github("radiant-rstats/radiant.data", upgrade = "never")
radiant::win_launcher()
```
