### ISSUE TITLE
R version 4

### ISSUE THREAD

**Issue by DataScienceSurfer** [radiant-rstats/radiant#138]
When will radiant be available for R version 4?

Warning in install.packages :
  package ‘radiant’ is not available (for R version 4.0.2)

**Comment by Oromendia** [comment]
I am also having trouble installing radiant from here. I am able to install `radiant.update` without a problem, and can also install the CRAN version of radiant. 

`install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/")`

**Comment by vnijs** [comment]
I can reproduce on Windows. Is that the platform you are on as well? The below should still work. I'll look into this soon. 

```
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```

FYI Full install instructions are listed below.

https://radiant-rstats.github.io/docs/install.html

**Comment by DataScienceSurfer** [comment]
correct I am installing on windows
This is what I am getting

Warning in install.packages :
  package ‘radiant’ is not available (for R version 4.0.2)

**Comment by vnijs** [comment]
The below should work to install the latest version of radiant

```
options(repos = c(RSM = "https://radiant-rstats.github.io/minicran", CRAN = "https://cloud.r-project.org"))
install.packages("radiant")
```

**Comment by aj-devops-wi** [comment]
> 
> 
> The below should work to install the latest version of radiant
> 
> ```
> options(repos = c(RSM = "https://radiant-rstats.github.io/minicran", CRAN = "https://cloud.r-project.org"))
> install.packages("radiant")
> ```

That appears to work - perhaps the documentation on https://radiant-rstats.github.io/docs/install.html could be changed.

**Comment by vnijs** [comment]
Thanks for checking @aj-devops-wi. That information is on the pages below:

https://radiant-rstats.github.io/docs/index.html
https://radiant-rstats.github.io/docs/install.html
