### ISSUE TITLE
radiant.init.data option doesn't work

### ISSUE THREAD

**Issue by ffalcolini** [radiant-rstats/radiant#139]
Hi,

I would like to use an alternative set of .rda files with data.frames as the default.
I try to use this option: 

 options(radiant.init.data = list.files(path = "data/", full.names = TRUE))

But it doesn't work.
Do you have any ideas to help me?

I put some rds files in the folder "data".
The variable "radiant.init.data" contains the list of files in the folder.
But Radiant always uses the same data files

Thanks a lot

**Comment by vnijs** [comment]
Please try this with (1) the absolute path and (2) .rda files. For example, the below should work fine.

```
options(radiant.init.data = list.files(path = "~/Desktop/rdata/", full.names = TRUE))
```
