### ISSUE TITLE
Installing RStudio on Windows

### ISSUE THREAD

**Issue by hlhardenberg** [radiant-rstats/radiant#141]
I have click to run the RStudio Installer. The black script box continuously runs. I finally got it to where it said download had 'Finished', but I cannot find the installed program on my computer. The only option it gives me is to continuously run the Installer. Please help.

**Comment by vnijs** [comment]
I assume you use the install instructions here: https://radiant-rstats.github.io/docs/install.html

Is so, then you have to start Rstudio and Choose Radiant from the Addins Dropdown.  Take another look at the video and all should be clear. If not, post again.

https://youtu.be/16B5SvtW8Ks

**Comment by vnijs** [comment]
Closing ...
