### ISSUE TITLE
Radiant not displaying model results

### ISSUE THREAD

**Issue by NagaRady** [radiant-rstats/radiant#145]
Radiant not displaying regression model results under summary tab. Attached is the screenshot. The place where we are supposed to see the regression coefficients etc., is just empty even after selecting dependent and independent variables and clicking on "Estimate Model". 

Note: The browsers I used are both Firefox and Chrome. Issue exists both the browsers. My laptops runs with Windows 10 OS. Both R and RStudio versions are up to date.

![Error](https://user-images.githubusercontent.com/24913565/100332610-9a794b00-2ff7-11eb-8bd7-022f2f368f42.JPG)

**Comment by hermandr** [comment]
Hi I am experiencing the same thing.
When I ran it yesterday it was normal.
Today I did a radiant update.
I tried to remove packages and re-installed but no change.

**Comment by vnijs** [comment]
Thanks for reporting. This is due to a breaking change in the `magrittr` package that Radiant uses. A new version of radiant.data is already on its way to CRAN but temporary work arounds are shown below

```
install.packages("remotes")
remotes::install_github("radiant-rstats/radiant.data", upgrade = "never")
```

Or try:

```
remotes::install_version("magrittr", version = "1.5")
```

**Comment by hermandr** [comment]
Thank you for responding.
I have done the update as your instruction.
```
> remotes::install_github("radiant-rstats/radiant.data", upgrade = "never")
Downloading GitHub repo radiant-rstats/radiant.data@HEAD
√  checking for file 'C:\Users\herma\AppData\Local\Temp\RtmpcXRCTZ\remotes64dc69571965\radiant-rstats-radiant.data-b0e166c/DESCRIPTION' (716ms)
-  preparing 'radiant.data': (7.4s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (1.9s)
-  checking for empty or unneeded directories
-  building 'radiant.data_1.3.12.tar.gz'
   
Installing package into ‘C:/Users/herma/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'radiant.data' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'magrittr' was built under R version 4.0.3
Execution halted
ERROR: lazy loading failed for package 'radiant.data'
* removing 'C:/Users/herma/Documents/R/win-library/4.0/radiant.data'
* restoring previous 'C:/Users/herma/Documents/R/win-library/4.0/radiant.data'
Error: Failed to install 'radiant.data' from GitHub:
  (converted from warning) installation of package ‘C:/Users/herma/AppData/Local/Temp/RtmpcXRCTZ/file64dcc443ab0/radiant.data_1.3.12.tar.gz’ had non-zero exit status
```

What do I do to fix this?

**Comment by vnijs** [comment]
R sometimes has issues installing directly from github. The new version of radiant.data is on its way to CRAN and should be available in a few days. If you can't wait, try installing a previous version of the `magrittr` package

**Comment by NagaRady** [comment]
Thank you Professor. I uninstalled my current version of magrittr and
installed version 1.5. It worked.
I will update my margrittr version once the new version of radiant.data is
available. Will let you know if I face any issues at that time.


Regards,
Naga

**Comment by vnijs** [comment]
Thanks for confirming Naga!
