### ISSUE TITLE
Basics Section not working

### ISSUE THREAD

**Issue by AndrewFust** [radiant-rstats/radiant#146]
Hello everyone, I'm new to R, RStudio, and Radiant. everything worked fine until yesterday I encountered problems in doing hypothesis testing on Radiant. Whenever I open the Basics Area and I go to either Single Mean or Compare Means, the "Summary" section won't display anything. The plot section runs smoothly, but in the summary section I'm just staring at a white blank screen.
Thank you in advance for any help.

**Comment by vnijs** [comment]
Thanks for reporting. This is due to a breaking change in the `magrittr` package that Radiant uses. A new version of radiant.data is already on its way to CRAN but temporary work arounds are shown below

```
install.packages("remotes")
remotes::install_github("radiant-rstats/radiant.data", upgrade = "never")
```

Or try:

```
remotes::install_version("magrittr", version = "1.5")
```

**Comment by AndrewFust** [comment]
Thank you Sir for your prompt answer. I ran the second line of code and it seems to work now. Just to let you know, when running the first line fo code you sent the console reported at the end what follows:




Error: (converted from warning) package 'magrittr' was built under R version 4.0.3
Execution halted
ERROR: lazy loading failed for package 'radiant.data'
* removing 'C:/Users/39347/OneDrive/Documents/R/win-library/4.0/radiant.data'
* restoring previous 'C:/Users/39347/OneDrive/Documents/R/win-library/4.0/radiant.data'
Error: Failed to install 'radiant.data' from GitHub:
  (converted from warning) installation of package ‘C:/Users/39347/AppData/Local/Temp/RtmpekrDeC/file474c1dfb40a0/radiant.data_1.3.12.tar.gz’ had non-zero exit status

**Comment by vnijs** [comment]
Thanks for reporting the Error. This is either because you don't have Rtools installed (see link below) or because your R-packages in OneDrive/Documents. Since you have this working you should be fine for now

https://cran.r-project.org/bin/windows/Rtools/

**Comment by AndrewFust** [comment]
I guess it's the second option as I had already downloaded Rtools. Anyway, thank you for the response! Have a nice day
