### ISSUE TITLE
Cannot save .csv, rda, rds

### ISSUE THREAD

**Issue by BadgerDaniel** [radiant-rstats/radiant#148]
Attempting to save data in any format other than radiantstate is impossible. 
It shows the saving/loading bar briefly before making the screen covered in a grey tint, and the file is not downloaded or saved.

**Comment by BadgerDaniel** [comment]
before running radiant

install.packages("readr")

**Comment by vnijs** [comment]
I cannot reproduce. Are there any messages shown in Rstudio or is this on a server? The more detail you can provide the better.

**Comment by vnijs** [comment]
@BadgerDaniel Can you provide more information so I can try to reproduce the issue you are seeing?

**Comment by vnijs** [comment]
Closing for now. I can't replicate and there was no follow up from OP
