### ISSUE TITLE
Radiant is deleting variables?

### ISSUE THREAD

**Issue by bradleyrava** [radiant-rstats/radiant#150]
I am using Radiant for one of my classes and a few students have noticed that after they have added new variables to their data frame and clicked "store", Radiant deletes these transformations after they go through a few more tabs. Are there any quick fixes for this?

Thank you!

**Comment by vnijs** [comment]
I have not seen or heard about this issue. Can you reproduce? One thing that might be happening is that a student creates a new variable in Data > Transform, for example, and then reloads a dataset, e.g., through the R > Rmarkdown feature. That will, of course, reset the dataframe and delete the variable. The (reproducible) solution is that you put code to do the loading of data and the transformations all in to the report.

https://youtu.be/pNNQc2lHR8Q

**Comment by vnijs** [comment]
Closing for now. If you have more information, please let me know.
