### ISSUE TITLE
HTML document from R Markdown

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#151]
When I save HTML files or Knit reports in Radiant, many of the custom HTML code I add doesn't render even when I add 
 %>% render()

I want to change the tab name (title) of the HTML I save.  I'd also like to add tabs.  The code for this seems straight forward, but it doesn't seem to work

https://bookdown.org/yihui/rmarkdown/html-document.html

![image](https://user-images.githubusercontent.com/36533710/114960358-b4d38a00-9e1b-11eb-9115-00b22d3fc502.png)

**Comment by vnijs** [comment]
The "preview" you see in Radiant does not use Rmarkdown but knitr for various reasons. If you save the report to html or notebook format however this will work fine. See screenshot below

![image](https://user-images.githubusercontent.com/2998956/115101446-0867d580-9ef9-11eb-9e92-d91e67becf23.png)

**Comment by josh1400** [comment]
Thanks :)
