### ISSUE TITLE
Can't install radiant for R version 3.6.0

### ISSUE THREAD

**Issue by dieter-wilhelm** [radiant-rstats/radiant#152]
Hello

In your github home page you are saying that Radiant should work with "R 3.4.0 and later" but when I'm doing

```
 install.packages("radiant", repos = "https://radiant-rstats.github.io/minicrInstalling package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
```
it says:

```
Warning message:
package ‘radiant’ is not available (for R version 3.6.0)
```

is there a workaround to get it to run with R 3.6.0?

**Comment by vnijs** [comment]
What exactly was the process you were following? Where/when did you get this message?

Can you try the below? 

```
options(repos = c(RSM = "https://radiant-rstats.github.io/minicran", CRAN = "https://cloud.r-project.org"))
install.packages("radiant.update")
```

https://radiant-rstats.github.io/docs/install.html

**Comment by dieter-wilhelm** [comment]
I did the exact commands in R as indicated in my first comment, nothing else.  But above information is dated now, in the meantime I learned to update R for an Ubuntu 18.04 system. And I'm now in R 4.0.5, installed Radiant and it seems to work on my shiny server (in version 1.3.2)!

Thanks a lot for Radiant

**Comment by vnijs** [comment]
Glad to hear that @dieter-wilhelm
