### ISSUE TITLE
Error for Visualize 

### ISSUE THREAD

**Issue by Marie-Ann-S** [radiant-rstats/radiant#153]
Hey,

I am using radiant for my stats class and some of my students report the following error, when opining the Visualize Part of the GUI: 

The 'markdown' package should be installed and declared as a dependency of the 'radiant' package (e.g., in the 'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'markdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.

relevant packages like markdown, rmarkdown and knitr are already installed, but the error remains. Do you have an idea on this? It orrurs only at the devices of some of the students, but I coudn't find any systematic pattern, so far. 

Best,

Marie-Ann

**Comment by vnijs** [comment]
@Marie-Ann-S is this a warning shown in Rstudio or a error that you see in Radiant? Can you share a screenshot?

**Comment by Marie-Ann-S** [comment]
@vnijs  Thank you for the fast response! 

Here are screenshots from the GUI and the Console.

Best, Marie-Ann 

![Bildschirmfoto 2021-05-05 um 08 05 04](https://user-images.githubusercontent.com/35803772/117104030-b8539480-ad7b-11eb-8499-0c6c570efa46.png)
![Fehlermeldung console](https://user-images.githubusercontent.com/35803772/117104036-ba1d5800-ad7b-11eb-8875-2008afdd16cf.png)

**Comment by vnijs** [comment]
I wonder why that warning is translated into an error. Very odd. Anyway, can you ask the students that are seeing this issue to run the code below? Since I cannot reproduce the issue I'd need confirmation that this fixes the problem before submitting to CRAN. 

Thanks again for reporting!

```
install.packages("remotes")
remotes::install_github("radiant-rstats/radiant", upgrade = "never", force=TRUE)
```

**Comment by Marie-Ann-S** [comment]
@vnijs The new version worked for all of my students - they can now use Visualize without any problems (only one student has problems with the installation, but I think that is a more general Mac problem occuring for installations from Github). 

Thank you so much for the fast help!

**Comment by vnijs** [comment]
Thanks for letting me know @Marie-Ann-S. I'll push this new version to CRAN. Thanks again for reporting this issue!
