### ISSUE TITLE
Oversampling

### ISSUE THREAD

**Issue by NagaRady** [radiant-rstats/radiant#154]
Hello Professor Nijs,

I'm trying to build a logistic regression model to predict the "default" probability of a borrower. But my response variable is unbalanced. The ratio of default to non default borrowers is 10 : 90. I want to use "oversampling" technique to address this problem. How do I do that in Radiant? I've gone through the help documents but can't find any information on that.  Can you please help me.

Regards,
Naga

**Comment by vnijs** [comment]
Unbalanced data is not really an issue for logistic regression. If, however, you want to apply weights you can add a column "weights" to your data frame and select the variable in the Weights dropdown on the Summary page for logistic regression.

**Comment by NagaRady** [comment]
Thank you professor. Will do that.


Regards,
Naga
