### ISSUE TITLE
Error on "Visualize" tab of "Data" section

### ISSUE THREAD

**Issue by carbog** [radiant-rstats/radiant#155]
The 'markdown' package should be installed and declared as a dependency of the 'radiant' package (e.g., in the 'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'markdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.

![image](https://user-images.githubusercontent.com/50428414/119037674-221c9280-b967-11eb-94e2-8e4f98f43132.png)

**Comment by vnijs** [comment]
Thanks for reporting @carbog. I am trying to get the updated version of radiant on CRAN but there is a weird build issue on Windows (see below). For now, please use `remotes::install_github('radiant-rstats/radiant')`
