### ISSUE TITLE
Setting up path for directory to target my server side

### ISSUE THREAD

**Issue by MackyKavinsky** [radiant-rstats/radiant#156]
Hi, currently i am trying to implement to set the default directory to a path (link of my server) for browsing the dataset from the server. Currently i face 2 problem:

1. How can i set my server path (link) on the radiant (through codes)?
2. How can i set it to default (toward my server location or directory) for user when user click browse (i want to set it up through codes instead of setting working directory through Rstudio or R command line)?

Your help is appreciated! Sorry just started playing with R.

**Comment by vnijs** [comment]
Take a look at the issue below that should help address your question.

https://github.com/radiant-rstats/radiant/issues/139

**Comment by MackyKavinsky** [comment]
What i did try, was setting path on the rprofile. It works on my local machine, however when I try to upload on the server and try to connect the upload button to a directory in the server, it doesnt work.

rProfile
options(radiant.sf_volumes=c(D = "D://", C = "C://", server = "/mnt/hadoop/swat_clean_db/"))

I added this on my rprofile using usethis::edit_r_profile(), and apparently it doesnt work. Do i need to set a path directly inside the radiant.data codes?

**Comment by vnijs** [comment]
Are you launching from Rstudio on the server? If so, that should work just fine.

If you are using shiny server you would have to add information to .rprofile of the shiny user most likely.

Your example show "C://" which suggests you are on windows and "/mnt/" which suggests you are on linux (or WSL2). The combination you are showing is not likely to work on any system.

**Comment by MackyKavinsky** [comment]
options(radiant.sf_volumes=c(D = "D:\", C = "C:\", server = "https://*********.my/fileset/swat_clean_db/"))

should this combination is work? (the ****** is the link of my server database which is an external access)

and i edited on the console of server for the rprofile lines of codes after using usethis::edit_r_profile() command. 

![image](https://user-images.githubusercontent.com/34124958/119751112-23047580-becd-11eb-8cb8-8564db823036.png)

**Comment by vnijs** [comment]
Nope. It need to be a file system. You can can add code to connect to a database in `Report > Rmd` and pull down a some data into a dataframe to use with Radiant. Something like the below

```
mydata <- {insert code to extra data from database}
register("mydata")
```

**Comment by MackyKavinsky** [comment]
Sir, do i need to make a connection to the database? Because, i view a video on datacamp of R that it required to connect to the database to access the file. Is it possible to use that in Radiant?

**Comment by vnijs** [comment]
Please see the below on how to connect to databases from R. 

https://db.rstudio.com/

Rstudio community is a great place to ask general R questions like this.

https://community.rstudio.com/

For this to work with Radiant you would write code to connect to the database in _Report > Rmd_, pull data from the databased into a dataframe, and then add `register("mydata")` in your Rmd document to access the dataframe from Radiant.
