### ISSUE TITLE
Error at Visualization Tab

### ISSUE THREAD

**Issue by NagaRady** [radiant-rstats/radiant#157]
I see an error message when I go to visualization tab. I took a screenshot of the error and attached it here. I tried installing "markdown" package like mentioned in the error message, but it didn't work. Can you please help.
![Error at Visualization Tab](https://user-images.githubusercontent.com/24913565/120512144-14203600-c399-11eb-8318-33e11dcd56f3.JPG)
 [](url)

**Comment by vnijs** [comment]
Thanks for reporting. I am trying to get the updated version of radiant on CRAN but there is a weird build issue on Windows. For now, please use remotes::install_github('radiant-rstats/radiant')

**Comment by NagaRady** [comment]
Hello Professor,

I just got a chance to install radiant using the code you provided. (
remotes::install_github('radiant-rstats/radiant') ). But, I still see the
error.


Regards,
Naga

**Comment by vnijs** [comment]
Did you restart R and/or Rstudio? Should work fine.

**Comment by NagaRady** [comment]
Yes Professor, I did. I actually got warning messages when I ran the
command you gave. Attached are the warings (in case it's useful).

Regards,
Naga

**Comment by vnijs** [comment]
I don't see the attachments on GitHub. Can you post them directly to the issue linked below? Thanks

https://github.com/radiant-rstats/radiant/issues/157

**Comment by NagaRady** [comment]
It's here
![WM](https://user-images.githubusercontent.com/24913565/121107971-ed1d9600-c7d6-11eb-8383-a5bcf0f58acd.JPG)

**Comment by vnijs** [comment]
Thanks! The messages show that the new version of radiant was not installed. Please restart Rstudio first, and then run the two commands below. That should address the issue.

```
install.packages("remotes")
remotes::install_github('radiant-rstats/radiant') 
```

**Comment by NagaRady** [comment]
Thank you professor. It worked now. Not sure why it didn't work earlier. I
even restarted, uninstalled, and reinstalled R and R Studio. Anyway, it;s
working now. Thank you so much for the help.

Regards,
Naga
