### ISSUE TITLE
Save the Radiant State on the server

### ISSUE THREAD

**Issue by hedjour** [radiant-rstats/radiant#158]
Hi,
We share your app on an internal server for the team is it possible to save automatically the state of the app on the server ?
Our server is an Ubuntu 20.10 , with 
```r
R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
 ```
On R we have install radiant package by following the doc.
We cloned the radiant repository in our ShinyApps directory (Shiny is configured to use personal home of the server).
Config infos of shiny :
```   location / {
    # Host the directory of Shiny Apps stored in this directory
    app_dir /home/lnec/ShinyApps/radiant/inst/app;

    # Log all Shiny output to files in this directory
     log_dir ~/ShinyApps/log;
    # When a user visits the base URL rather than a particular application,
    # an index of the applications available in this directory will be shown.
    directory_index off;
  }
  ```
  The save menu  -> load radiant state file from Server part - loads file from client pc and not from the server is that expected ?
like the Upload radiant state file.

**Comment by vnijs** [comment]
In .Rprofile add something like. Then when you try to "Save radiant state file" a file browser should shown. 

options(radiant.sf_volumes = "/home/shiny/statefiles")

**Comment by hedjour** [comment]
It works perfectly. Many thanks to you.
Just an info Load works but Upload is now broken.

**Comment by vnijs** [comment]
Can you give a bit more information? Screenshot?

**Comment by hedjour** [comment]
Sorry finaly it fworks, I don't know why.
Maybe a time of sync of something...
I will let you know with screenshot if it reappears.

**Comment by hedjour** [comment]
Sorry finaly it fworks, I don't know why.
Maybe a time of sync of something...
I will let you know with screenshot if it reappears.
