### ISSUE TITLE
Error Message running Radiant

### ISSUE THREAD

**Issue by strak64** [radiant-rstats/radiant#16]
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’

**Comment by vnijs** [comment]
This message means that the `stringi` package was not installed. You can either install it using:

    install.packages("stringi")

or run the command below in case there are other packages that were not installed:

    source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/build.R")
