### ISSUE TITLE
Problem Installing Radiant

### ISSUE THREAD

**Issue by lukas10051** [radiant-rstats/radiant#163]
I've downloaded the newest version of R and RStudio. Afterwards I tried to install Radiant with this code : install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/", type = 'binary')
Unfortunately, every time I paste it, the following appears and I can not launch radiant:

> install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/", type = 'binary')
versuche URL 'https://radiant-rstats.github.io/minicran/bin/macosx/contrib/4.1/radiant_1.4.0.tgz'
Content type 'application/octet-stream' length 2547880 bytes (2.4 MB)
==================================================
downloaded 2.4 MB

The downloaded binary packages are in
	/var/folders/p4/47w6xt5d3z56ck49dbsnb_n80000gn/T//Rtmp9t6gn7/downloaded_packages
> 

How to proceed? Thanks a lot in advance!

**Comment by vnijs** [comment]
I don't see any errors. See the video below on Starting and Stopping Radiant. You can also run `radiant:::radiant()` in the Rstudio console.

https://youtu.be/rNPnnqJhmD4

All documentation for Radiant is here: https://radiant-rstats.github.io/docs/index.html
