### ISSUE TITLE
R won't install on Mac

### ISSUE THREAD

**Issue by akifranklin1** [radiant-rstats/radiant#164]
I have been able to download R and RStudio, but am unable to open radiant in the Addins section (it is grayed out). I get to the point of entering: "source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/install.R")" into R and I receive the below error:

   package ‘gitgadget’ is available as a source package but not as a binary

Skipping install of 'radiant.update' from a github remote, the SHA1 (b90bdd56) has not changed since last install.
  Use `force = TRUE` to force installation
trying URL 'https://download1.rstudio.org/desktop/macos/RStudio-1.4.1717.dmg'
Content type 'application/x-apple-diskimage' length 203061938 bytes (193.7 MB)
==========
downloaded 41.5 MB

Error in download.file(URL, "Rstudio.dmg") : 
  download from 'https://download1.rstudio.org/desktop/macos/RStudio-1.4.1717.dmg' failed
In addition: Warning messages:
1: package ‘gitgadget’ is not available as a binary package for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: In download.file(URL, "Rstudio.dmg") :
  downloaded length 43487814 != reported length 203061938
3: In download.file(URL, "Rstudio.dmg") :
  URL 'https://download1.rstudio.org/desktop/macos/RStudio-1.4.1717.dmg': Timeout of 60 seconds was reached

**Comment by vnijs** [comment]
If you already have R and Rstudio then the above messages do not show any issues. Please try  restarting Rstudio to see of now you can start radiant from the Addins menu. Rstudio doesn't always pick up new Addins right awat. If that doesn't work, please copy-and-paste the command below into the console and report back if there are any issues and include screenshots.

`radiant:::radiant()`

**Comment by vnijs** [comment]
No follow up so closing. Reopen as needed.
