### ISSUE TITLE
when I type in the first installment command it says Error

### ISSUE THREAD

**Issue by shijia-chen** [radiant-rstats/radiant#165]
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[R.app GUI 1.77 (7985) x86_64-apple-darwin17.0]

[History restored from /Users/shijiachen/.Rapp.history]

> source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/install.R")
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection to 'https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/install.R'
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  URL 'https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/install.R': status was 'Couldn't connect to server'

**Comment by vnijs** [comment]
Please provide more detail on what exactly you are doing before this error shows up. Are you following the installation steps as described on the page linked below?

```
https://radiant-rstats.github.io/docs/install.html
```

**Comment by vnijs** [comment]
No follow up so closing. Reopen as needed.
