### ISSUE TITLE
error ; report was not evaluated

### ISSUE THREAD

**Issue by a2akakao** [radiant-rstats/radiant#166]
Hello! I have an error as you can see in the picture. How can I fix it?? Did I set something wrong??
![radiant error](https://user-images.githubusercontent.com/62986907/136682243-f551f0f6-a745-456e-bea8-44b55cfcc868.jpg)
?

**Comment by vnijs** [comment]
This is not error. Rather, it is a built-in feature to limit the risk that malicious users can run R code in a unprotected environment. You need to add the below to the `.Rprofile` file on your system. See the page below for more information about options you can set Radiant.  

`options(radiant.report = TRUE)`

https://radiant-rstats.github.io/docs/data/report_rmd.html

You will need to restart Radiant before it will pickup the changes in `.Rprofile`. Feel free to reopen the issue if you have difficulty get the reporting feature to run.

On a related note, I recommend running Radiant from the Addins menu in Rstudio (server) if available.
