### ISSUE TITLE
Error Message After Source Code Entered

### ISSUE THREAD

**Issue by chelasaur** [radiant-rstats/radiant#167]
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
2GHz Quad-Core Intel core i5

Link used to download R:
https://cran.r-project.org/bin/macosx/

Error message below after I had input the code:

> 
> source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/install.R")
Error in ifelse(os == "Linux", repos[1], repos[3]) : 
  object 'repos' not found
> 
>

**Comment by vnijs** [comment]
Thanks for reporting! Can you try again now?

```
source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/install.R")
```

**Comment by chelasaur** [comment]
Looks like it is working now. I will circle back if there are any additional issues.

**Comment by vnijs** [comment]
Thanks again for reporting @chelasaur
