### ISSUE TITLE
Data > Visualize > Boxplot 

### ISSUE THREAD

**Issue by dshchew** [radiant-rstats/radiant#169]
I wonder if it might be possible to implement the plotting of boxplots without requiring specifying a "X-variable" as a factor?

In ggplot, it is possible to do both 
[1] `ggplot(diamonds, aes(y=price)) + geom_boxplot()`
and 
[2] `ggplot(diamonds, aes(x=cut, y=price)) + geom_boxplot()`

It will be great if [1] can be done in Radiant.

Perhaps it can be done with a " " or "None" option in the "X-variable" list?
That will be similar to 
`ggplot(diamonds, aes(y=price, x="")) + geom_boxplot()`

By the way, I think Radiant is a great app!

**Comment by vnijs** [comment]
Something like this? Install the github version of `radiant.data` and try it out. I'm waiting for an update to `shinyFiles` and then plan to push this version to CRAN. 

```
install.packages(c("remote", "shiny"))
remotes::install_github("radiant-rstats/radiant.data", update = "never")
```

![image](https://user-images.githubusercontent.com/2998956/140678839-08d036a4-b685-4a47-9978-14ec85e80801.png)

**Comment by dshchew** [comment]
Hi Vincent, 
Yes, that worked. Thanks so much!

**Comment by vnijs** [comment]
Thanks for confirming @dshchew. Hope to have the update on CRAN soon.
