### ISSUE TITLE
Transform

### ISSUE THREAD

**Issue by ugartelon** [radiant-rstats/radiant#17]
I would like to strip the dollar signs and extra white spaces from a dataset I clipboard.
http://online.wsj.com/public/resources/documents/info-Salaries_for_Colleges_by_Region-sort.html

Is this possible in Radiant?

Thanks

**Comment by vnijs** [comment]
Sure. In _Data > Transform_ select `Create` from the `Transformation type` drop-down and use something like:

```r
Starting.Median.Salary = sub("\\$","",Starting.Median.Salary) %>% sub(",","",.) %>% as.numeric
```

Press enter to see the preview and then the Store button to store the change

Data in Radiant is stored in `r_data` so in _R > Code_ you could also run:

```r
r_data[["copy_and_paste"]] <- mutate_all(r_data[["copy_and_paste"]], funs(sub("\\$","",sub(",","",.))))
```

To convert to number use _Data > Transform_, select  `Change type`, select the variables you want to change, and then click the Store button
