### ISSUE TITLE
Load radiant.data from local Github clone

### ISSUE THREAD

**Issue by ColinConwell** [radiant-rstats/radiant#171]
I've been modifying radiant.data a bit in a git clone of the radiant.data repo, and now am looking to interface it with a modified clone of the overarching radiant repo. 

I figured this would be done by changing the 'radiant.path.data' option in global.R to point to the radiant.data clone on my local machine, but this doesn't seem to load the modified copy.

Is there another option I need to set somewhere to force radiant to load from my local copy? Something with radiant.development, perhaps?

**Comment by vnijs** [comment]
If you set `radiant.development` to TRUE and you start the app using a ui.R file it should load from source. This is much easier and faster compared to rebuilding. If that doesn't work for some reason, just rebuild the packages and start with `radiant:::radiant()`

**Comment by ColinConwell** [comment]
Thanks as always for the rapid response. The way I've been developing and modifying is by running devtools::load_all(), then shiny::runApp() from inside the /inst/app folder. I've now hit an odd error where it seems like certain aspects of my modified code are loading, but others are not. (For example, changes I made to visualize_ui.R are rendering, but changes made to visualize.R are not). When you say start the app using a ui.R file, is the shiny::runApp() command what you mean or is there some other function that's superior?

**Comment by vnijs** [comment]
In Rstudio open ui.R and click the Play button. Same things as what you are doing though

**Comment by vnijs** [comment]
@ColinConwell I assume you have seen https://shiny.rstudio.com/py/ Might be a good fit for you. Looks amazing!
