### ISSUE TITLE
Radiant installation takes very long (Ubuntu)

### ISSUE THREAD

**Issue by joulev** [radiant-rstats/radiant#173]
I am trying to install R, Rstudio and Radiant. So far I have been trying the commands mentioned in [Installation guide](https://radiant-rstats.github.io/docs/install.html) (literally copy-pasting).

All went well, until this part,

> Run the following command to install the required R-packages for a user:
>
> ```sh
> R -e "source('https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R')"
> ```
>
> To make R-packages available to all users on a linux system run the command below instead:
>
> ```sh
> sudo su -c "R -e \"source('https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R')\""
> ```

Each of these commands takes a long amount of time. By long, I mean *loooooooooong*.

What worries me even more is that it doesn't seem to be a network issue. Take a section of the log, for example

```
trying URL 'https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/AdjBQR_1.0.tar.gz'
Content type 'binary/octet-stream' length 25957 bytes (25 KB)
==================================================
downloaded 25 KB

* installing *binary* package ‘AdjBQR’ ...
* DONE (AdjBQR)

The downloaded source packages are in
        ‘/tmp/Rtmp0Ci6bJ/downloaded_packages’
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
```

The tar archive file was downloaded pretty quickly (of course, since it's just 25KB). However, the "Installing package to `/usr/local/lib/R/site-library`" takes really long. And I don't think it's a problem with my computer, since I can install other softwares just fine (for example I could download *and* install the whole of TeX Live (~7GB) in only about an hour).

So I wonder if there is something wrong with the install scripts that's slowing the process of moving downloaded files to the library directory.

**Comment by vnijs** [comment]
That is odd. Can you try the below?

```
options(HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(), paste(getRversion(), R.version$platform, R.version$arch, R.version$os)))
options(repos = c(RSPM = "https://packagemanager.rstudio.com/all/__linux__/focal/latest"))
install.packages("radiant")
```

**Comment by joulev** [comment]
> ```
> options(HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(), paste(getRversion(), R.version$platform, R.version$arch, R.version$os)))
> options(repos = c(RSPM = "https://packagemanager.rstudio.com/all/__linux__/focal/latest"))
> install.packages("radiant")
> ```

Oh, this one was really fast (only ~10mins). Thank you!

Then probably something's wrong with this

```
sudo su -c "R -e \"source('https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R')\""
```

I think I will keep this issue open for now, but feel free to close it.

**Comment by vnijs** [comment]
Closing for now. Please re-open as needed.
