### ISSUE TITLE
Datasets in Global Environment in RStudio, but not listed among datasets Radiant app

### ISSUE THREAD

**Issue by nilskvilvang** [radiant-rstats/radiant#175]
Hi. When trying to follow along the tutorial (048) it works well until I open Radiant. Then the example dataset (walmart_sales_weekly) does not show in the drop-down menu for the datasets, but it is present in RStudio in the Global Environment. I followed the setup tutorial - created new project and set-up the github connection as shown in the tutorial. What could be the cause(s) of the dataset not showing in Radiant browser when present in the Global Environment?

**Comment by nilskvilvang** [comment]
Nevermind, my mistake (of course). Just a matter of defining "Load data of type:"

**Comment by vnijs** [comment]
I was about to say what you found out :) Thanks for using Radiant
