### ISSUE TITLE
Time series analysis

### ISSUE THREAD

**Issue by VitoFanelli** [radiant-rstats/radiant#176]
Hi, I sugget to add a section to time series analysis (trend, seasonality, autocorrelation,...), modelling (arima, nn, ecc.) and forecasting.
It would be greatful.

Congratulations for this beautiful app.

Vito

**Comment by vnijs** [comment]
Thanks. I started on this a while back but didn't get very far. Not likely to be added in the near future ... unless there is a pull request :)
