### ISSUE TITLE
problem with html export from rmd report in .bat mode

### ISSUE THREAD

**Issue by VitoFanelli** [radiant-rstats/radiant#177]
Hi, I've created a .bat file with with win_launcher() to launch radiant directly from desktop.
When I click save report in html, after knitr, the app crashes and I get this error

Avvertimento in file(file, "rb"):
  non è possibile aprire il file 'www/htmlwidgets.js': No such file or directory
Avvertimento: Error in file: non è possibile aprire la connessione
  1: shiny::runApp

It doesn't find 'www/htmlwidgets.js' file.

From RStudio, it works.

**Comment by vnijs** [comment]
I recommend you start Radiant from Rstudio. If you cannot do that then either (1) install pandoc or (2) find where Rstudio has Pandoc set up (`Sys.getenv("RSTUDIO_PANDOC")`) and then add something like the below to your launch script.

```
Sys.setenv(RSTUDIO_PANDOC='C:/Program Files/RStudio/bin/pandoc');
```

**Comment by vnijs** [comment]
I updated the code for the .bat files. Please try the development version. New versions of the different sub-packages are on CRAN or will be submitted today.
