### ISSUE TITLE
Do not see Random Forests or Gradient Boosted Trees after installing Radiant

### ISSUE THREAD

**Issue by eachoe** [radiant-rstats/radiant#178]
Hello,

After installing Radiant on my mac, I noticed Random Forests and Gradient Boosted Trees are missing vs the version online.  Is there any way I can get it on my local version?

![Screen Shot 2022-02-25 at 11 15 47 AM](https://user-images.githubusercontent.com/3403036/155758377-4771c8fe-88ec-4d72-857f-d2ab86f81d22.png)

Secondly, I really appreciate Radiant and think its great.

Thanks!

**Comment by vnijs** [comment]
Using an old version or R perhaps? The current version of R is 4.1.2 and should have full access to the latest version of Radiant

**Comment by eachoe** [comment]
Yes that worked.  Thank you!
