### ISSUE TITLE
Parameter tuning using grid search

### ISSUE THREAD

**Issue by mileta1976** [radiant-rstats/radiant#18]
Dear Dr. Vincent,

Do you have any plans regarding parameter tuning using grid search ?

Best regards

**Comment by vnijs** [comment]
I do. Either using the caret package or some custom code. Hope to have some time to work on that in summer/fall

**Comment by vnijs** [comment]
See documentation at the links below

http://radiant-rstats.github.io/radiant.model/reference/cv.nn.html
http://radiant-rstats.github.io/radiant.model/reference/cv.crtree.html
