### ISSUE TITLE
Problem with build_win.R in radiant-master

### ISSUE THREAD

**Issue by jaimemoreirar** [radiant-rstats/radiant#180]
Hello I hope you are well. I have a problem, I am studying the source code of the Radiant package, but when compiling said code through the build_win.R file (Run the file in RStudio) I get a series of errors that do not allow the process to be completed.

As an additional fact, I have Shiny installed.

I hope you can help me, greetings
![capture1](https://user-images.githubusercontent.com/55266728/159482797-fad806de-19d6-4fba-ab07-85e912927019.png)
![capture2](https://user-images.githubusercontent.com/55266728/159482807-b0a13a05-802f-4254-9cd7-6d8087310685.png)
.

**Comment by vnijs** [comment]
I haven't used that code in quite some time. It is just setup for my local system and other packages that I maintain (e.g., shinyAce). If all you want to do is install from source that you cloned locally just use the 'build' option in Rstudio

![image](https://user-images.githubusercontent.com/2998956/160321113-f612f56e-4253-4803-a5db-934f74cec9dd.png)

**Comment by vnijs** [comment]
Closing. Open again as needed.
