### ISSUE TITLE
Question: Filter slider on radiant > View

### ISSUE THREAD

**Issue by yogat3ch** [radiant-rstats/radiant#181]
Greetings @vnijs,
We're in awe of the functionality packed into radiant and have been wondering where some of it came from. This is the first time I've seen the pop-up sliders on continuous data filter fields, seen in the screenshot below on the Radiant > View tab:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/32208821/162819646-fa45d65f-6bb7-42f6-8b40-d87c01848f9d.png">

I haven't been able to find this functionality documented in  the [datatable](https://datatables.net/manual/) manual. Is this some obscure feature? A table plug-in? Or is this something you added with custom javascript?

Thanks for your time,
Stephen

**Comment by vnijs** [comment]
Thanks for the kind comment @yogat3ch. Everything in the Data > View tab in Radiant comes from the DT package.

https://rstudio.github.io/DT/

The `view_data` function linked below show the setup you could use outside of Radiant.

https://github.com/radiant-rstats/radiant.data/blob/master/R/view.R#L192-L254

**Comment by yogat3ch** [comment]
Most awesome, thank you @vnijs! I don't know how I've been using `DT` for so long and never observed this functionality! Much appreciated
