### ISSUE TITLE
Broken url

### ISSUE THREAD

**Issue by dshchew** [radiant-rstats/radiant#182]
I was trying to download the all-in-one windows installer from https://radiant-rstats.github.io/docs/install.html, 
and found that the following link is broken:

https://rady.ucsd.edu/faculty/directory/vnijs/Rady-Radiant-Installer-Latest.exe

Thanks.

**Comment by vnijs** [comment]
Sorry for the late response. You can use the link below to get the installer:
 
https://www.dropbox.com/s/oy1x4cdxegs4bau/Rady-Radiant-Installer-Latest.exe?dl=1

**Comment by dshchew** [comment]
Thanks a lot!
