### ISSUE TITLE
Different menu than the shown in tutorials

### ISSUE THREAD

**Issue by RC3656** [radiant-rstats/radiant#184]
I started using Radiant in my RStudio version 4.1.3 under Mac. At the first step in tutorials, I saw that my Menu is different that those in tutorials: in mine there is no option under Decision Trees then, should I reinstall it,? Is this a problem with my RStudio?
Thanks for your comments
Regard
<img width="322" alt="Captura de Pantalla 2022-08-21 a las 17 01 09" src="https://user-images.githubusercontent.com/101126492/185797617-d3c77fdf-bae8-490c-b5f1-5c87fbb30e55.png">
s

**Comment by vnijs** [comment]
@RC3656 Thanks for reporting. It looks like the menu is cut off. You will need to zoom out a bit in the browser so the full dropdown menu is shown 

In the next release of radiant, I have now added CSS styling that will allow you to scroll in long dropdown menus. If you want to try it out, use the code below.

```
install.packages("remotes")
remotes::install_github("radiant-rstats/radiant.data", upgrade = "never")
```

**Comment by RC3656** [comment]
Thanks for your reply and sorry for bothering with this minor problem. I implemented your recommendation and now is Ok. Thanks again.
Regards

**Comment by vnijs** [comment]
@RC3656 This is a great ticket/issue actually. I develop and test on a large monitor. I assume you were using this on smaller a laptop screen. I am glad that you pointed out this issue and that it had an easy fix.
