### ISSUE TITLE
Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by kshipskie** [radiant-rstats/radiant#185]
I get the following message with trying to download R according to the instructions on https://radiant-rstats.github.io/docs/install.html. I'm on MacOS Mojave

Skipping install of 'radiant.update' from a github remote, the SHA1 (b90bdd56) has not changed since last install.
  Use `force = TRUE` to force installation
Error in file(con, "r") : 
  cannot open the connection to 'https://www.rstudio.com/products/rstudio/download'
In addition: Warning message:
In file(con, "r") :
  URL 'https://www.rstudio.com/products/rstudio/download': status was 'Peer certificate cannot be authenticated with given CA certificates'

Any suggestions?

**Comment by vnijs** [comment]
That is very odd. Can you tell me what you get when you run the lines of code below in R? 

```
page <- readLines("https://www.rstudio.com/products/rstudio/download", warn = FALSE)
pat <- "//download1.rstudio.org/desktop/macos/RStudio-[0-9.]+.[0-9.]+.[0-9]+.dmg";
URL <- paste0("https:",regmatches(page, regexpr(pat, page))[1])
URL
```

It should return:

`[1] "https://download1.rstudio.org/desktop/macos/RStudio-2022.07.1-554.dmg"`

Can I asked what country you are in? Is it possible that any firewall or network settings might be blocking access to the link below?

https://www.rstudio.com/products/rstudio/download

**Comment by vnijs** [comment]
Reopen as needed if you have more information.
