### ISSUE TITLE
My Radiant does not recognise figures <0

### ISSUE THREAD

**Issue by RC3656** [radiant-rstats/radiant#187]
Hello. Trying to going on with the tutorial of this extraordinary package, I found a trouble and I was not able to solve it. I re-started by new installations of R, RStudios & Radiant on my Mac and the result is the same. I load the input in the tutorial (\solutions\video2.state.rda) but the behaviour is the same. 

I tried with a fresh installation of R / RStudio /Radiant in a Windows computer, load the file in the example but I have no way to include a payoff < 0. In the model in the Screen shot attached can be seen that, no matter that the definition is "payoff: -1000000",
always the calculation assumes that the the 0.4 n ode "fracaso" hay payoff for +1000000.

Is there a way to specify negative numbers? 
I would appreciate your comments and suggestions
Thanks agains
Regards
RC Orellana
<img width="1207" alt="Captura de Pantalla 2022-08-24 a las 17 20 19" src="https://user-images.githubusercontent.com/101126492/186459889-d773fbde-9143-4e1e-8d59-143a744c9787.png">

**Comment by vnijs** [comment]
You found a bug @RC3656. Thanks for reporting. An update is on its way to CRAN but you can get the updated version by running the command below.

```
remotes::install_github("radiant-rstats/radiant.model", upgrade="never")
```
