### ISSUE TITLE
macOS Mojave Unable to access index for repository 

### ISSUE THREAD

**Issue by Radiantguru33** [radiant-rstats/radiant#188]
Hi everyone!
I am having difficulties downloading radiant due to the error shown below, if you guys have any advice, I would greatly appreciate it!

Thank you, 

Warning: unable to access index for repository https://rsm-compute-01.ucsd.edu:4242/rsm-msba/__linux__/focal/latest/bin/macosx/contrib/4.2:
  cannot open URL 'https://rsm-compute-01.ucsd.edu:4242/rsm-msba/__linux__/focal/latest/bin/macosx/contrib/4.2/PACKAGES'
trying URL 'https://radiant-rstats.github.io/minicran/bin/macosx/contrib/4.2/MASS_7.3-58.1.tgz'
Content type 'application/octet-stream' length 1167421 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

trying URL 'https://radiant-rstats.github.io/minicran/bin/macosx/contrib/4.2/nlme_3.1-159.tgz'
Content type 'application/octet-stream' length 2399889 bytes (2.3 MB)

**Comment by vnijs** [comment]
This is just a warning and since packages are being downloaded you should be fine.

**Comment by Radiantguru33** [comment]
Thank you for your reply Vnijs,

This is all the errors i get when adding the source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/install.R") and it does not continue to update. Only other error is shown below. Please assist on how I should proceed. 

Skipping install of 'radiant.update' from a github remote, the SHA1 (b90bdd56) has not changed since last install.
  Use `force = TRUE` to force installation
Error in file(con, "r") : 
  cannot open the connection to 'https://www.rstudio.com/products/rstudio/download'
In addition: Warning message:
In file(con, "r") :
  URL 'https://www.rstudio.com/products/rstudio/download': status was 'Peer certificate cannot be authenticated with given CA certificates'

**Comment by vnijs** [comment]
That is very odd. Can you tell me what you get when you run the lines of code below in R?

page <- readLines("https://www.rstudio.com/products/rstudio/download", warn = FALSE)
pat <- "//download1.rstudio.org/desktop/macos/RStudio-[0-9.]+.[0-9.]+.[0-9]+.dmg";
URL <- paste0("https:",regmatches(page, regexpr(pat, page))[1])
URL
It should return:

[1] "https://download1.rstudio.org/desktop/macos/RStudio-2022.07.1-554.dmg"

Can I asked what country you are in? Is it possible that any firewall or network settings might be blocking access to the link below?

https://www.rstudio.com/products/rstudio/download

Finally, what do yo get when you run the below?

```
radiant.update::radiant.update()
```

**Comment by Radiantguru33** [comment]
> radiant.update::radiant.update()
trying URL 'https://radiant-rstats.github.io/minicran/bin/macosx/contrib/4.2/lobstr_1.1.2.tgz'
Content type 'application/octet-stream' length 331872 bytes (324 KB)
==================================================
downloaded 324 KB

trying URL 'https://radiant-rstats.github.io/minicran/bin/macosx/contrib/4.2/packrat_0.8.1.tgz'
Content type 'application/octet-stream' length 682634 bytes (666 KB)
==================================================
downloaded 666 KB

trying URL 'https://radiant-rstats.github.io/minicran/bin/macosx/contrib/4.2/quarto_1.2.tgz'
Content type 'application/octet-stream' length 68484 bytes (66 KB)
==================================================
downloaded 66 KB

trying URL 'https://radiant-rstats.github.io/minicran/bin/macosx/contrib/4.2/rsconnect_0.8.27.tgz'
Content type 'application/octet-stream' length 680835 bytes (664 KB)
==================================================
downloaded 664 KB


The downloaded binary packages are in
	/var/folders/wz/swg2l4917yz2f302xym2qrs40000gn/T//RtmpREEDy8/downloaded_packages

Testing if Radiant can be loaded ...

Radiant update was successful

**Comment by Radiantguru33** [comment]
1. First upload you asked to see
2. I am in the United States, my firewall is off for downloads, and I have checked that

> page <- readLines("https://www.rstudio.com/products/rstudio/download", warn = FALSE)
Error in file(con, "r") : 
  cannot open the connection to 'https://www.rstudio.com/products/rstudio/download'
In addition: Warning message:
In file(con, "r") :
  URL 'https://www.rstudio.com/products/rstudio/download': status was 'Peer certificate cannot be authenticated with given CA certificates'
> pat <- "//download1.rstudio.org/desktop/macos/RStudio-[0-9.]+.[0-9.]+.[0-9]+.dmg";
> URL <- paste0("https:",regmatches(page, regexpr(pat, page))[1])
Error in as.character(text) : 
  cannot coerce type 'closure' to vector of type 'character'
> URL
Error: object 'URL' not found

**Comment by vnijs** [comment]
The good news is that from your previous post it looks like Radiant is installed and ready to use. Try the code below from an R-console to see Radiant start in your default browser.

```
radiant::radiant()
```

I can't tell what is going on with your setup. As you can see from the code + output this should all work fine.

```
> page <- readLines("https://www.rstudio.com/products/rstudio/download", warn = FALSE)
> pat <- "//download1.rstudio.org/desktop/macos/RStudio-[0-9.]+.[0-9.]+.[0-9]+.dmg";
> URL <- paste0("https:",regmatches(page, regexpr(pat, page))[1])
> URL
[1] "https://download1.rstudio.org/desktop/macos/RStudio-2022.07.1-554.dmg"
```

**Comment by vnijs** [comment]
Reopen as needed if you have more information.
