### ISSUE TITLE
Classification Tree Plot (Weird)

### ISSUE THREAD

**Issue by nmullapudi** [radiant-rstats/radiant#189]
Hi,

I'm naga (ex Rady school student). I use Radiant in my office to make my life easy when building the models. I'm currently working on Sales Data and tried to built a classification tree model. I built a classification tree model with Max Nodes 19 (suggested by prune) and tried to plot the classification tree. But the plot looks weird (like attached). 
Clearly it doesn't look like a regular tree with green boxes. Is this a known error? How do I fix it? Can you please help. 

![Tree Figure](https://user-images.githubusercontent.com/85891988/195182946-2a1c21cc-e37b-4bcc-b885-f2b33ab1454c.JPG)

**Comment by vnijs** [comment]
Hi Naga,

The decision tree module seems to be working fine. Can you try updating to the latest version of all radiant packages? Also, what version of R are you using? The latest version is 4.2.1.

Install.packages(“radiant”)

Best,

Vincent

***@***.***

From: nmullapudi ***@***.***>
Date: Tuesday, October 11, 2022 at 12:40 PM
To: radiant-rstats/radiant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [radiant-rstats/radiant] Classification Tree Plot (Weird) (Issue #189)

Hi,

I'm naga (ex Rady school student). I use Radiant in my office to make my life easy when building the models. I'm currently working on Sales Data and tried to built a classification tree model. I built a classification tree model with Max Nodes 19 (suggested by prune) and tried to plot the classification tree. But the plot looks weird (like attached).
Clearly it doesn't look like a regular tree with green boxes. Is this a known error? How do I fix it? Can you please help.

[Tree Figure]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/85891988/195182946-2a1c21cc-e37b-4bcc-b885-f2b33ab1454c.JPG__;!!Mih3wA!Bwh1ndgJLxjvgVPfqPVsRtTcBrE8Wjg952TBgLQ5YuU6yNTdpAFbbXKCWZAsJ_TzCATPb2IOE-SRMpaGAkHM4GU$>

**Comment by nmullapudi** [comment]
Professor,

I did make sure the versions are up to date when I saw the error. The error doesn’t show up all the time, and it is difficult (or recreate) to guess when it will show up. It is working fine since yesterday. But may come again. I will get back to you if I see the error again. For now, I’m able to get my job done. Thank you for the quick response.

Naga Mullapudi​​ | Senior Statistical Analyst | Info-Tech Research Group | 888 Yonge Street | Toronto, ON | M4W 2J2
O: +1 (888) 670-8889 x3363 | infotech<https://www.infotech.com/>.<https://www.infotech.com/>com<https://www.infotech.com/>
***@***.***
***@***.***<https://go.infotech.com/info-tech-linkedin>
***@***.***<https://go.infotech.com/info-tech-twitter>
***@***.***

**Comment by vnijs** [comment]
Thanks for the update Naga. I'll close the issue for now but feel free to reopen as needed.
