### ISSUE TITLE
installation issues with minicran

### ISSUE THREAD

**Issue by GeraldCNelson** [radiant-rstats/radiant#19]
When I run
install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/") in rstudio, I quickly get the follow error
Warning in install.packages :
  URL 'https://radiant-rstats.github.io/minicran/src/contrib/radiant.model_0.8.1.tar.gz': status was '404 Not Found'

When I install from cran, after trying the above, 00LOCK-radiant needs to be deleted, but then the installation works.

**Comment by vnijs** [comment]
Thanks for reporting. Should be updated now.
