### ISSUE TITLE
Allowing for the selection of the prediction interval type

### ISSUE THREAD

**Issue by NopeSiniscalco** [radiant-rstats/radiant#191]
Hi,
In the linear regression prediction tab I added a drop-down to choose between the confidence and prediction intervals and thought it might be worth adding (My uni stats classmates would definitely appreciate it), though it might be too much clutter for the gui?

Here are the changes I implemented in radiant.model's regress_ui.R, though my implementation was solely for the purposes of my class and extremely basic :stuck_out_tongue: 

First edit:
```
reg_predict_interval <- c(
  "Confidence" = "confidence",
  "Prediction" = "prediction"
)
```

Second edit:
```
## setting value for prediction interval type
  if (input$reg_predict_interval == "confidence") {
  	reg_pred_args$interval <- "confidence"
  } else {
  	reg_pred_args$interval <- "prediction"
  }
 reg_pred_args
```

Third edit:
```
selectInput(
          "reg_predict_interval",
          label = "Prediction interval type:", reg_predict_interval,
          selected = state_single("reg_predict_interval", reg_predict_interval, "confidence")
        ),
```

**Comment by vnijs** [comment]
Thanks for the suggestion. I'd rather not change the already pretty complex interface tbh. A relatively easy approach to address your preference would be to add the `interval = "prediction"` argument in code generated for `Report > Rmd`. 

```
pred <- predict(result, pred_data = diamonds, interval = "prediction")
```
