### ISSUE TITLE
porblem: radiant warning: error in do.call: 'what' must be a function or character string

### ISSUE THREAD

**Issue by kewyang** [radiant-rstats/radiant#192]
Hi, there
i got a problem when runing a linear regression, i dont know why, please help me to salve it. 
many thanks.

![image](https://user-images.githubusercontent.com/66128761/207227602-6ffa6f1c-3cd0-44d6-a400-34113a4520ab.png)

**Comment by vnijs** [comment]
Strange. I can't reproduce the problem (see below). If you are running Radiant from Rstudio, are there any other messages in the console?

![image](https://user-images.githubusercontent.com/2998956/208182434-66cfda9a-ada9-420a-b4e2-dd4f10666306.png)

**Comment by vnijs** [comment]
Without more information I can't help out here. Please feel free to reopen as needed if you have more information to share.
