### ISSUE TITLE
Saving state files causes crashes without a writable home directory; problem is something interacting with the file system

### ISSUE THREAD

**Issue by robertwwalker** [radiant-rstats/radiant#196]
Thank you again and as always for a wonderful tool.  I think the issue is where the working directory is set, or perhaps not having one set at all.

This is the warning message and, when attempting to save files, it crashes.  

If one sets a working directory so that it is not the root of the file structure, the warning persists but the crash behavior can be avoided.

```
> radiant:::radiant()

Starting radiant in the default browser

Radiant is opensource and free to use. If you are a student or instructor using Radiant for a class, as a favor to the developer, please send an email to <radiant@rady.ucsd.edu> with the name of the school and class

Listening on http://127.0.0.1:3660
Warning in file(con, "r") :
  file("") only supports open = "w+" and open = "w+b": using the former
```

**Comment by vnijs** [comment]
I did notice the warning message a while ago but then after working on some other things in Radiant and updating some R-packages it disappeared before I had a chance to look into it. Can you try updating using the code below and checking if the issue still occurs? Thanks

```{r}
remotes::install_github("radiant-rstats/radiant.update")
radiant.update::radiant.update()
```

**Comment by robertwwalker** [comment]
That seems to have gotten it; thank you very much!  I think I also get the warning on my workstation so I will check in on that but my M1 mac laptop is now behaving swimmingly with this.
