### ISSUE TITLE
My Radiant is Gray

### ISSUE THREAD

**Issue by GGGGLORIA12138** [radiant-rstats/radiant#199]
**I running the Radiant through RStudio ->Addins -> Start Radiant (browser) 
But the website is gray and I cannot read any data or analyze anything. I attached a screen shot:** 
![radiant](https://user-images.githubusercontent.com/126451559/221504690-a23c57fa-92f0-437d-850e-cd5c76c74052.PNG)

**I tried to restart my computer & RStudio, reinstall the R, RStudio, Radiant, and delete my original dataset, but not working.
Meanwhile, my RStudio console looks like this:**

> radiant:::radiant()

Starting radiant in the default browser

Radiant is opensource and free to use. If you are a student or instructor using Radiant for a class, as a favor to the developer, please send an email to <radiant@rady.ucsd.edu> with the name of the school and class

Listening on http://127.0.0.1:4549
Warning: Error in %>%: attempt to set an attribute on NULL
  86: %>%
  85: <reactive:varnames> [C:/Users/GloriaTu/AppData/Local/R/win-library/4.2/radiant.data/app/radiant.R#236]
  69: varnames
  67: <reactive:transform_auto_complete> [C:/Users/GloriaTu/AppData/Local/R/win-library/4.2/radiant.data/app/tools/data/transform_ui.R#115]
  51: transform_auto_complete
  49: observe [C:/Users/GloriaTu/AppData/Local/R/win-library/4.2/radiant.data/app/tools/data/transform_ui.R#149]
  48: <observer>
   5: shiny::runApp
   2: radiant.data::launch
   1: radiant:::radiant
Warning: Error in if: argument is of length zero
  104: <Anonymous> [C:/Users/GloriaTu/AppData/Local/R/win-library/4.2/radiant.data/app/radiant.R#310]
  103: %>%
  102: show_data_snippet [C:/Users/GloriaTu/AppData/Local/R/win-library/4.2/radiant.data/app/radiant.R#300]
  101: renderText [C:/Users/GloriaTu/AppData/Local/R/win-library/4.2/radiant.data/app/tools/data/manage_ui.R#885]
  100: func
   87: renderFunc
   86: output$man_example
    5: shiny::runApp
    2: radiant.data::launch
    1: radiant:::radiant

**Anyone has had the same problem before who can help me out?**

**Comment by vnijs** [comment]
From the screenshot it looks like radiant is trying to restore a previous state. Can you try running the code below in a terminal and then restarting Rstudio and Radiant?

```
cd; 
rm -rf .radiant.sessions;
cd Documents; 
rm -rf .radiant.sessions
```

**Comment by GGGGLORIA12138** [comment]
> From the screenshot it looks like radiant is trying to restore a previous state. Can you try running the code below in a terminal and then restarting Rstudio and Radiant?
> 
> ```
> cd; 
> rm -rf .radiant.sessions;
> cd Documents; 
> rm -rf .radiant.sessions
> ```

Thank you sooo much! Your answer is very helpful!
