### ISSUE TITLE
ERROR: could not find function "write_csv"

### ISSUE THREAD

**Issue by bjameshunter** [radiant-rstats/radiant#2]
adding library(readr) to radiant/inst/app/global.R fixed this. 

from `sessionInfo()`:
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

**Comment by vnijs** [comment]
Thanks Ben! Just pushed the update.
