### ISSUE TITLE
downloaded images have the same size even we change the  height and width

### ISSUE THREAD

**Issue by kmezhoud** [radiant-rstats/radiant#20]
Dear Dr. Vincent,
If we change the size of the image and want to download image with the new size. 
I noted that the downloaded image has always the same size.
I am using radiant.data 0.8.3
Karim
Thanks

**Comment by vnijs** [comment]
Thanks for spotting this @kmezhoud. I implemented a fix and will push updates in a few days.

**Comment by vnijs** [comment]
Fixed in `radiant.data`. Install the latest version using:

```r
install.packages("radiant.data", repos = "https://radiant-rstats.github.io/minicran/", type = "binary")
```

**Comment by kmezhoud** [comment]
@vnijs ,
Is the fixMS encoding commit only needed  for this issue?

or just 

```r

plot_downloader <- function(plot_name, width = plot_width,
height = plot_height, pre = ".plot_", po = "dl_") {

...
     ## fix for https://github.com/radiant-rstats/radiant/issues/20
        w <- if (any(c("reactiveExpr","function") %in% class(width))) width()*pr else width*pr
        h <- if (any(c("reactiveExpr","function") %in% class(height))) height()*pr else height*pr

        png(file=file, width = w, height = h, res=72*pr)
...
}
```
Thanks

**Comment by vnijs** [comment]
To allow plot-resizing `plot_width` and `plot_height` should be functions passed to `plot_downloader`. You do not need fixMS for that
