### ISSUE TITLE
cant adjust height of shiny apps launched in Report>R or Report>Rmd 

### ISSUE THREAD

**Issue by tvdvinw** [radiant-rstats/radiant#200]
In report>R or report>Rmd if I try to launch a shiny app, for instance: https://shiny.rstudio.com/gallery/tabsets.html
It works. I can style the body to have  a  yellow background. But I cant seem to change the height. With a fluidpage I can scroll but the max height seems to be about 1/4 of the browser page. This is when using radiant in Chrome browser.

**Comment by tvdvinw** [comment]
Fixed. It did work with "options = list(height = 3000)"

**Comment by vnijs** [comment]
Glad you were able to resolve.
