### ISSUE TITLE
German Excel version

### ISSUE THREAD

**Issue by Leo47114711** [radiant-rstats/radiant#202]
Hi, 
Whenever I load a CSV to Radiant, the titles are concenated with underscores like "X1_X2_X3" for example. This results in one attribute while you have 3.
Could you help me to avoid this, please?
Cheers and thank you,
Leo

**Comment by vnijs** [comment]
Your data is likely not "comma separated" but "semicolon separated". You likely need the settings as in the screenshot below

![image](https://github.com/radiant-rstats/radiant/assets/2998956/1d2efbf0-70d9-4d9c-bdbb-3b1f4eb98604)
