### ISSUE TITLE
Trouble installing Radiant

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#206]
I have a new Windows system and the all in one installer doesn't install Radiant.  It installed R & Rstudio.  I opened Rstudio and ran this (also tried in R): 

> source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/install.R")

I get the following error;

Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection to 'https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/install.R'
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  URL 'https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/install.R': status was 'SSL connect error'

My thought is that this is because of my work's security.  However, I'm able to access https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/install.R via a web browser.

Any thoughts on why I can't install?

**Comment by vnijs** [comment]
The script seems to be running fine. If you can access the page, you can copy-and-paste the whole thing into Rstudio.

**Comment by josh1400** [comment]
I get a 404 error for this URL https://radiant-rstats.github.io/minicran/bin/windows/contrib/4.3/  
I'll check with my IT to see if it's a firewall issue.


I can access all the cloud.r-project.org links that are listed in the error below via a browser.  I get the following errors when I copy the code into Rstudio:  

Warning: unable to access index for repository https://radiant-rstats.github.io/minicran/bin/windows/contrib/4.3:
  cannot open URL 'https://radiant-rstats.github.io/minicran/bin/windows/contrib/4.3/PACKAGES'
Warning: unable to access index for repository https://cloud.r-project.org/bin/windows/contrib/4.3:
  cannot open URL 'https://cloud.r-project.org/bin/windows/contrib/4.3/PACKAGES'
Warning in install.packages :
  unable to access index for repository https://radiant-rstats.github.io/minicran/src/contrib:
  cannot open URL 'https://radiant-rstats.github.io/minicran/src/contrib/PACKAGES'
Warning in install.packages :
  unable to access index for repository https://cloud.r-project.org/src/contrib:
  cannot open URL 'https://cloud.r-project.org/src/contrib/PACKAGES'
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Warning in install.packages :
  unable to access index for repository https://radiant-rstats.github.io/minicran/bin/windows/contrib/4.3:
  cannot open URL 'https://radiant-rstats.github.io/minicran/bin/windows/contrib/4.3/PACKAGES'
Warning in install.packages :
  unable to access index for repository https://cloud.r-project.org/bin/windows/contrib/4.3:
  cannot open URL 'https://cloud.r-project.org/bin/windows/contrib/4.3/PACKAGES'
Warning in install.packages :
  packages ‘radiant’, ‘gitgadget’, ‘miniUI’, ‘webshot’, ‘tinytex’, ‘usethis’, ‘svglite’, ‘remotes’ are not available as a binary package for this version of R

Versions of these packages for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
Warning: unable to access index for repository https://radiant-rstats.github.io/minicran/src/contrib:
  cannot open URL 'https://radiant-rstats.github.io/minicran/src/contrib/PACKAGES'
Warning: unable to access index for repository https://cloud.r-project.org/src/contrib:
  cannot open URL 'https://cloud.r-project.org/src/contrib/PACKAGES'
Error in loadNamespace(x) : there is no package called ‘remotes’
Error in loadNamespace(x) : there is no package called ‘radiant.update’

**Comment by vnijs** [comment]
That is expected. There is no html page there and it is not set up to show a list of files. The packages are at the link below but R accesses them through URL you provided

https://github.com/radiant-rstats/minicran/tree/gh-pages/bin/windows/contrib/4.3

Notice that you are also getting message from other repos like cloud.r-project.org

cannot open URL '[https://cloud.r-project.org/bin/windows/contrib/4.3/PACKAGES](https://urldefense.com/v3/__https://cloud.r-project.org/bin/windows/contrib/4.3/PACKAGES__;!!Mih3wA!Bjdlu2w2QE8dQUXGzEajQorTv70qRgXtAfiiPjth-d26JzFED0Wpq5_fr_LhWfdDAX3K4PE9VI_sRaXbMJAjZao$)'

**Comment by josh1400** [comment]
All the other URLs can be accessed via a web browser.  If it's not an access issue, what might it be?

![image](https://github.com/radiant-rstats/radiant/assets/36533710/c1757153-342b-49da-870e-76dabf7cfa6c)

**Comment by josh1400** [comment]
I resolved this issue.  It was an access issue.
