### ISSUE TITLE
Error when using "combine Y-variables in one plot"

### ISSUE THREAD

**Issue by koushr89** [radiant-rstats/radiant#207]
Hello,

I used to be able to combine two y-variables on the same line plot, but now it is giving me an error:
![image](https://github.com/radiant-rstats/radiant/assets/54371813/3146fdc7-b555-47d5-a07a-c6d2b49dd099)

Without choosing the "combine" option, it can produce separate plots. there is no missing values in either variable.
![without y-comb](https://github.com/radiant-rstats/radiant/assets/54371813/72ed7d53-35cc-4232-9a74-89f6a725761a)

Is there a quick fix to this?

**Comment by koushr89** [comment]
For your reference, I am also attaching the data file that I am using: 

[Crime in US.csv](https://github.com/radiant-rstats/radiant/files/12422502/Crime.in.US.csv)

I am using R version 4.3.1, and I just updated Radiant so I should be using the latest version.

**Comment by koushr89** [comment]
A quick update: if I change the type of x-variable (Year) to Character or Factor, it will produce the combined plot (but the x-axis does not look nice). If I use Year as numeric or integer, it will give me the previous error. 

![image](https://github.com/radiant-rstats/radiant/assets/54371813/dbbe8edc-13a0-4e74-8295-ec48c7638f40)

**Comment by vnijs** [comment]
Thanks for reporting! Will be fixed in the next release. If you want to try out the fix, use the below.

```r
install.packages("remotes")
remotes::install_github("radiant-rstats/radiant.data", upgrade="never")
```

**Comment by koushr89** [comment]
Hi again Vincent,

For one of the students in my class, most of the visualization features do not work and produce the following error: 
![MicrosoftTeams-image (1)](https://github.com/radiant-rstats/radiant/assets/54371813/32119e0f-69c5-4123-898b-7cf548d31f20)

We tried the solution you gave in your above comment, but it gave errors: 
![MicrosoftTeams-image](https://github.com/radiant-rstats/radiant/assets/54371813/9ee182a4-7737-4ad8-8f86-9fb904065612)
