### ISSUE TITLE
Radiant archived on CRAN, inaccessible

### ISSUE THREAD

**Issue by mattinbits** [radiant-rstats/radiant#208]
I noticed that radiant is archived on CRAN, due to a dependency on radiant.model which itself was archived due to a dependency on "vip", which was archived. 

It looks like the archiving of "vip" was unintentional, and it is already back up: https://github.com/koalaverse/vip/issues/153

Is it intended that radiant is available on CRAN, and is there some action required to restore it? Thanks.

**Comment by vnijs** [comment]
Sorry for the late reply. Radiant is back up. TBH I don't understand why CRAN doesn't automatically restore packages when they accept a broken dependency.
