### ISSUE TITLE
Unable to locate "Start Radiant " option post installation- Package not found

### ISSUE THREAD

**Issue by gauthameyunni** [radiant-rstats/radiant#209]
[](url)Hello ,

I am using Mac with Intel chip  unable to locate the start radiant option after installing Radiant. Thank you so much for your time on this!

Logs attached: 

> radiant.undate:::radiant.update()

Warning: unable to access index for repository https://radiant-rstats.github.io/minicran/bin/macosx/big-sur-x86_64/contrib/4.3:
cannot open URL 'https://radiant-rstats.github.io/minicran/bin/macosx/big-sur-x86_64/contrib/4.3/PACKAGES
Warning: Unable to access index for repository https://radiant-rstats.github.lo/minicran/bin/macos×/brg-sur-X86_64/contrib/4.3:
cannot open URL httos://radiant-rstats.github.io/minicran/bin/macosx/big-sur-x86_64/contrib/4.3/PACKAGES'
also installing the dependencies 'radiant.model',
'radiant multivariate'
trying URL "https://cloud.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.3/radiant.model_1.5.0.tgz'
Warning in install.packages
cannot open URL "https://cloud.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.3/radiant.model_1.5.0.tgz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb"
....) :
cannot open URL https://cloud.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.3/radiant.model_1.5.0.tgz
Warning in install.packages
download of package 'radiant.model' failed
trying URL 'https://cloud.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.3/radiant.multivariate_1.5.0.tgz'
Warning in install.packages:
cannot open URL "https://cloud.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.3/radiant.multivariate_1.5.0.tgz': HTTP status was '404 Not Found'
Error in download. file(url, destfile, method, mode = "wb",
...) :
cannot open URL https://cloud.r-proiect.orq/bin/macosx/biq-sur-x86_64/contrib/4.3/radiant.multivariate_1.5.0.taz'
Warning in instaLL.packages:
download of package 'radiant multivariate' failed
trying URL 'https://cloud.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.3/radiant_1.5.0.tgz'
Warning in install.packages
cannot open URL "https://cloud.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.3/radiant_1.5.0.tgz': HTTP status was '404 Not Found'
Error in download. file(url, destfile, method, mode = "wb", ...) :
cannot open URL "https://cloud.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.3/radiant_1.5.0.tgz'
Warning in instaLL.packages
download of package 'radiant' failed
Testing it Radiant can be Loaded
Falled with error:
"there is no package called 'radiant'

Radiant update attempt was unsuccessful. Please restart (studio) and run the update (radiant.update: :radiant.update()) or sync (radiant.update: :sync_packages ()) command again. I
update (sync) is still not successful, please send an email to radiant@rady.ucsd. edu with screen shots of the output shown in (studio).

**Comment by vnijs** [comment]
Please try the command below:

`source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/install.R")`
