### ISSUE TITLE
Installation MacOS

### ISSUE THREAD

**Issue by m42smith** [radiant-rstats/radiant#21]
Hi, 
I'm trying to install Radiant on MacOs and get the following error: 

source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/insError in install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  : 
  type 'binary' is not supported on this platform

If I try: install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/")
installation fails as well: 
Warning in install.packages :
  installation of package 'radiant' had non-zero exit status

Any suggestions?
Thanks!

**Comment by vnijs** [comment]
Strange. Binary format is actually supported on Mac. What version of R are you using? Radiant requires R 3.3 or newer.

Can you try the command below again and post a screenshot of R(studio)?

```r
install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/", type = "binary")
```

**Comment by m42smith** [comment]
Hi, 
I'm running R 3.3.2 here is the output of Version: 
> version
               _                           
platform       x86_64-apple-darwin11.4.2   
arch           x86_64                      
os             darwin11.4.2                
system         x86_64, darwin11.4.2        
status                                     
major          3                           
minor          3.2                         
year           2016                        
month          10                          
day            31                          
svn rev        71607                       
language       R                           
version.string R version 3.3.2 (2016-10-31)
nickname       Sincere Pumpkin Patch 


![rstudio](https://user-images.githubusercontent.com/11852165/28341263-2ff949ac-6c13-11e7-82e8-95a39271533b.jpg)

**Comment by vnijs** [comment]
Sorry but I cannot reproduce the problem you are having on Mac. I do notice from the `version` information that you may be using an old version of OSX (see my `version` information below). That said, as far as I know Mac has support binary package for a very long time. Other than upgrading your OS and upgrading R to 3.4.1 the only thing I can think of at the moment is to try the code below.

```r
install.packages("radiant")
radiant::update_radiant()
```

> version
                                 
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          4.1                         
year           2017                        
month          06                          
day            30                          
svn rev        72865                       
language       R                           
version.string R version 3.4.1 (2017-06-30)
nickname       Single Candle

**Comment by m42smith** [comment]
I've found the problem. I was using the Anaconda  R installation and that seems to have been the problem. After removing that and installing R and RStudio separately the binary install of Radiant worked. I'm not sure if it was Anaconda or R3.4 which did the trick but if someone else gets a similar problem these two factors seem to fix it. 

Thank you for your help.  

PS The R version command seems to have trouble reporting the OS version. 
This is what I am running: 
System Version:	macOS 10.12.5
  Kernel Version:	Darwin 16.6.0

Anaconda R reported darwin11. My new R installation reports the following. Closer but still not correct. 

platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          4.1                         
year           2017                        
month          06                          
day            30                          
svn rev        72865                       
language       R                           
version.string R version 3.4.1 (2017-06-30)
nickname       Single Candle

**Comment by vnijs** [comment]
Thanks for the update @m42smith. I wasn't aware that Anaconda supported R. That said, it seems to have some issues if it doesn't support binary packages on Mac. Glad you were able to resolve the problem.
