### ISSUE TITLE
Compare Means/Proportions Sometimes Not Working

### ISSUE THREAD

**Issue by koushr89** [radiant-rstats/radiant#210]
Hi again,

Sometimes, after a few times of working with compare means or compare proportions, after switching to another page and then coming back, the boxes for choosing variables do not appear. If I refresh Radiant then those boxes appear but I don't think that is the best solution. 

![image](https://github.com/radiant-rstats/radiant/assets/54371813/aaa357e8-8e89-40c2-84bc-bea405fd194b)
![image](https://github.com/radiant-rstats/radiant/assets/54371813/8d9a1a50-72f6-4d0b-9308-e2344f3a26b9)

My theory is that whenever in a session I use compare means, compare proportions becomes unavailable and vice versa.

**Comment by koushr89** [comment]
This issue also applies to other functions such as Linear Regression: 

![image](https://github.com/radiant-rstats/radiant/assets/54371813/cdd69c12-ec03-48c0-b779-9fb31666d968)

After refreshing the page the boxes to choose variables appear: 

![image](https://github.com/radiant-rstats/radiant/assets/54371813/2a372a5d-da6e-46e3-89a1-a61c50c7509e)

**Comment by vnijs** [comment]
Thanks for reporting. There haven't been any major changes to the code in Shiny so I suspect the issue might be due to a dependency. Can you try downgrading shiny to version "1.7.4.1" and then check if you still see the issue? If we can repoduce the issue, I can open an issue for Shiny on GitHub.

```r
remotes::install_version("shiny", "1.7.4.1")
packageVersion("shiny")
[1] '1.7.4.1'
```

**Comment by koushr89** [comment]
Thank you. This seems to have resolved the issue. Should I tell my students to run the same command?

**Comment by vnijs** [comment]
Yes. 

I think we are near(er) a solution with the shiny team to things working with 1.7.5 but I want be very sure there are no lurking issues. Thanks again for reporting!

**Comment by vnijs** [comment]
This seems to be a rather complex issue. See discussion here: https://github.com/rstudio/shiny/pull/3904

If you can, I'd suggest using shiny 1.7.4.1. If you are already using Radiant from Rstudio, you can use the "Sync packages" option from the Addins menu to get that version of  shiny.

**Comment by vnijs** [comment]
This is fixed in the latest version of the `shiny` package. If you upgrade to the latest version of `radiant.data`, it will use shiny 1.8.0 or newer.
