### ISSUE TITLE
Install only Radiant

### ISSUE THREAD

**Issue by sasrwt** [radiant-rstats/radiant#212]
I am running 4.3.1.  I don't seem to be able to just install Radiant when running the Rady.... installer.  

Can this been done?

Can I install Radiant with the the required version of R and RStudio using the installer and still maintain my 4.3.1 version?

I am installing on a  Windows 10 machine.
Many of students will be on a mac.  Any considerations for these students for which many already have R installed?  thanks Wayne

**Comment by vnijs** [comment]
From https://radiant-rstats.github.io/docs/install.html use:

`source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/install.R")`
