### ISSUE TITLE
Receiving an error when trying to save report

### ISSUE THREAD

**Issue by k1doyle** [radiant-rstats/radiant#214]
After knitting a report, when I try to save it (have tried HTML and PDF), I receive the following error:

> YAML parse exception at line 5, column 0,
> while scanning for the next token:
> found character that cannot start any token
> Warning: Error in : pandoc document conversion failed with error 64
>   5: shiny::runApp
>   2: radiant.data::launch
>   1: radiant:::radiant

Any help/guidance would be deeply appreciated.

**Comment by vnijs** [comment]
This was an issue with having "---" tokens in the report. Pandoc treats that as the start of a special section and then throws an error when it doesn't find the expected content in that special section.
