### ISSUE TITLE
Cant select multiple explanatory variables for OLS

### ISSUE THREAD

**Issue by lailawinningham** [radiant-rstats/radiant#217]
I am using Radiant for a school project, so I am relatively new to using it. However, I know that I should be able to select multiple variables for my model. When I click on a variable it selects it, but then if I click on another variable it unselects the previous variable I chose. So I am only able to select one variable at a time. I am able to select multiple variables by highlighting them, but this still doesn't allow me to select all of the variables I need without including variables I don't want to use.

![Screenshot (64)](https://github.com/radiant-rstats/radiant/assets/151770633/a97a990f-b767-4643-b6cf-143a8f4cb3ca)

Here's an attached screenshot of my explanatory variables. I want to select everything except for Month {factor}, however, due to this issue I am not able to do so.

**Comment by vnijs** [comment]
Try draggin, shift+click, or ctrl + click. That will get you the variables you want
