### ISSUE TITLE
Installation on Mac

### ISSUE THREAD

**Issue by amy09** [radiant-rstats/radiant#22]
Hi, 
I'm trying to get radiant on my laptop, but there is an error keeps comping up:

Error in webshot::install_phantomjs() : 
  Unable to install PhantomJS to any of these dirs: ~/Library/Application Support/PhantomJS, In addition: Warning messages:
1: In utils::download.file(url, method = method, ...) :
  download had nonzero exit status
2: In utils::unzip(zipfile) : error 1 in extracting from zip file
3: In file.copy(exec, destdir, overwrite = TRUE) :
  problem copying phantomjs-2.1.1-macosx/bin/phantomjs to /Users/xi/Library/Application Support/PhantomJS/phantomjs: No such file or directory

My R is version 3.3.2 and Mac OS is version 10.10.5.
Looking forward to your reply. Thank you.

**Comment by vnijs** [comment]
Radiant tries to install the webshot package as part of the install process. I can't replicate the error you are seeing with webshot on R3.3.3 or R3.4.1. Can you run just the commands below and post a screenshot of all output?

```r
install.packages("webshot")
webshot::install_phantomjs()
```

Depending on the result we can either (1) post in issue on the webshot github page or (2) try to install PhantomJS manually by downloading it from http://phantomjs.org/ and copying the phantomjs file to ~/Library/Application Support/PhantomJS

If you try option 2 use `webshot:::find_phantom()` to see if it can find the installed file. If so, the Radiant install should proceed as intended

**Comment by amy09** [comment]
Thank you for your solutions. I still cannot fix phantomjs issues because of downloading failure, but I get radiant after upgrading Rstudio. So weird.

发自我的 iPhone

在 2017年7月20日，上午12:32，Vincent Nijs <notifications@github.com<mailto:notifications@github.com>> 写道：


Radiant tries to install the webshot package as part of the install process. I can't replicate the error you are seeing with webshot on R3.3.3 or R3.4.1. Can you run just the commands below and post a screenshot of all output?

install.packages("webshot")
webshot::install_phantomjs()

Depending on the result we can either (1) post in issue on the webshot github page or (2) try to install PhantomJS manually by downloading it from http://phantomjs.org/ and copying the phantomjs file to ~/Library/Application Support/PhantomJS

If you try option 2 use webshot:::find_phantom() to see if it can find the installed file. If so, the Radiant install should proceed as intended

**Comment by vnijs** [comment]
Thanks for the update @amy09. I would still recommend that you download phantomjs here: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-macosx.zip

Unzip that file and move phantomjs to ~/Library/Application Support/PhantomJS
