### ISSUE TITLE
iframe shown as HTML tag

### ISSUE THREAD

**Issue by raffaelemancuso** [radiant-rstats/radiant#220]
In the README file, is the iframe supposed to be shown as an HTML tag?

![image](https://github.com/radiant-rstats/radiant/assets/54762742/3150a6cc-427d-409a-aee2-b07da1253d70)

**Comment by vnijs** [comment]
GitHub doesn't support iframes anymore it seems. Unfortunate. Thanks for reporting but it doesn't seem this is fixable.
