### ISSUE TITLE
Radiant won't start--invalid 'nchars' argument

### ISSUE THREAD

**Issue by JLDedrick** [radiant-rstats/radiant#24]
I'm trying to run Radiant within R-Studio. When I start Radiant as an Addin, I get the following

> radiant:::radiant()
Starting Radiant ...

Listening on http://127.0.0.1:6245
Warning in file(con, "rb") :
  file("") only supports open = "w+" and open = "w+b": using the former
Warning: Error in readChar: invalid 'nchars' argument
Stack trace (innermost first):
    2: shiny::runApp
    1: radiant:::radiant
Error : invalid 'nchars' argument

**Comment by vnijs** [comment]
Never seen that error. Please run the command below and then try starting Radiant again:

`radiant::update_radiant()`

Alternatively Radiant can be updated using the command:

`source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/build.R")`

If the error still occurs please report the output from:

`sessionInfo()`

**Comment by JLDedrick** [comment]
Now I’m not seeing Radiant as an Addin (it was there before). Here’s what I see when I try the update command

> radiant::update_radiant()
Error in loadNamespace(name) : there is no package called ‘radiant’

**Comment by vnijs** [comment]
Did you follow my other two suggestions as well @JLDedrick?

Alternatively Radiant can be updated using the command:

`source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/build.R")`

If the error still occurs please report the output from:

`sessionInfo()`

**Comment by JLDedrick** [comment]
Yes, for the second I got

source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/build.R")

It seems you installed R in the Program Files directory.

Please uninstall R and re-install into C:\R\R-3.4.1

R is running fine in its current location. Do I need to uninstall and reinstall to run Radiant?

**Comment by vnijs** [comment]
As a general rule I recommend *not* installing R in the Program Files directory on Windows. If you want to keep R in its current location use the command below: 

`install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/", type = "binary")`

If you are just starting out with R I would recommend you use the all-in-one installer for R, Rstudio, and Radiant linked below:

http://rady.ucsd.edu/faculty/directory/nijs/pub/docs/radiant/Rady-Radiant-Installer-64bit.exe

Before you run the installer you should (1) uninstall your current version of R and (2) remove the Documents/R directory

A tutorial on how to run the installer is linked below:

https://youtu.be/iaB4mTrm2Co

**Comment by JLDedrick** [comment]
I got it. Working fine now. Thanks!

**Comment by vnijs** [comment]
Glad to hear it. Closing issue
