### ISSUE TITLE
menus not showing up

### ISSUE THREAD

**Issue by 49R** [radiant-rstats/radiant#25]
Good evening,

I've uninstalled and re-installed R, RStudio, and Radiant together and separately several times, but I think I must have failed to delete something that's causing me trouble.

When I launch Radiant, all appears well until I move off the Data-Manage tab.  View shows only the top portion of the side menu, screenshot pasted below.  There's nothing else on the page, except the output to file button (which generates a csv with all of the data I can't see or manipulate).  Can you tell me where to look for possible trouble making files? Thank you.

Windows 10, R 3.4.1, RStudio 1.0.153, 
![scrnsht](https://user-images.githubusercontent.com/14957896/29391152-1fa0e4ae-82c3-11e7-8e9b-c39585d59d0c.jpg)

**Comment by vnijs** [comment]
@49R I can't replicate the problem using the same setup (windows 10, R 3.4.1, RStudio 1.0.153). I'll need more information to figure out what is going on with your setup. Are any messages shown in Rstudio? Can you post a screen shot of Rstudio?

Have you tried running `radiant::update_radiant()` to make sure you have the latest version (0.8.7.1) installed?

**Comment by jurbanhost** [comment]
Good evening,
I have this problem to...

>>Have you tried running radiant::update_radiant() to make sure you have the latest version (0.8.7.1) installed?

yes

>>>Are any messages shown in Rstudio?
No any messages

**Comment by jurbanhost** [comment]
This is report from Radiant (Stop & Report from Radiant menu)
[radiant_problem.zip](https://github.com/radiant-rstats/radiant/files/1230695/radiant_problem.zip)

**Comment by vnijs** [comment]
@jurbanhost At the very least the following should be shown in the Rstudio console so lease post everything that is shown in the Rstudio console. Also, please post the output from `sessionInfo()`. 

```r
> radiant:::radiant()
Starting Radiant ...
Loading required package: shiny

Attaching package: ‘plotly’

The following object is masked from ‘package:ggplot2’:

    last_plot

The following object is masked from ‘package:stats’:

    filter

The following object is masked from ‘package:graphics’:

    layout


Listening on http://127.0.0.1:7837
```

**Comment by jimgrasell** [comment]
I am having the same issue. 

Versions: radiant 0.8.7.1, radiant.basics 0.8.7.1, radiant.data 0.8.7.1, radiant.design 0.8.7.1, radiant.model 0.8.7.1, radiant.multivariate 0.8.7.1

Version 1.0.153 – © 2009-2017 RStudio, Inc.

R version 3.4.1 (2017-06-30) -- "Single Candle"

> radiant:::radiant()
Starting Radiant ...

Listening on http://127.0.0.1:6051

> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] bindrcpp_0.2                 plotly_4.7.1                 shiny_1.0.4                  radiant_0.8.7.1              radiant.multivariate_0.8.7.1 radiant.model_0.8.7.1        radiant.basics_0.8.7.1       radiant.design_0.8.7.1      
 [9] mvtnorm_1.0-6                radiant.data_0.8.7.1         lubridate_1.6.0              magrittr_1.5                 tables_0.8                   Hmisc_4.0-3                  Formula_1.2-2                survival_2.41-3             
[17] lattice_0.20-35              readxl_1.0.0                 dplyr_0.7.2                  purrr_0.2.3                  readr_1.1.1                  tidyr_0.6.3                  tibble_1.3.3                 ggplot2_2.2.1               
[25] tidyverse_1.1.1             

loaded via a namespace (and not attached):
Error in x[["Version"]] : subscript out of bounds
In addition: Warning message:
In FUN(X[[i]], ...) :
  DESCRIPTION file of package 'Matrix' is missing or broken

![image](https://user-images.githubusercontent.com/6974648/29426064-6d6c7dd4-8353-11e7-94d4-aafc3937264a.png)

**Comment by jimgrasell** [comment]
Here is a screen capture of the Data-Manage page. The layout has changed from the previous version of Radiant. Could this be related to the problem being discussed in this thread?

![image](https://user-images.githubusercontent.com/6974648/29428274-9bcb45a0-835a-11e7-9d2d-0a50ce3bbec8.png)

**Comment by vnijs** [comment]
It seems this is related to the recent upgrade of the `shiny` package to version `1.0.4`. You can install version `1.0.3` using the command below. Restart R studio and please let me know if this fixed the problem for you as well.

```{r}
install.packages("shiny", repos = "https://radiant-rstats.github.io/minicran/")
```

**Comment by jimgrasell** [comment]
Your solution works!
Thanks.

**Comment by 49R** [comment]
Installed Shiny 1.0.3, and victory!  Thank you very much.

**Comment by jurbanhost** [comment]
Thank you!

**Comment by vnijs** [comment]
FYI Shiny 1.0.5 was just released on CRAN and has a fix for this problem
