### ISSUE TITLE
Cannot install RStudio.

### ISSUE THREAD

**Issue by Pehtonen** [radiant-rstats/radiant#28]
Hi,

I'm a student in KU and in my statistic class our professor wanted us to install RStudio. Everything went well until my Antivirus system (Avast) asked from do I want to give permission to overwrite some document, and recommendation was simply "no". I'm not much of a tech guy so I thought its better not to overwrite anything and let it install the RStudio without it. Now the RStudio cannot find "knitr" -file. I'm out of options what I'm supposed to do. 

I've attached picture as a file where you can see what the RStudio says. 

![rstudio_problem](https://user-images.githubusercontent.com/31822400/30249481-597bb776-9678-11e7-9f05-9b1e8406cd41.png)

Regards
Petteri

**Comment by vnijs** [comment]
Hi @Pehtonen

You probably already have R and Ratudio. It is Radiant that you want to use. Try running the command below in the Rstudio console (bottom-left window).

`source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R")`

**Comment by vnijs** [comment]
@Pehtonen 

Question: How exactly did you install R, Rstudio, and Radiant? I assume you are using Windows and if so, did you use the all-in-one installer at http://rady.ucsd.edu/faculty/directory/nijs/pub/docs/radiant/Rady-Radiant-Installer-64bit.exe or some other method? Full install instructions are give below.

https://radiant-rstats.github.io/docs/install.html

**Comment by Pehtonen** [comment]
Hi Vincent,


KU is Korea University, located in Seoul. I did install it by the instructions our teacher gave me. Yes I have Windows based computer and I think I did use the right installer.


But now it seems its working (using your update link you gave me). Thank you a lot!


Regards

Petteri


________________________________
Lähettäjä: Vincent Nijs <notifications@github.com>
Lähetetty: 10. syyskuuta 2017 19:21
Vastaanottaja: radiant-rstats/radiant
Kopio: Pehtonen; Mention
Aihe: Re: [radiant-rstats/radiant] Cannot install RStudio. (#28)


@Pehtonen<https://github.com/pehtonen>

Question 1: Just our of curiosity ... where is KU?
Question 2: How exactly did you install R, Rstudio, and Radiant? I assume you are using Windows and if so, did you use the all-in-one installer at http://rady.ucsd.edu/faculty/directory/nijs/pub/docs/radiant/Rady-Radiant-Installer-64bit.exe or some other method? Full install instructions are give below.

https://radiant-rstats.github.io/docs/install.html

**Comment by vnijs** [comment]
Glad to hear Radiant is working now @Pehtonen. Closing the issue
