### ISSUE TITLE
Report not showing plots

### ISSUE THREAD

**Issue by LakshmiNittala** [radiant-rstats/radiant#3]
Hi VIncent,
I started using radiant again after two months and I updated R, Rstudio and Radiant to latest versions.
I tried knitting a report from two months ago and now I see that it is not showing the plots.
Any suggestions?
-Lakshmi

**Comment by vnijs** [comment]
Can you send me the report by email?

**Comment by vnijs** [comment]
Thanks for reporting @LakshmiNittala. Should be fixed in the latest version of radiant.data in the minicran. Just click `Update Radiant` from the addins menu and everything should work as intended.
