### ISSUE TITLE
Am facing with attached problem-radiant

### ISSUE THREAD

**Issue by hanbyul7** [radiant-rstats/radiant#32]
I am using radiant and facing with the attached issues.
pls help me out.

![2017-09-25 21 40 32](https://user-images.githubusercontent.com/32269333/30812540-fae2add0-a245-11e7-9b14-a0dddaf49857.png)
![2017-09-25 21 40 45](https://user-images.githubusercontent.com/32269333/30812543-fcad2136-a245-11e7-9bdc-be2b190327c9.png)

**Comment by vnijs** [comment]
@hanbyul7 why are you using the public version of radiant on shinyapps.io? This app is open to anyone and so is not allowed to run _R > Report_ for security reasons. 

Have you looked into installing Radiant locally? See install instructions below. There is an all-in-one installer for windows and we use this with > 200 students Rady each year

https://radiant-rstats.github.io/docs/install.html

**Comment by vnijs** [comment]
Closing for now.
