### ISSUE TITLE
Margin effects on predictions

### ISSUE THREAD

**Issue by joniarroba** [radiant-rstats/radiant#33]
Dear Vincent, 
Do you know why when we change the values on Margin it also changes the predictions? Below I add some picture, changing the margins. This gives doubts of the overall model itself. Any ideas?

![screenshot from 2017-09-27 18-44-51](https://user-images.githubusercontent.com/4237743/30939745-ead8dc0a-a3b4-11e7-9735-32202c7ff897.png)
![screenshot from 2017-09-27 18-44-38](https://user-images.githubusercontent.com/4237743/30939747-eae2d73c-a3b4-11e7-8831-1fd132b447ca.png)
![screenshot from 2017-09-27 18-44-23](https://user-images.githubusercontent.com/4237743/30939746-eadea220-a3b4-11e7-87cd-f5cc02109788.png)

**Comment by vnijs** [comment]
The predictions do *not* change when you change cost and margin. What changes is how a probability is converted to 1 or 0. If the cost / margin ratio is .5 then a prediction > .5 is labeled as positive, else negative. This may be a bad threshold for infrequently occurring events. Precision, Accuracy, etc. are all sensitive to the threshold that you select. AUC, on the other hand, basically evaluates models across across all possible thresholds and is not sensitive to the cost/margin ratio.

**Comment by joniarroba** [comment]
Thanks Vincent, 
Now it became crystal clear. 
Greetings!
