### ISSUE TITLE
Error: file name conversion problem - name too long?

### ISSUE THREAD

**Issue by seungheekang** [radiant-rstats/radiant#35]
When i used knit report, i got a error massange as above title.

If you need more detail informatiion please send to me by email
Thanks!

**Comment by vnijs** [comment]
Can you provide a screen shot and a state file?

**Comment by seungheekang** [comment]
![kakaotalk_20171001_143703432](https://user-images.githubusercontent.com/32427384/31052899-912ec416-a6cb-11e7-8fb8-886d7c50696e.jpg)

**Comment by seungheekang** [comment]
can you read it?

**Comment by vnijs** [comment]
I can see the screenshot but I don't see a state file on Github. To generate a state file click on the Save icon in the navbar and then "Save state". Please post the file or email it to me at radiant@rady.ucsd.edu

I expect there will also be messages in the Rstudio console. Please share those as well

**Comment by seungheekang** [comment]
I sent email. Plz check for me~~

**Comment by seungheekang** [comment]
Dear sir
I dont have enough time for waiting your feed back
If you send email to me, i will chech again tommorrow.
and have still problem, iwill send you again
 
Thanks
 
-----Original Message-----

**Comment by vnijs** [comment]
I believe this is an issue related to the use of Korean characters in the name of the home directory. If so, this may be resolved in the latest version of Rstudio. Download at https://www.rstudio.com/products/rstudio/download/

If after installing the latest version of Rstudio you still see this problem, please reopen this issue

**Comment by seungheekang** [comment]
Good morning Mr. Vincent
I am not sure you remember me,
I asked to this questions before a month.
Since you kindly explained at that time, i already solved it.
I am studying master business administration in korea university, I have learning R program in the business statistics class. 
I think R program is helpful for us.
  
Thanks 
 
 
-----Original Message-----

**Comment by vnijs** [comment]
That is great @seungheekang. I was closing the issue on github and you automatically get a message at that point ... although I don't think you ever told me specifically how you fixed the issue on your end

**Comment by seungheekang** [comment]
Ah, Sorry about that.
I changed my username from korean to english.
You mentioned before, korean characters was problem with R program.
Thank you again. 
 
 
-----Original Message-----
