### ISSUE TITLE
error in Rstudio after installation

### ISSUE THREAD

**Issue by thk042** [radiant-rstats/radiant#4]
Hi, I got two error messages after installation of Rstudio (newest version).
I can use R but can't use Rstudio, which I need to use.
please see the error messages and help me to solve problems.
Thanks!
Best Regards,
![rstudio](https://cloud.githubusercontent.com/assets/22112549/18408493/ee579814-76e5-11e6-8165-f48d23999095.png)

**Comment by vnijs** [comment]
Thanks for reporting this issue. This is not a problem with Radiant but with R and Rstudio. From the screenshot I'm wondering if changing your language settings to US-english might do the trick. Could you give that a try?

**Comment by vnijs** [comment]
I assume this issue has been resolved. If not, feel free to reopen.
