### ISSUE TITLE
Erros in radiant_update 

### ISSUE THREAD

**Issue by leox3107** [radiant-rstats/radiant#40]
Below, are the error messages I get when attempting to update radiant.

radiant:::update_radiant()

Updating Radiant. Your R session will now restart ...

Restarting R session...

> source('https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R')

#################################################
Updating previously installed packages
#################################################

trying URL 'https://radiant-rstats.github.io/minicran/bin/windows/contrib/3.4/radiant.data_0.9.0.6.zip'
Content type 'application/zip' length 1894091 bytes (1.8 MB)
downloaded 1.8 MB

package ‘radiant.data’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\my_name\AppData\Local\Temp\RtmpcVHQVB\downloaded_packages

#################################################
Installing new packages
#################################################

** There was an issue installing package lattice **
Error in install.packages : Updating loaded packages

###############################################################

  Some packages were not successfully installed or updated

  Offending packages: lattice 

  Use the command below to install these packages:

  install.packages("lattice")

###############################################################

Restarting R session...

Error saving session (plots_dir): Access is denied
WARNING: Forcing suspend of process in spite of all session data not being fully saved.
> install.packages(p, repos = repos, type = type, dependencies = FALSE)
Error in install.packages : object 'repos' not found

**Comment by vnijs** [comment]
Please run the command below after restarting Rstudio:

`source('https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R')`

You can also use `install.packages("lattice")` as shown in the message. If you still have problems please let me know
