### ISSUE TITLE
Saving HTML reports doesn't work.  Please fix in next update.

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#41]
Saving reports as HTML don't seem to work.  This function [dtab(result, dec = 0) %>% render] works when knitting a report, but when the report is saved as HTML, the file appears with the title, a drop down menu to download the .Rmd file, and nothing else.  (Like the image below).  Please fix the bug since this was a useful way to share the functionality to people that don't use Radiant.

![image](https://user-images.githubusercontent.com/36533710/36302935-23b5f2a0-12bf-11e8-8cd9-bac99d2b7307.png)

**Comment by vnijs** [comment]
Thanks for reporting @josh1400. Have you tried restarting Rstudio and running:

`source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R")`

That will install the latest versions Radiant and dependencies. If the issue persists, please provide the state file and the output from `sessionInfo()` after closing Radiant.

**Comment by vnijs** [comment]
@josh1400 Did this address the issue for you or are you still having problems? Please let me know if I can close the issue

**Comment by josh1400** [comment]
That update fixed the problem.

I'll also say that this update solved a lot of the upgrades I've been waiting for (like commas on the numbers)

Thanks :)

**Comment by vnijs** [comment]
Glad to hear it @josh1400 :) Closing issue
