### ISSUE TITLE
No decimal control in saved HTML or Knit Report area

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#42]
When running code like the following in Radiant, the pivot table comes out with 3 decimals regardless of what you set it at.  This issue is only in the report area and with saved HTML files.  The Pivot tab in Data has no issues with decimals.

```{r}
result <- pivotr(
  dataset = "DMA", 
  cvars = c("fiscal_quarter", "stuff"), 
  nvar = "variable", 
  fun = "sum_rm", 
  tabsort = "desc(Total)"
)
# summary(result, dec = 0)
dtab(result, dec = 0) %>% render()
# store(result, name = "DMA_pvt")
```

**Comment by vnijs** [comment]
Thanks for the report @josh1400. I'll push the fix to GitHub today or tomorrow. It will be a few more weeks before I can submit the updates to CRAN

**Comment by vnijs** [comment]
The update of `radiant.data` is now in github. I'll close the issue now but please reopen if needed
