### ISSUE TITLE
Data--Visualize can not show specific plot.

### ISSUE THREAD

**Issue by ruinyxu** [radiant-rstats/radiant#43]
Hi,
   I am learning the Radiant on my statistics class, and there is a same problem which one of my classmates and I have now.

  When I tried to make a plot under the Visualize section ,with setting “Plot-type”as "Scatter","Y-variable"as "Net Sales",and "X-variable"as "Age", it does not show the plot no matter how long I wait. However, if I change the variables, it can show the plot without any problems.I attached the screen shot of my computer. 

  I will be grateful if you tell me how to deal with this problem.

  Thank you.

Best wishes.

<img width="960" alt="_20180314112500" src="https://user-images.githubusercontent.com/37150622/37380593-b3be344e-277c-11e8-9a43-1f1085297edc.png">

**Comment by vnijs** [comment]
Thank you for reporting this issue. Should be fixed now. You can upgrade using the command below:

`source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R")`
