### ISSUE TITLE
only "scatter" from visualize tab is not functioning well

### ISSUE THREAD

**Issue by wp02157** [radiant-rstats/radiant#44]
only "scatter" from visualize tab is not functioning well. I don't know why. eveything else works well.  I tried it through two web browers

![problem](https://user-images.githubusercontent.com/37375203/37410721-1ac657ea-2799-11e8-9d10-d5151f7c5479.PNG)

 called "chrome" and "explorer" . please let me know the solution.

**Comment by vnijs** [comment]
Thanks for reporting. This issue was fixed in response to https://github.com/radiant-rstats/radiant/issues/43. Please run the command below to get the latest updates:

`source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R")`
