### ISSUE TITLE
I have problem on the install procress

### ISSUE THREAD

**Issue by ruinyxu** [radiant-rstats/radiant#45]
Hi,

Thank you for offering me the resolution on how to deal with the problem that the radiant can not show the plot.
You said that: "You can upgrade using the command below:

source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R")"

I followed what you said but when I tried to open the radiant , the letters of the last line always showed up and I cannot open the radiant now.Besides, I told my classmate the method to update, and her computer showed the same problem as mine,too.I attached the screen shot.

I am looking forward for your reply.
Thank you.

Best wishes.

<img width="960" alt="86e6b5b27d22f78a3907e99a6166528" src="https://user-images.githubusercontent.com/37150622/37412363-122ae282-27e8-11e8-810e-ca157743d0dd.png">

**Comment by vnijs** [comment]
Thanks again for reporting. Please try again now using the same command:

`source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R")`

**Comment by vnijs** [comment]
I assume the issue is resolved. If not, please re-open.
