### ISSUE TITLE
with regard to #44, it is still not working even though I tried to solve problem in the way that you suggested

### ISSUE THREAD

**Issue by wp02157** [radiant-rstats/radiant#46]
the problem is even aggravated. before updating, I could access to radiant by clicking 'start radiant browers from addins tab'. however, currently, I can not access to radiant let alone "scatter" tab .
when I clicked 'start radinat brower', the last line from the attached file appeared. 
![problem2](https://user-images.githubusercontent.com/37375203/37438477-8f276ec0-27ea-11e8-96fc-d2d020f047cf.png)

**Comment by vnijs** [comment]
Please close Rstudio and then start Rstudio again. Then run the code below. If you still have problems please add a comment to this issue rather than opening a new one. 

`source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R")`

**Comment by vnijs** [comment]
FYI You can also try running the command in R (rather than Rstudio). Upgrading the "yaml" package can sometimes be tricky in Rstudio

**Comment by vnijs** [comment]
FYI If you are still stuck you can try using Radiant through the link below. It is a free service, not very fast, and you should not upload private data but it might be useful until your updating issue is resolved.

https://vnijs.shinyapps.io/radiant

**Comment by vnijs** [comment]
Assuming this is resolved. If not, please re-open
