### ISSUE TITLE
My r radient is not working. making pdf files.

### ISSUE THREAD

**Issue by lovestargirl** [radiant-rstats/radiant#48]
my r radient is not working. there are problems when i try to make a pdf file.
only empty text file is in my downloads.
i wanted to attach my r radient state file with this issue but it says that this page doesnt support rda file type. hope i could solve this problem soon.

**Comment by vnijs** [comment]
Can you post the content of Report > Rmd ? Also, any messages shown in Rstudio?

**Comment by lovestargirl** [comment]
# Business Statistics

### HW1

```{r}
result <- explore(
  dataset = "PelicanStores", 
  vars = "Items", 
  fun = c("min_rm", "p25", "median_rm", "p75", "max_rm"), 
  nr = 1
)
summary(result)
# dtab(result) %>% render()
# store(result, name = "PelicanStores_expl")
```



```{r fig.width = 7, fig.height = 7, dpi = 96}
visualize(
  dataset = "PelicanStores", 
  xvar = "Net.Sales", 
  yvar = "Customer", 
  type = "scatter", 
  custom = FALSE
)
```


```{r fig.width = 7, fig.height = 7, dpi = 96}
visualize(
  dataset = "PelicanStores", 
  xvar = "dummy", 
  yvar = "Net.Sales", 
  type = "box", 
  custom = FALSE
)
```


this is the content of the report rmd. it works perfectly with saving in word, but only pdf does not work. 
i want to attatch the file that was saved instead, when i tried to save the report as pdf file. but since it is an empty text file, it says it cannot be attatched.

**Comment by lovestargirl** [comment]
and there were no messages.

**Comment by lovestargirl** [comment]
R version 3.4.2 (2017-09-28) -- "Short Summer"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> radiant:::radiant()

Starting radiant in default browser ...

Use radiant::radiant_viewer() to open radiant in Rstudio viewer

Listening on http://127.0.0.1:6676
ERROR: [on_request_read] connection reset by peer
pandoc.exe: pdflatex not found. pdflatex is needed for pdf output.
Warning: running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS report-4d46bfd4c52.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output report-4d46bfd4c52.pdf --template "c:\R\R-3.4.2\library\rmarkdown\rmd\latex\default-1.17.0.2.tex" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in"' had status 41
Warning: Error in : pandoc document conversion failed with error 41
Stack trace (innermost first):
    68: pandoc_convert
    67: convert
    66: rmarkdown::render
    65: eval [c:/R/R-3.4.2/library/radiant.data/app/tools/app/report_funs.R#601]
    64: eval
    63: withProgress
    56: isolate
    55: report_save_content [c:/R/R-3.4.2/library/radiant.data/app/tools/app/report_funs.R#497]
    54: download$func [c:/R/R-3.4.2/library/radiant.data/app/tools/app/report_rmd.R#495]
     5: shiny::runApp
     4: withCallingHandlers
     3: suppressPackageStartupMessages
     2: radiant.data::launch
     1: radiant:::radiant
Error : pandoc document conversion failed with error 41
pandoc.exe: pdflatex not found. pdflatex is needed for pdf output.
Warning: running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS report-4d448f46820.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output report-4d448f46820.pdf --template "c:\R\R-3.4.2\library\rmarkdown\rmd\latex\default-1.17.0.2.tex" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in"' had status 41
Warning: Error in : pandoc document conversion failed with error 41
Stack trace (innermost first):
    68: pandoc_convert
    67: convert
    66: rmarkdown::render
    65: eval [c:/R/R-3.4.2/library/radiant.data/app/tools/app/report_funs.R#601]
    64: eval
    63: withProgress
    56: isolate
    55: report_save_content [c:/R/R-3.4.2/library/radiant.data/app/tools/app/report_funs.R#497]
    54: download$func [c:/R/R-3.4.2/library/radiant.data/app/tools/app/report_rmd.R#495]
     5: shiny::runApp
     4: withCallingHandlers
     3: suppressPackageStartupMessages
     2: radiant.data::launch
     1: radiant:::radiant
Error : pandoc document conversion failed with error 41



actually there were some messages in r studio.  these are the messages.

**Comment by vnijs** [comment]
You likely don't have latex installed which is required for PDF. Try the link below for one option or else do a search for MikTex

https://yihui.name/tinytex/

After installing, restart Rstudio and try creating a PDF again.

**Comment by vnijs** [comment]
I assume you were able to install a version of Latex (e.g., tinytex) and can now generate PDF documents. If not, you can re-open this issue
