### ISSUE TITLE
Saving Report as PDF File

### ISSUE THREAD

**Issue by regina3371** [radiant-rstats/radiant#49]
I can't save my report as PDF file. Other files work fine, but an error occurs whenever I try to save reports as PDF file.

## Q3

```{r fig.width = 7, fig.height = 7, dpi = 200}
visualize(
  dataset = "복사본 PelicanStores", 
  xvar = "Items", 
  yvar = "Net.Sales", 
  type = "scatter", 
  nrobs = -1, 
  custom = FALSE
)
```

**Comment by vnijs** [comment]
Not much I can say about that without more information. Can you copy all message from a Rstudio?

**Comment by regina3371** [comment]
I hope this is the right content:(


---
title: ""
output:
  html_document:
    highlight: textmate
    theme: spacelab
    df_print: paged
    toc: yes
    code_folding: hide
    code_download: true
---

```{r r_setup, include = FALSE}
## initial settings
knitr::opts_chunk$set(
  comment = NA,
  echo = TRUE,
  error = TRUE,
  cache = FALSE,
  message = FALSE,
  dpi = 200,
  warning = FALSE
)

## width to use when printing tables etc.
options(
  width = 250,
  scipen = 100,
  max.print = 5000,
  stringsAsFactors = FALSE
)

## make all required libraries available by loading radiant package if
needed
if (!exists("r_environment")) library(radiant)

## load data (add path)
# r_data <- readr::read_rds("r_data.rds")
```

<style>
.table {
  width: auto;
}
ul, ol {
  padding-left: 18px;
}
pre, code, pre code {
  overflow: auto;
  white-space: pre;
  word-wrap: normal;
  background-color: #ffffff;
}
</style>

## Q3


```{r fig.width = 7, fig.height = 7, dpi = 200}
visualize(
  dataset = "복사본 PelicanStores",
  xvar = "Items",
  yvar = "Net.Sales",
  type = "scatter",
  nrobs = -1,
  custom = FALSE
)
```


2018-03-22 16:38 GMT+09:00 Vincent Nijs <notifications@github.com>:

**Comment by vnijs** [comment]
You likely don't have latex installed which is required for PDF. Try the link below for one option or else do a search for MikTex

https://yihui.name/tinytex/ 

After installing, restart Rstudio and try creating a PDF again.

**Comment by vnijs** [comment]
I assume you were able to install a version of Latex (e.g., tinytex) and can now generate PDF documents. If not, you can re-open this issue
