### ISSUE TITLE
Radiant crashing when using the simulate menu

### ISSUE THREAD

**Issue by gofarm** [radiant-rstats/radiant#53]
I just updated to R 3.4 and the most recent Radiant version today to address issues with plots from the data menu not representing in the report section. The state file I am using was originally built on R 3.3 and an older version of Radiant (don't remember which, installed back in January). I'm running on Chrome. After update, when I attempt to run a simulation, Radiant screen greys out and becomes non-responsive. I get the following error in RStudio console: 

Warning: Error in if: missing value where TRUE/FALSE needed
Stack trace (innermost first):
    69: observeEventHandler [C:/Users/SheridanVentures/Documents/R/win-library/3.4/radiant.model/app/tools/analysis/simulater_ui.R#338]
     5: shiny::runApp
     4: withCallingHandlers
     3: suppressPackageStartupMessages
     2: radiant.data::launch
     1: radiant:::radiant
ERROR: [on_request_read] connection reset by peer

Any help appreciated.

**Comment by vnijs** [comment]
Can you email me the state file @ radiant@rady.ucsd.edu?

**Comment by vnijs** [comment]
Fixed [#53](https://github.com/radiant-rstats/radiant.model/commit/89180d8d628e0383cdd564b51977e44591ac2da0)
