### ISSUE TITLE
Can't rename integer variable

### ISSUE THREAD

**Issue by jwaugh28** [radiant-rstats/radiant#54]
Selecting to rename an integer variable gives error message "Error: is.character(txt) is not TRUE"

![image](https://user-images.githubusercontent.com/38676301/39161799-d1a655dc-47b5-11e8-931e-edf6e4b37d49.png)

**Comment by vnijs** [comment]
I can't reproduce that error. See screenshot below. Does it also happen with `saleitemid` or `invengoryitemid`? Are there any messages shown in the Rstudio console? 

https://radiant-rstats.github.io/docs/news.html

Also, could you upgrade to the latest version of Radiant (see link below) and try again? 

![image](https://user-images.githubusercontent.com/2998956/39162768-fad6af54-472b-11e8-8114-ac99fe803587.png)

**Comment by jwaugh28** [comment]
Thanks @vnijs for the extremely fast response!

Updating the package (via the addin update manager) resolved my issue after installing some dependencies.

Thanks so much for this package - I'm really blown away by radiant. It will change how I approach data analysis & documentation in the future.

One question / suggestion - is it possible to see a log style file of everything that has been run in radiant for a particular session? Such a thing would be great to further enhance reproducibility (especially for outside of the radiant environment) to see what transformations etc were done to arrive at the current state.

James

**Comment by vnijs** [comment]
Thanks for the compliment James :) I think what you are asking for is in _Report > Rmd_ (and/or _Report > R_). See links below. The youtube clip needs to be updated but it will give you the ideas.

https://radiant-rstats.github.io/docs/data/report_rmd.html  
https://youtu.be/pNNQc2lHR8Q

**Comment by jwaugh28** [comment]
No worries,

I think my question still stands regarding a log file though. As it currently stands the user to manually hits the button to add a code chunk to the Rmd file (this is certainly desirable for documentation - you shouldn't need to re-execute everything every time).

However if a user shares a state file with another user for example, they can load the state and see the current Rmd file, however there is no 'history' of data manipulations, changes etc that were run to actually go from the initial raw data to the current state (unless the first user chose to manually document every single thing they did).

My suggestion is to:
 - Keep the Rmd format exactly as is - i.e. users manually add chunks by choice.
 - A separate text file maintains a 'log' of _everything that was executed in radiant that changed the underlying data_. This can be stored in the state file.

The advantage of this is it makes radiant even more reproducible from raw-data to current state with steps that can be exported and modified in rstudio where appropriate without burdening the user to manually track everything they have done that changed the data.

Keen to hear your thoughts :).

James

**Comment by vnijs** [comment]
I see what you mean now. Not really feasible with a shiny-based app however. If you change the data and you want your analysis to reproducible you have to explicitly store the code you want to keep. This does have the advantage that the user can explore and try things without having to slog through a large, and likely messy, log file.

**Comment by jwaugh28** [comment]
This is true, I understand your preference for this design decision.

Thanks again for a great app!

James

**Comment by vnijs** [comment]
Thanks James. Enjoy radiant!
