### ISSUE TITLE
problem installing Gmedian

### ISSUE THREAD

**Issue by danielsender** [radiant-rstats/radiant#56]
I'm installing Radiant for a friend of mine - I have no clue about the program, so I don't know how to fix the problem. When in Rstudio (Ubuntu 18.04)  I click on Adding->Update Radiant, it would give me error messages after compilations steps, which are:

`****_** preparing package for lazy loading
Warning: S3 methods ‘eigs.matrix’, ‘eigs.dgeMatrix’, ‘eigs.dgCMatrix’, ‘eigs.dgRMatrix’, ‘eigs.dsyMatrix’, ‘eigs.function’, ‘eigs_sym.matrix’, ‘eigs_sym.dgeMatrix’, ‘eigs_sym.dgCMatrix’, ‘eigs_sym.dgRMatrix’, ‘eigs_sym.function’, ‘svds.matrix’, ‘svds.dgeMatrix’, ‘svds.dgCMatrix’, ‘svds.dgRMatrix’, ‘svds.dsyMatrix’, ‘svds.function’ were declared in NAMESPACE but not found
Error in namespaceExport(ns, exports) : 
  undefined exports: eigs, eigs_sym, svds
ERROR: lazy loading failed for package ‘Gmedian’
* removing ‘/home/benji/R/x86_64-pc-linux-gnu-library/3.4/Gmedian’

The downloaded source packages are in
	‘/tmp/Rtmp5vPCUy/downloaded_packages’
Warning message:
In install.packages("Gmedian") :
  installation of package ‘Gmedian’ had non-zero exit status_****

I would appreciate any help.

Daniel
`

**Comment by vnijs** [comment]
`Gmedian` is a package that radiant uses and for some reason it is not installing on your ubuntu system. I can't replicate the problem on systems I have access to. Can you run the command below and post back *all* output that is generated in Rstudio? Also, please provide the output from `sessionInfo()`.

`install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/")`

**Comment by danielsender** [comment]
`Content type 'application/gzip' length 134563 bytes (131 KB)
==================================================
downloaded 131 KB

* installing *source* package ‘Gmedian’ ...
** package ‘Gmedian’ successfully unpacked and MD5 sums checked
** libs
g++  -I/usr/share/R/include -DNDEBUG  -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/RcppArmadillo/include" -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/RSpectra/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Gmedian.cpp -o Gmedian.o
g++  -I/usr/share/R/include -DNDEBUG  -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/RcppArmadillo/include" -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/RSpectra/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++  -I/usr/share/R/include -DNDEBUG  -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/RcppArmadillo/include" -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/RSpectra/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Weiszfeld.cpp -o Weiszfeld.o
g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o Gmedian.so Gmedian.o RcppExports.o Weiszfeld.o -L/usr/lib/R/lib -lR
installing to /home/benji/R/x86_64-pc-linux-gnu-library/3.4/Gmedian/libs
** R
** preparing package for lazy loading
Warning: S3 methods ‘eigs.matrix’, ‘eigs.dgeMatrix’, ‘eigs.dgCMatrix’, ‘eigs.dgRMatrix’, ‘eigs.dsyMatrix’, ‘eigs.function’, ‘eigs_sym.matrix’, ‘eigs_sym.dgeMatrix’, ‘eigs_sym.dgCMatrix’, ‘eigs_sym.dgRMatrix’, ‘eigs_sym.function’, ‘svds.matrix’, ‘svds.dgeMatrix’, ‘svds.dgCMatrix’, ‘svds.dgRMatrix’, ‘svds.dsyMatrix’, ‘svds.function’ were declared in NAMESPACE but not found
Error in namespaceExport(ns, exports) : 
  undefined exports: eigs, eigs_sym, svds
ERROR: lazy loading failed for package ‘Gmedian’
* removing ‘/home/benji/R/x86_64-pc-linux-gnu-library/3.4/Gmedian’
ERROR: dependency ‘Gmedian’ is not available for package ‘radiant.multivariate’
* removing ‘/home/benji/R/x86_64-pc-linux-gnu-library/3.4/radiant.multivariate’
ERROR: dependency ‘radiant.multivariate’ is not available for package ‘radiant’
* removing ‘/home/benji/R/x86_64-pc-linux-gnu-library/3.4/radiant’

The downloaded source packages are in
	‘/tmp/Rtmp1txK3c/downloaded_packages’
Warning messages:
1: In install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/") :
  installation of package ‘Gmedian’ had non-zero exit status
2: In install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/") :
  installation of package ‘radiant.multivariate’ had non-zero exit status
3: In install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/") :
  installation of package ‘radiant’ had non-zero exit status
`
Many thanks for your prompt response.

**Comment by danielsender** [comment]
`> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4 tools_3.4.4 `

**Comment by vnijs** [comment]
That didn't help as much as I hoped it would :) Could you try the command below and report all messages? If that doesn't provide any inspiration, I'll get in touch with the package author of `Gmedian` for suggestions.

`install.packages(c("Rcpp", "RSpectra", "robustbase", "RcppArmadillo", "Gmedian"))`

**Comment by danielsender** [comment]
`> install.packages(c("Rcpp", "RSpectra", "robustbase", "RcppArmadillo", "Gmedian"))
Installing packages into ‘/home/benji/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/Rcpp_0.12.16.tar.gz'
Content type 'application/x-gzip' length 3763400 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

trying URL 'https://cloud.r-project.org/src/contrib/RSpectra_0.12-0.tar.gz'
Content type 'application/x-gzip' length 426762 bytes (416 KB)
==================================================
downloaded 416 KB

trying URL 'https://cloud.r-project.org/src/contrib/robustbase_0.93-0.tar.gz'
Content type 'application/x-gzip' length 2958250 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

trying URL 'https://cloud.r-project.org/src/contrib/RcppArmadillo_0.8.500.0.tar.gz'
Content type 'application/x-gzip' length 1347753 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

trying URL 'https://cloud.r-project.org/src/contrib/Gmedian_1.2.4.tar.gz'
Content type 'application/x-gzip' length 17196 bytes (16 KB)
==================================================
downloaded 16 KB

* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Date.cpp -o Date.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Module.cpp -o Module.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Rcpp_init.cpp -o Rcpp_init.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c api.cpp -o api.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c attributes.cpp -o attributes.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c barrier.cpp -o barrier.o
g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o Rcpp.so Date.o Module.o Rcpp_init.o api.o attributes.o barrier.o -L/usr/lib/R/lib -lR
installing to /home/benji/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (Rcpp)
* installing *source* package ‘robustbase’ ...
** package ‘robustbase’ successfully unpacked and MD5 sums checked
** libs
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c R-rng4ftn.c -o R-rng4ftn.o
gfortran   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong  -c eigen.f -o eigen.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c lmrob.c -o lmrob.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c mc.c -o mc.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c monitor.c -o monitor.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c qn_sn.c -o qn_sn.o
gfortran   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong  -c rf-common.f -o rf-common.o
gfortran   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong  -c rffastmcd.f -o rffastmcd.o
gfortran   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong  -c rfltsreg.f -o rfltsreg.o
gfortran   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong  -c rllarsbi.f -o rllarsbi.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c rob-utils.c -o rob-utils.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c rowMedians.c -o rowMedians.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c wgt_himed.c -o wgt_himed.o
g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o robustbase.so R-rng4ftn.o eigen.o init.o lmrob.o mc.o monitor.o qn_sn.o rf-common.o rffastmcd.o rfltsreg.o rllarsbi.o rob-utils.o rowMedians.o wgt_himed.o -llapack -lblas -lgfortran -lm -lquadmath -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
installing to /home/benji/R/x86_64-pc-linux-gnu-library/3.4/robustbase/libs
** R
** data
*** moving datasets to lazyload DB
** demo
** inst
** byte-compile and prepare package for lazy loading
Creating a generic function from function ‘chgDefaults’ in package ‘robustbase’
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (robustbase)
ERROR: failed to lock directory ‘/home/benji/R/x86_64-pc-linux-gnu-library/3.4’ for modifying
Try removing ‘/home/benji/R/x86_64-pc-linux-gnu-library/3.4/00LOCK-RSpectra’
* installing *source* package ‘RcppArmadillo’ ...
** package ‘RcppArmadillo’ successfully unpacked and MD5 sums checked
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking whether g++ version is sufficient... yes, with OpenMP as version 7.3.0
checking for macOS... checking LAPACK_LIBS... system LAPACK found
checking for OpenMP... found and suitable
configure: creating ./config.status
config.status: creating inst/include/RcppArmadilloConfigGenerated.h
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG  -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -I../inst/include -fopenmp -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c RcppArmadillo.cpp -o RcppArmadillo.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG  -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -I../inst/include -fopenmp -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG  -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -I../inst/include -fopenmp -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c fastLm.cpp -o fastLm.o
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o RcppArmadillo.so RcppArmadillo.o RcppExports.o fastLm.o -fopenmp -llapack -lblas -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
installing to /home/benji/R/x86_64-pc-linux-gnu-library/3.4/RcppArmadillo/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (RcppArmadillo)
* installing *source* package ‘Gmedian’ ...
** package ‘Gmedian’ successfully unpacked and MD5 sums checked
** libs
g++  -I/usr/share/R/include -DNDEBUG  -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/RcppArmadillo/include" -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/RSpectra/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Gmedian.cpp -o Gmedian.o
g++  -I/usr/share/R/include -DNDEBUG  -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/RcppArmadillo/include" -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/RSpectra/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++  -I/usr/share/R/include -DNDEBUG  -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/RcppArmadillo/include" -I"/home/benji/R/x86_64-pc-linux-gnu-library/3.4/RSpectra/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Weiszfeld.cpp -o Weiszfeld.o
g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o Gmedian.so Gmedian.o RcppExports.o Weiszfeld.o -L/usr/lib/R/lib -lR
installing to /home/benji/R/x86_64-pc-linux-gnu-library/3.4/Gmedian/libs
** R
** preparing package for lazy loading
Warning: S3 methods ‘eigs.matrix’, ‘eigs.dgeMatrix’, ‘eigs.dgCMatrix’, ‘eigs.dgRMatrix’, ‘eigs.dsyMatrix’, ‘eigs.function’, ‘eigs_sym.matrix’, ‘eigs_sym.dgeMatrix’, ‘eigs_sym.dgCMatrix’, ‘eigs_sym.dgRMatrix’, ‘eigs_sym.function’, ‘svds.matrix’, ‘svds.dgeMatrix’, ‘svds.dgCMatrix’, ‘svds.dgRMatrix’, ‘svds.dsyMatrix’, ‘svds.function’ were declared in NAMESPACE but not found
Error in namespaceExport(ns, exports) : 
  undefined exports: eigs, eigs_sym, svds
ERROR: lazy loading failed for package ‘Gmedian’
* removing ‘/home/benji/R/x86_64-pc-linux-gnu-library/3.4/Gmedian’

The downloaded source packages are in
	‘/tmp/Rtmp8mfm3p/downloaded_packages’
Warning messages:
1: In install.packages(c("Rcpp", "RSpectra", "robustbase", "RcppArmadillo",  :
  installation of package ‘RSpectra’ had non-zero exit status
2: In install.packages(c("Rcpp", "RSpectra", "robustbase", "RcppArmadillo",  :
  installation of package ‘Gmedian’ had non-zero exit status
`

**Comment by vnijs** [comment]
Problem starts with rspectra. Try removing the mentioned directory and then installing rspectra again. If that succeeds try gmedian again

**Comment by danielsender** [comment]
Can you please tell me how to remove that directory?

**Comment by vnijs** [comment]
rm -rf /home/benji/R/x86_64-pc-linux-gnu-library/3.4/00LOCK-RSpectra

and maybe

rm -rf /home/benji/R/x86_64-pc-linux-gnu-library/3.4/RSpectra

**Comment by danielsender** [comment]
Great! That did the trick - When I installed Gmedian it automatically also installed RSpectra. Now I'm trying to figure out how to star Radiant - in the Addings drop-down menu I only see mentioned "Update radiant", how do I do that?

**Comment by danielsender** [comment]
I just typed install.packages("radiant"), and after appeared in the Addins menu -

Thank you very much for your help. You saved my day (and night)!

**Comment by danielsender** [comment]
OK - So can I type your command now or I have to do some other intermediate step? Currently I can start Radiant from the Addins menu.

Thanks.

**Comment by danielsender** [comment]
`> install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/")
Installing package into ‘/home/benji/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://radiant-rstats.github.io/minicran/src/contrib/radiant_0.9.3.1.tar.gz'
Content type 'application/gzip' length 134563 bytes (131 KB)
==================================================
downloaded 131 KB

* installing *source* package ‘radiant’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (radiant)

The downloaded source packages are in
	‘/tmp/Rtmpb0rCty/downloaded_packages’

So, is this OK?

Thanks again.`

**Comment by vnijs** [comment]
Looks like it. If you can run radiant now I'll close the issue.
