### ISSUE TITLE
Trouble Installing Radiant

### ISSUE THREAD

**Issue by Sudarshanb1990** [radiant-rstats/radiant#57]
I am getting the following error message while trying to install Radiant.

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘feather’

**Comment by vnijs** [comment]
I assume you are on Windows, using R 3.5. Unfortunately feather is not available for that platform and it is not clear if or when it will be (https://github.com/wesm/feather/issues/338)

Did you install radiant using the command below?

`install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/")`

**Comment by Sudarshanb1990** [comment]
Hey vnijs,
Thankyou for the comment. I tried re-installing and I am now getting the following error message.
Warning in install.packages :
  unable to move temporary installation ‘c:\R\R-3.4.4\library\file2aec46574a3a\knitr’ to ‘c:\R\R-3.4.4\library\knitr’
and when I try to run radiant,I get this message:
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘knitr.
What should I do?

**Comment by vnijs** [comment]
Do you have a virus checker running? That can sometimes interfere with R-package installation. Try turning the virus checker off temporarily and then use:

`install.packages("knitr")`

If other, similar messages, pop-up turn the command below again:

`install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/")`

**Comment by vnijs** [comment]
I'll close this issue for now but please reopen if needed
