### ISSUE TITLE
Unable to save data as csv file

### ISSUE THREAD

**Issue by Sudarshanb1990** [radiant-rstats/radiant#59]
I am unable to save my work as a csv file. When I try to do that I get the following error message.
"Failed - Server problem".
 Please help

**Comment by vnijs** [comment]
Use the commands below to upgrade to the latest version of Radiant. Then please try again.

```r
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```

**Comment by Sudarshanb1990** [comment]
Thankyou Vincent
