### ISSUE TITLE
Error: invalid 'y' type in 'x && y'

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#60]
All my old state files have the following error in the pivot tab.

If I copy the rmd code over to a brand new state and rerun it, I have no problems.  I can save those states and everything works fine.

**Comment by vnijs** [comment]
I'll need a specific example to figure that one out. Can you email?

**Comment by vnijs** [comment]
Were these pivot tables you were trying to "store" perhaps?

**Comment by josh1400** [comment]
Nothing is wrong with the code.  Many of the state files don't even have pivot tables.

All of my old state files simply show this error on the Pivot tab regardless of the dataset selected.

![image](https://user-images.githubusercontent.com/36533710/41382240-32e452a4-6f20-11e8-9cc4-dac6b8abf0eb.png)

**Comment by josh1400** [comment]
The only solution I've found is copying the code, restarting Radiant, pasting the code, and saving a new state file.

**Comment by vnijs** [comment]
Found the issue! Thanks for reporting Josh! I'll push the update soon. In the meantime adding the code below in at the top of your _Report > Rmd_ should fix as well.

`r_state$pvt_type <- FALSE`

**Comment by josh1400** [comment]
Great to hear.  Thanks :)

**Comment by vnijs** [comment]
New version posted (radiant.data 0.9.5.1). The update should close the issue. Please update and confirm. Thanks for reporting this issue @josh1400!

**Comment by josh1400** [comment]
That seems to have fixed the issue.

**Comment by vnijs** [comment]
Great. Thanks Josh. Closing now.
