### ISSUE TITLE
How would connecting to a multidimensional cube database affect how Radiant interacts with the data?

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#61]
How would connecting to a multidimensional cube database affect how Radiant interacts with the data?

https://docs.microsoft.com/en-us/sql/advanced-analytics/r/using-data-from-olap-cubes-in-r?view=sql-server-2017

**Comment by vnijs** [comment]
I'm not sure what you are asking. R (and Radiant) need data in memory for analysis. If you can pull data from the cube in R you can use it in Radiant.

**Comment by vnijs** [comment]
Closing for now. Reopen if needed
