### ISSUE TITLE
any plan to support spark

### ISSUE THREAD

**Issue by witwall** [radiant-rstats/radiant#63]
It is there any plan to support spark? thanks!

**Comment by vnijs** [comment]
If you write R-code to extract data from a spark cluster you can include that at the start of your report (see _Report > Rmd_) and assign the result to a data frame that you can then register (i.e., `register("my_data_from_spart")` and use in Radiant. 

Having the functions used in radiant actually run *in* a spark cluster is unlikely to happen I think.

**Comment by witwall** [comment]
sparklyr: R interface for Apache Spark, provides a complete dplyr backend. 
I know it has many difference with data.frame

![image](https://user-images.githubusercontent.com/3222056/42364549-17e10838-812e-11e8-82a3-de5014a24187.png)

**Comment by vnijs** [comment]
Once you apply `collect` to the slice of the data you want, however, it should work just as a regular in-memory data.frame which you can use in radiant without any problems.

**Comment by witwall** [comment]
but if the amount of data is big, collect is not a good idea.

**Comment by vnijs** [comment]
True. But most of R (and Python etc.) is set up to analyze data in memory. When you are using `sparklyr` or `dplyr` with some database, before you use `collect` the data is not actually in memory yet. Of course, with very large datasets you try to wait as long as possible to use `collect` but you have to before you run the analysis. The only alternative is to use functions that run *in* the spark-cluster or *in* the database. I haven't looked into it but I expect that would require a *lot* of work for a tool like radiant, if it is even possible at all

**Comment by vnijs** [comment]
I'll close this issue for now
