### ISSUE TITLE
Window Function Support

### ISSUE THREAD

**Issue by witwall** [radiant-rstats/radiant#64]
Does it support Window function? if not? any plan ?
thanks in advance.

**Comment by vnijs** [comment]
Do you mean window functions for a database? As I mentioned for spark, if you `collect` the slice of data you want and put it into a data.frame that will work fine.

**Comment by witwall** [comment]
not about spark,  dplyr supports Window Function

**Comment by vnijs** [comment]
dplyr is supported

**Comment by witwall** [comment]
I means support window function in UI

**Comment by vnijs** [comment]
You can run any R code, including dplyr functions such as discussed in https://cran.r-project.org/web/packages/dplyr/vignettes/window-functions.html in _Report > Rmd_ and _Report > R_. Basic transformations have specific entries in a dropdown in _Data > Transform_ (e.g., changing variable type from character to factor). For any more advanced functions to be include in a call to `mutate` you can use _Data > Transform > Create_. See http://radiant-rstats.github.io/radiant.data/articles/pkgdown/transform.html#create for basic examples that can be extended to use any R-function you want. 

For example, once you click the `Store` button in _Data > Transform_ using the settings shown in the screenshot below a new variable `price_rank` is added to the `diamonds` data and the following R code is generated that you can include in a report.

```
diamonds <- group_by(diamonds, cut) %>%
  mutate(price_rank = percent_rank(price)) %>%
  ungroup()
```

![image](https://user-images.githubusercontent.com/2998956/42720646-cc9addf6-86df-11e8-8d94-16c013f15314.png)

You can also use window functions in filters (e.g., in _Data > View_). 

![image](https://user-images.githubusercontent.com/2998956/42720627-79290d50-86df-11e8-83bf-35b65e45ee39.png)

**Comment by vnijs** [comment]
@witwall Does this address your question?

**Comment by witwall** [comment]
@vnijs 
thanks, like this, but it would  be better  if had  ui to interactive, and for this example, should better have arrange method,
 
```
diamonds <- group_by(diamonds, cut) %>%
arrange(desc(price))%>%
  mutate(price_rank = percent_rank(price)) %>%
  ungroup()
```

**Comment by vnijs** [comment]
I think it would be difficult to design a good UI that would be sufficiently flexible for something like this. That said, If you have ideas for a really good UI I'd be happy to look at a PR

**Comment by witwall** [comment]
yes, it is difficult, I am not familiar with UI.

 I introduced radiant to business analysts, who are not familiar with coding,  but like this great app.

**Comment by witwall** [comment]
thanks
