### ISSUE TITLE
MacOs installation. Library cairo is not installed automatically

### ISSUE THREAD

**Issue by AlekseyBuzmakov** [radiant-rstats/radiant#65]
Thank you far a nice tool! I have given radiant as a tool for data analysis in a summer school on data analytics. Many persons on MacOs has faced a problem with the library cairo that is not installed. The result is that no visualization is possible in radiant.  Would it be possible to modify the install script to automatically install cairo

**Comment by vnijs** [comment]
Thanks for the note @AlekseyBuzmakov. What you describe seems very odd to me though. I use a mac and don't have cairo installed but visualization works fine. Do you have any error messages you can share to help track down what is going on? What analysis tool were you using when this problem showed up?

**Comment by AlekseyBuzmakov** [comment]
I provide the screenshots and the OS version. If you need other information please let me know.

Plots is not shown as it has not been drawn at all:
![No plot screenshot](https://www.dropbox.com/s/3u6b9c2unz5igaa/no-plot.png?dl=1)

The errors in RStudio:
![Errors in RStudio](https://www.dropbox.com/s/p6hs039h875fcvv/error.png?dl=1)

The Mac OS version:
![Mac OS version](https://www.dropbox.com/s/9omkl4vqb2nzzis/macos-version.png?dl=1)

UPD: we have found a the same MacOS but with working plots, so there is some other reason

**Comment by vnijs** [comment]
Thanks for reporting @AlekseyBuzmakov. Never seen this issue before and don't know what is going on (yet). Radiant uses `ggplot2` for (almost) all plots and doesn't require `cairo`. To start, can you install the latest version of the different radiant packages using the commands below:

```r
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```

If the issue still occurs please post the output from running `sessionInfo()`?

**Comment by AlekseyBuzmakov** [comment]
@vnijs , most of the users has installed fresh radiant + R + MacOS just on Monday. One some fo them radiant.update (from addins) has found nothing (I do not use MacOS, and it is a bit hard to run smth on them, but a number of summer school participants has complained).

One of the users has found a solution. I put it here for information.

1.    https://www.xquartz.org is needed
2.    Then follow https://github.com/randy3k/homebrew-r#installing-r-with-x11-support (both blocks, but just the first point)
3.    Then after restart of RStudio, everything works

It seems that it is an issue of RSutdio rather than radiant. So it is likely you are unable to correct it, but probably this inforamtion would be useful. Thank you.

**Comment by vnijs** [comment]
Thanks again for reporting @AlekseyBuzmakov. It took me a while to track down but the issue should be resolved now. No `XQuartz` required! Please use `radiant.update::radiant.update()` to get the latest version of `radiant.data` (i.e., 0.9.6.8). You can check if you have it using `packageVersion("radiant.data")`

**Comment by AlekseyBuzmakov** [comment]
Sorry, I have restarted the RStudio after the update and everything works. Thank you!

**Comment by vnijs** [comment]
Excellent!
