### ISSUE TITLE
csv datasets cannot be open under Windows if path contains to latin symbols

### ISSUE THREAD

**Issue by AlekseyBuzmakov** [radiant-rstats/radiant#66]
The error is related only to **Windows** platform. If a path contains non latin symbols, then the dataset is not opened with the error that the file not found. For example if file name contains "папка/dataset.csv" (папка is a folder in russian), the dataset will not be open and an empty dataset with column names X1, X2, ... X6 is created.

**Comment by vnijs** [comment]
Thanks for reporting this issue @AlekseyBuzmakov. Enconding on Windows is a hard problem that people have struggled with for a long time. I will see what I can do but it will take some time.

An immediate solution might be to use the docker container for R, Rstudio, and Radiant (https://github.com/radiant-rstats/docker). This does require you install Docker first and does not work with Windows Home edition. If you install Git Bash (https://git-scm.com/downloads) you can then use the script below to run Rstudio. From Rstudio you can run Radiant as usual and you should be able to use directory names like папка without difficulty. I did test this and it seems to work well.

https://github.com/radiant-rstats/docker/blob/master/radiant/launch-windows.sh

I'll post back if I have any updates

**Comment by vnijs** [comment]
I have spent several hours on this now and I'm not overly hopeful as I can't even get `list.files("C:")` to recognize "папка" correctly. It just prints it as "?????". This makes it very hard to diagnose and fix the problem. I hope you can try out the docker option I mentioned.

**Comment by AlekseyBuzmakov** [comment]
@vnijs  Yes, Windows had made bad decisions :( in its history. In fact in RStudio under Windows it is possible to open files. For that the encoding of the script file should be set to CP1251. For the moment we have advised to put data files to latin-name-only paths.

**Comment by vnijs** [comment]
Ah. If you can load data into Rstudio you can also have them start Radiant
after that and get the data from the global workspace.

[image: image.png]

**Comment by vnijs** [comment]
@AlekseyBuzmakov I have updated a few things in `shinyFiles`, the file browser that Radiant uses. 

Could you run the commands below and let me know if the file paths you see show up correctly when there are russian characters in the directory and/or filename? If this works I will integrate this version of `shinyFiles` into Radiant.

Thanks

```
devtools::install_github("thomasp84/shinyFiles")
shinyFiles::shinyFilesExample()
```

**Comment by vnijs** [comment]
@AlekseyBuzmakov Is this something you can try out? There have been quite a few improvements to the file browser that radiant uses but it is hard to test these types of things without the locale settings

**Comment by AlekseyBuzmakov** [comment]
@vnijs sorry for a long response, I will try it somewhere. The problem is that I have no windows computer. It was computer of a person from the summer school and I have no easy available windows machine.

**Comment by vnijs** [comment]
I see. If you do have an opportunity to check this in the future please let me know how it goes.
