### ISSUE TITLE
to_categorical: Error in dir.exists(x) : file name conversion problem -- name too long?

### ISSUE THREAD

**Issue by sproket12001** [radiant-rstats/radiant#67]
Hello,
I have got stucked with this message while using to_categorical function in rstudio (the latest available with keras package onboard). I don't know how to overcome the issue - seems like language settings, but I do not know how to move further. Can you help me please?
Sproket

**Comment by vnijs** [comment]
@sproket12001 This seems to be a keras related issue. Why did you post here?

**Comment by sproket12001** [comment]
I'm new to github - I could see comparable issue solved right just on github (unfortunatelly, the solution doesn't help me at all). Where you suggest me to post this question?

**Comment by vnijs** [comment]
Use stackoverflow. See link below on how to ask a good question there. Good luck

https://stackoverflow.com/help/how-to-ask
