### ISSUE TITLE
grepl issue in Report>Rmd

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#68]
Data exists and can be stored using the button in the view tab, but the code that it creates (below) creates a data frame that's empty regardless of the grepl parameters used.

```{r}
## filter and sort the dataset
One_Micron_Data_wrk <- One_Micron_Data %>%
  filter(grepl('aat', mpn, fixed = TRUE)) %>%
  select(material_dwid:Duplicate)
register("One_Micron_Data_wrk", "One_Micron_Data")
 dtab(One_Micron_Data_wrk, dec = 2, nr = 100) %>% render()
```

**Comment by vnijs** [comment]
@josh1400 It is very helpful to post issues using data that other can access as well. Using the diamonds data the following code works fine. Code with `filter = TRUE` could not have worked in _Data > View_ as you can see in the screenshot below

![image](https://user-images.githubusercontent.com/2998956/43289978-70e5d37e-90e1-11e8-86c5-a4c687c2b509.png)

The example below was generated in _Data > View_ and works fine in a report and in _Data > View_

```{r}
## filter and sort the dataset
diamonds_wrk <- diamonds %>%
  filter(grepl("eal", cut)) %>%
  select(price:date)
register("diamonds_wrk", "diamonds")
```

The below as edited in _Report > Rmd_ and also works file.

```{r}
## filter and sort the dataset
diamonds_wrk <- diamonds %>%
  filter(grepl("eal", cut, fixed = TRUE)) %>%
  select(price:date)
register("diamonds_wrk", "diamonds")
```
I can only guess that there is a problem with your dplyr code and the grepl call. Try something like the below to check what data is actually being filtered

```{r}
## filter and sort the dataset
diamonds_wrk <- diamonds %>%
  filter(grepl("eal", cut, fixed = TRUE)) %>%
  select(price:date)
head(diamonds_wrk)
```

**Comment by vnijs** [comment]
I assume I can close the issue. If not please post again.

**Comment by josh1400** [comment]
I'm still having issues.

The following code creates a blank data set.


```{r}
## filter and sort the dataset
titanic_wrk <- titanic %>%
  filter(grepl('allen', name, fixed = TRUE)) %>%
  select(pclass:embarked)
register("titanic_wrk", "titanic")
# dtab(titanic_wrk, dec = 0, nr = 100) %>% render()
```

**Comment by josh1400** [comment]
Perhaps I need to update Radiant?

**Comment by vnijs** [comment]
Yes. Because the filter you applied leads to a data.frame with 0 rows as you can see below.

```
library(radiant.data)
titanic_wrk <- titanic %>%
  filter(grepl('allen', name, fixed = TRUE)) %>%
  select(pclass:embarked)

> titanic_wrk
 [1] pclass   survived sex      age      sibsp    parch    fare     name     cabin    embarked
<0 rows> (or 0-length row.names)
```

**Comment by josh1400** [comment]
In the view tab, I see three rows.
![image](https://user-images.githubusercontent.com/36533710/43659736-c321c5a4-9711-11e8-8d3d-215d698245c0.png)

**Comment by josh1400** [comment]
I then click the "Report Results" button to create the code above.

**Comment by josh1400** [comment]
I think I figured it out.  The code is case sensitive in the report, but the view tab is not case sensitive.

**Comment by vnijs** [comment]
The "Search" input is case insensitive and does a search across all columns. If you use `grepl` in the Filter box it will run as you specify it.

For more on this see: https://radiant-rstats.github.io/docs/data/view.html 

"You can also use string matching to select rows. For example, type grepl('ood', cut) to select rows with Good or Very good cut. This search is case sensitive by default. For case insensitive search use grepl("GOOD", cut, ignore.case = TRUE). Type your statement in the  Filter box and press return to see the result on screen or an error below the box if the expression is invalid."

The code you posted can't run in the _Data > View_ tab due to an issue with the filter

![image](https://user-images.githubusercontent.com/2998956/43660135-f04eb89c-9712-11e8-8e0d-3a240220e811.png)

**Comment by josh1400** [comment]
Thanks for the clarifications.  I got it now.

**Comment by vnijs** [comment]
Ah. Now I see what you did based on the screenshot from the View tab. Very useful. Thanks! I will look into this.

**Comment by vnijs** [comment]
Should be fixed now. The command below should have you all set for R >= 3.5.0

`radiant.update::radiant.update()`
