### ISSUE TITLE
linear programming module

### ISSUE THREAD

**Issue by sergioventurini** [radiant-rstats/radiant#7]
hi,

together with some colleagues we were thinking of using radiant for a business analytics course starting from fall 2017. the course covers all but one of the topics that radiant already includes. in particular, in the course we also discuss linear programming.

could it be possible to add a linear programming module in a future release of the package?

thanks.

**Comment by vnijs** [comment]
Nice to hear of your interest in Radiant @sergioventurini. I may add an interface for LP as some point but, to be honest, I'm not sure how easy it would be to make an interface that is at least as convenient for students as Excel + Solver. At the moment I'm working on modules for random forests, choice models, and text analysis. Then I'll likely focus on adding access to data bases, etc. In sum, it might be a while before LP get added. We currently, actually, to everything in Radiant and then use Excel and Solver for LP. Would that be an option for you for now?

**Comment by sergioventurini** [comment]
thanks for your answer.

yes, we currently use excel's solver for LP problems, but it would be nice to have all the tools in a single software. moreover, differently from excel, it would be a much more _**portable**_ solution (OS X/Windows/Linux)! :)

as you probably already know, currently there are many packages that are able to solve LP problems. the most popular is _linprog_, but many others can be found here

https://cran.r-project.org/web/views/Optimization.html

best regards.

**Comment by vnijs** [comment]
You make a good point @sergioventurini. I know some of the packages that solve LP problems. The issue really is developing with an interface that can be used to describe the LP problem that is both flexible and convenient. Excel's interface has both those features but Radiant will likely never have spreadsheet-type input and formula's. If anything it would be more like the interface for Model > Simulate  https://radiant-rstats.github.io/docs/model/simulater.html
