### ISSUE TITLE
csv import issue

### ISSUE THREAD

**Issue by witwall** [radiant-rstats/radiant#70]
for example, if  a csv has the conten, 
```
test
BBB
"AAA \"Collection\""
CCC
DDD
"AAA \"Collection\""
EEE
FFF
```

when import with radiant, got wrong result,

![image](https://user-images.githubusercontent.com/3222056/43508535-ca76f9b6-95a2-11e8-805a-d3f64e542cf7.png)

when using read.csv, it is ok, but if have many rows, the result is not wrong either.

**Comment by vnijs** [comment]
The underlying issue is with the readr package (i.e., readr::read_delim). I'm not sure what the best fix is at this point other than to reformat the data as below. 

test
BBB
"AAA 'Collection'"
CCC
DDD
"AAA 'Collection'"
EEE
FFF

**Comment by witwall** [comment]
@vnijs how about let radiant supports data.table to import csv?

for now, I ask analyst to use fread to  import csv then save rds(do the job in radiant Report), then import in radiant, so no need to stop radiant and start it again.

rio can use in this way too.

**Comment by vnijs** [comment]
I'm thinking about both of these options. Will revisit in the next few weeks

**Comment by vnijs** [comment]
I was planning to post an issue to the `readr` repo on github but it seems this data structure doesn't work for `fread` either. 

```
data <- 'test
BBB
"AAA \"Collection\""
CCC
DDD
"AAA \"Collection\""
EEE
FFF'

tmp_file <- tempfile()
cat(data, file = tmp_file)

## Does not work with read_csv
readr::read_csv(tmp_file)

## Does not work with fread
data.table::fread(tmp_file)
```

**Comment by vnijs** [comment]
Closing
