### ISSUE TITLE
Number of Variables Displaying in Visualize

### ISSUE THREAD

**Issue by jab57** [radiant-rstats/radiant#71]
For some reason after creating a variable using transform, I see it when I view the list of variables but when I try to chart the variable using visualize I do not see the variable there.  Appreciate your help.

**Comment by jab57** [comment]
![capture2](https://user-images.githubusercontent.com/41925323/43587308-8cf0b52c-962f-11e8-840b-aea4f1e03019.PNG)
![capture](https://user-images.githubusercontent.com/41925323/43587313-8e8c470c-962f-11e8-80bd-ac42e0cf3162.PNG)


here are two images illustrating that for some reason it does not show these variables available when I  try to chart them in visualize tab.  Is there a limit in the number of variables that can display in the drop down box?

**Comment by jab57** [comment]
Just to be a little more specific, I created a constant variable that I want to use to display a reference line in the chart.  It seems to work if the variable is not a constant.  I just wanted to add a reference line and thought one easy way would be to create a variable with a constant value and then display it in the scatter chart.  Is there some type of data compression algorithm taking place when you display a limited number of observations with visualize?  Thanks.

**Comment by jab57** [comment]
I believe I found I way to do it using a conditional statement when creating the variable with slightly different values when condition is TRUE vs FALSE. Thanks.

**Comment by vnijs** [comment]
A variable will not be shown if it has no variability. What you want is a plot customization using ggtplo2 syntax. See the link below:

https://radiant-rstats.github.io/docs/data/visualize.html

Specifically: 

Draw a horizontal line: + geom_hline(yintercept = 0.1)

**Comment by vnijs** [comment]
Read the section "Customizing plots in Report > Rmd" on the linked page
"

**Comment by jab57** [comment]
Thanks.

**Comment by vnijs** [comment]
As a specific example of what you do in _Report > Rmd_. The `visualize` call was generated in _Data > Vizualize_ and then edited in _Report > Rmd_

```{r fig.width = 7, fig.height = 7, dpi = 144}
visualize(
  diamonds, 
  xvar = "carat", 
  yvar = "price", 
  type = "scatter", 
  nrobs = 1000, 
  custom = TRUE
) + geom_hline(yintercept = 5000)
```

![image](https://user-images.githubusercontent.com/2998956/43595991-e686fb66-9632-11e8-86a6-05689b1f8c20.png)

**Comment by vnijs** [comment]
Will close for now. Reopen if needed
