### ISSUE TITLE
Save collapsed rows in Rmd section in State file

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#72]
![image](https://user-images.githubusercontent.com/36533710/43803297-61ed0aac-9a4d-11e8-820c-0bdd2353ccfa.png)

Currently, regardless of how you save a state file, the Rmd tab is always fully expanded.

I want the state file to load with the rows collapsed underneath the title like 3 of them are in the photo.

Is this possible?

**Comment by josh1400** [comment]
Collapsed rows enable users to get a quick overview of the process with out seeing all the code.

**Comment by vnijs** [comment]
I agree this would be nice. However, that is not information that is currently stored and I'm not sure how to even implement it at this point.

The easiest way to get close to this at this point is a keyboard-shortcut:

Windows: Alt-0 
Mac: Command-Option-0

See https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts for more short cuts.

**Comment by vnijs** [comment]
As this is not likely to be a feature I can add I'll close this issue now.
