### ISSUE TITLE
Downloading Radiant without using DropBox

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#73]
My company doesn't allow access to File Sharing services.  Is there another way to download Radiant?

Currently, I have special access to download it and I share the package with people who want it.  This is a fine workaround unless the package changes a lot.  How often does the package change?

**Comment by josh1400** [comment]
We are allowed to use OneDrive.

**Possible solution:** Have a download for each service (DropBox, OneDrive, Drive) so that restricted users don't have this issue.

**Comment by josh1400** [comment]
For Windows, you can download and run the all-in-one installer for R, Rstudio, and Radiant.  That installer is located at the following address.

https://www.dropbox.com/s/0l6va4pz3s8wghq/Rady-Radiant-Installer-Latest.exe?dl=1

I've downloaded the installer and have it shared where other's can get it.  This is completely fine assuming the installer doesn't change.  Do you ever update the all-in-one installer?

Our team does have Radiant installed on Rstudio Connect, but we'd like to provide the all-in-one installer for users that want to download a desktop version for offline work.

**Comment by vnijs** [comment]
Ah. Now I see what you mean. You don't actually need Dropbox to download from the link though. Or do you mean that https://www.dropbox.com is blocked altogether? 

The installer gets updated a about 2 times a year when there is a new version of R or Rstudio. If you update the installer once a year, however, you should be just fine.

We are working on another way to share files that should just be a URL within the Rady domain. Would that work for you?

**Comment by josh1400** [comment]
The Rady domain would work.

Our company has blocked the use of DropBox and Google Drive altogether.

**Comment by vnijs** [comment]
FYI The installer is now (also) available through the link below:

https://rady.ucsd.edu/faculty/directory/vnijs/Rady-Radiant-Installer-Latest.exe

**Comment by josh1400** [comment]
This link now results in 404.  Did you move it somewhere aside from DropBox?

**Comment by vnijs** [comment]
I'm looking into it. Thanks for the report.

**Comment by vnijs** [comment]
The link works again now although you browser may still cache the "old" 404 page. I'll also use this link by default on the install page from now on.

https://radiant-rstats.github.io/docs/install.html

**Comment by josh1400** [comment]
Thanks!
