### ISSUE TITLE
Radiant Update Issue - Starting Radiant in Window or Viewer options no longer available

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#75]
The options to start Radiant in a window or in the viewer are no longer available.  Is there a reason for that?

**Comment by josh1400** [comment]
I see that running radiant::radiant_window() or radiant::radiant_viewer() is still an option.

It seems that the browser version is now able to load data in the report.  Not being able to load data was the browser version's only drawback that i knew of.  Now that it's possible, are you encouraging people to only use the browser?

**Comment by vnijs** [comment]
That is correct. The "Window" option was not as nice as the external "Browser" option (e.g, Chrome or Firefox). The "Viewer" option still has merit but I decided to remove it from the menu to avoid confusion on the part of (new) students. 

As you noticed, you can still use radiant::radiant_viewer() if you prefer running radiant in the Rstudio Viewer.

Does this work for you?

**Comment by josh1400** [comment]
It works for me.

I'm happy to return to the browser now that data can be loaded in the report!

**Comment by vnijs** [comment]
Excellent. Will close for now
