### ISSUE TITLE
How to keep space in creation of new variables?

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#76]
![image](https://user-images.githubusercontent.com/36533710/44813113-dc538680-ab8d-11e8-82b9-1f6c56712319.png)

Before the update, spaces were included with the create function.  I'd like know what needs to be added to the below code to maintain the space.

```{r}
## create new variable(s)
titanic <- mutate(titanic, Animal = "The Dog")
```

**Comment by vnijs** [comment]
Thanks for reporting. Is fixed in the upcoming update (this evening or tomorrow)
