### ISSUE TITLE
Add commas to #s in visuals

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#77]
![image](https://user-images.githubusercontent.com/36533710/44815423-4f5ffb80-ab94-11e8-9bba-52aedd278b78.png)

The upgraded visuals section is great!  I love how easy it is to customize now.  Can you include a checkbox to add commas and maybe enable other changes too (3M, $30.27, 0.03, 40%, 5,990,321, etc.).

**Comment by vnijs** [comment]
I'm hesitant to add more customization options, to be honest, given that there are already quite a few. Below some examples of how you could customize the y-axis scales. There were already a few examples in the help file for Data > Visualize and I'm adding a few more for the next release. 

Radiant uses ggplot2 to render plots and it has a enormous number of customization options. See link below:

https://ggplot2.tidyverse.org/index.html 

```{r fig.width = 7, fig.height = 7, dpi = 144}
visualize(
  diamonds, 
  xvar = "date", 
  yvar = "price", 
  type = "line", 
  fun = "sum", 
  custom = TRUE
) +
 scale_y_continuous(label = scales::comma)
```

```{r fig.width = 7, fig.height = 7, dpi = 144}
visualize(
  diamonds, 
  xvar = "date", 
  yvar = "price", 
  type = "line", 
  fun = "sum", 
  custom = TRUE
) +
 scale_y_continuous(label = scales::dollar_format())
```

```{r fig.width = 7, fig.height = 7, dpi = 144}
visualize(
  diamonds, 
  xvar = "date", 
  yvar = "price", 
  type = "line", 
  fun = "sum", 
  custom = TRUE
) +
 scale_y_continuous(label = scales::percent)
```

```{r fig.width = 7, fig.height = 7, dpi = 144}
visualize(
  diamonds, 
  xvar = "date", 
  yvar = "price", 
  type = "line", 
  fun = "sum", 
  custom = TRUE
) +
 scale_y_continuous(labels = scales::unit_format(unit = "K", scale = 1e-3))
```

**Comment by vnijs** [comment]
Please reopen if needed
