### ISSUE TITLE
Flip axis labels

### ISSUE THREAD

**Issue by mv1991** [radiant-rstats/radiant#78]
Is it possible to implement the option to rotate axis labels 90 degrees for plots?
The labels overlap quickly, I know in native R it is `boxplot(las =2)` is there anyway to put that in Radiant?

**Comment by vnijs** [comment]
You can. The _Data > Visualize_ tab allows you to generate and customize code for plots. To generate code click on the ![image](https://user-images.githubusercontent.com/2998956/45514335-ee225580-b759-11e8-8640-fb6769009e2e.png) icon.

The `visualize` function is based on ggplot2 so you can customize any plot using ggplot2 syntax. See link and example below:

https://radiant-rstats.github.io/docs/data/visualize.html

```{r fig.width = 7, fig.height = 7, dpi = 144}
visualize(
  diamonds, 
  xvar = "cut", 
  yvar = "price", 
  type = "bar", 
  custom = TRUE
) + theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

Note that `custom = TRUE` when you want to add customizations to the plot

**Comment by mv1991** [comment]
Woks like a charm, thank you!

**Comment by vnijs** [comment]
Glad to hear that @mv1991!
