### ISSUE TITLE
ERROR: object 'Fire' not found

### ISSUE THREAD

**Issue by 4kammer** [radiant-rstats/radiant#8]
Saving a knitted report in any other file format other than *.RMD (Word, HTML, PDF...) results in this error -- screen capture is trying to save in MS Word as you can see.
![image](https://cloud.githubusercontent.com/assets/5490773/19566542/8eeec724-969f-11e6-9a75-3a3030842dc4.png)

**Comment by vnijs** [comment]
@4kammer I can't replicate the problem you are having. To save to different formats you will need to run radiant from Rstudio (Addins menu) and have followed the install instructions linked below.

https://radiant-rstats.github.io/docs/install.html

If this does not fix the problem please send me a state file (click the floppy icon and stave state).

**Comment by 4kammer** [comment]
Thanks for the quick reply.  Attached please find the saved state, which I uploaded in a new session and tried to save as Word with same error results.
[radiant-state-2016-10-20.zip](https://github.com/radiant-rstats/radiant/files/542915/radiant-state-2016-10-20.zip)

**Comment by 4kammer** [comment]
P.S., I've saved work in other file formats before without problem. This is the first time with this error repeating itself.

**Comment by vnijs** [comment]
I'll close this issue and reply by email.
