### ISSUE TITLE
State file loading with spaces entered between every line

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#80]
```{r}
Shipments <- sqlFetch(Master.Data, "iwpl.v_shipments")
register("Shipments")
```

```{r}
## create new variable(s)
Shipments <- mutate(Shipments, X = "X")
```
The above is saved, but occasionally a state file becomes corrupted and always loads as the following until manually fixed and saved again.

```{r}

Shipments <- sqlFetch(Master.Data, "iwpl.v_shipments")

register("Shipments")

```

```{r}

## create new variable(s)

Shipments <- mutate(Shipments, X = "X")

```

**Comment by josh1400** [comment]
No code is corrupted.  The report can still be knit easily.

The file just becomes really long and hard to debug.

**Comment by vnijs** [comment]
That is odd @josh1400. I have not been able to reproduce this in Mac, Linux, or Windows. Do you have a state file you could email me where this happens?

**Comment by josh1400** [comment]
The next time it happens, I'll send you the state file without making any changes.  FYI, the file that it happened to was very large.

**Comment by vnijs** [comment]
Please reopen if needed. Would be happy to take a look at this issue if it comes up again
