### ISSUE TITLE
In pivot tables, issue with column names containing dots

### ISSUE THREAD

**Issue by dcomtois** [radiant-rstats/radiant#81]
First, let me congratulate you for this outstanding application. I'm really impressed!

I noticed that when creating a Pivot which uses a grouping variable having a `.` in its name, we get an error message.

For instance, if I create a copy of `iris$Species` called `iris$iris.Species` :

`iris$iris.species <- iris$Species`

... I get the following error message when creating the pivot table using `iris.Species` as grouping variable:

> Error: You specified the columns: iris.species, but the column names of the data are **iris_species,** Sepal_Length

Most likely has to do with the use of `fix_names()`, which replaces '.' with '_'.

**Comment by vnijs** [comment]
Thanks for the compliment and the report @dcomtois. I just pushed a fix which will leave the input variable names unchanged but will "fix" other column names as needed

`devtools::install_github("radiant-rstats/radiant.data")`

**Comment by vnijs** [comment]
Seems to be working fine now @dcomtois. If you have any additional issues please open another. To get the latest version with radiant with the fix (not yet on CRAN) use the commands below:

```
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```
