### ISSUE TITLE
Radiant cannot open CSV

### ISSUE THREAD

**Issue by georgetrzv** [radiant-rstats/radiant#82]
Does anyone know how to handle Radiant not showing any of my files and folders in my Desktop? I'm trying to load a CSV, but it doesn't come up. Any advice? I've tried re-installing R, uninstalling the package, reinstalling it, and having the most updated versions. 

Thanks in advance,
George

<img width="809" alt="radiant_issue" src="https://user-images.githubusercontent.com/8847117/45911165-0e978300-bdde-11e8-8eac-c2ffe7c36a3f.PNG">

**Comment by vnijs** [comment]
Odd. Can you post a screenshot of File Explorer (or Finder on macOS) to show what is on your Desktop?

**Comment by vnijs** [comment]
Also, just to make sure you are indeed using the latest version, please run the commands below in Rstudio

```{r}
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```

**Comment by vnijs** [comment]
Any updates @georgetrzv? Just to be sure ... the view on your screen should show only (1) folders and (2) csv files. No other file (types) would be shown

**Comment by georgetrzv** [comment]
Hey vnijs, sorry for the late reply, I'll try to update and see if that solves the problem. In the meanwhile, here's a copy of the contents of my Desktop:

<img width="516" alt="desktop_snapshot" src="https://user-images.githubusercontent.com/8847117/45929135-6daee200-bf1b-11e8-8289-e1688cabda93.png">

**Comment by georgetrzv** [comment]
Coupon+Effectiveness is the .csv file of interest by the way.

**Comment by georgetrzv** [comment]
Just updated Radiant, got "nothing to update" comment in console, csv still not visible. :'(

I tried reinstalling from the following Dropbox link:
https://www.dropbox.com/s/0l6va4pz3s8wghq/Rady-Radiant-Installer-Latest.exe?dl=1

I doubt that's the issue as my classmates have all downloaded from the same source.

**Comment by vnijs** [comment]
I think the cause of the "blank" desktop in the file browser may be that Windows (unfortunately) can have multiple desktop folder. "Home" in the radiant file browser would be something like c:/Users/yourid. c:/Users/yourid/Desktop may or may not actually be the Desktop that your system uses though. Windows now also has, at least on some systems, c:/Users/yourid/OneDrive/Desktop

My guess is that if you navigate to Home > OneDrive > Desktop on the radiant file browser you will see the files you are looking for

**Comment by georgetrzv** [comment]
Holy... oh man, Vnijs... you are the bomb! Home > OneDrive > Desktop in Radiant worked. Found my file! Thank you very much!

Best,
George

**Comment by vnijs** [comment]
Glad to hear that @georgetrzv! :)
