### ISSUE TITLE
Customize Radiant UI

### ISSUE THREAD

**Issue by AzrizHaziq** [radiant-rstats/radiant#83]
Hi i'm new in R programming and I discover Radiant suites my needs. 

Unfortunately, I would like to try to customize theme, color, etc in Radiant UI. I search in Radiant docs but could not find it, while in Shiny I do find a way to custom it. 

It is possible to customize the UI in Radiant? 

Thank you.

**Comment by vnijs** [comment]
I'm not like to add something like that to radiant. Take a look at shinythemes

https://rstudio.github.io/shinythemes/

Not sure what you have in mind but please also take a look at the license use for the radiant packages:

https://github.com/radiant-rstats/radiant#license
