### ISSUE TITLE
Title with ' in it prevents it from loading as clipboard or .csv

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#84]
Account sales | 18-Sep | Oct '18
-- | -- | --
Alex Hu | 0 | 0

The Oct '18 prevents the data from loading properly.

**Comment by vnijs** [comment]
Parsing from clipboard will never be as robust as reading from CSV. When I tried loading the attached file based on your example that worked fine. That said, anything with quotes in the variable name can be problematic when using any library to read csv files in R, Python, etc.

[quote-test.csv.zip](https://github.com/radiant-rstats/radiant/files/2422084/quote-test.csv.zip)

**Comment by josh1400** [comment]
When I load the actual file as a CSV, I get the following error.

Error: input string 1 is invalid UTF-8

The file actually looks like below.  That being said, I always try to stay clear of apostrophes and quotes.

Account sales | MPN | Customer / End Customer | DID | BU | Sep' 18 | Oct' 18 | Nov' 18 | Dec' 18 | Jan' 19 | Feb' 19 | Mar' 19 | Apr' 19 | May' 19 | Jun' 19 | Jul' 19 | Aug' 19
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
