### ISSUE TITLE
I cannot save my report

### ISSUE THREAD

**Issue by dahyechoi** [radiant-rstats/radiant#85]
I tried to save my report as PDF and Word.

But I cannot get my report. Nothing comes up with my report file.

New document is made but there isn't my work in R studio.

If you know how to solve my problem, please let me know.

I have to save report and submit it as my mid-term exam.

Sincerely,

**Comment by vnijs** [comment]
Please provide (much) more information. Are there any errors in the Rstudio console? Do you see all the output you expect when you click the `Knit report` button in _Report > Rmd_? Saving to PDF requires (tiny) tex. Do you have that installed?

**Comment by vnijs** [comment]
I assume this is fixed. If not, please re-open an issue. FYI I recommend using the install instructions described on the page below as that will also install latex through tinytex

https://radiant-rstats.github.io/docs/install.html
