### ISSUE TITLE
State file saves as .rda or .state.rda

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#87]
Sometimes state files are saved as .rda and sometimes they are saved as .state.rda

I'm using the same button to do it every time so why is it changing?

![image](https://user-images.githubusercontent.com/36533710/46701745-9f8b9e00-cbd5-11e8-9fb0-4b735ee5782e.png)

**Comment by vnijs** [comment]
This is for legacy reasons. 

The use of state.rda as the default extension started a few months ago. If you don't have a state file loaded radiant should always save state to .state.rda. If you loaded a state file that has .rda as extension (i.e., and not .state.rda) then when saving radiant will not try to "force" a .state.rda extension on the user so they can keep the "old" file name. If you loaded a previous state file with extension .state.rda you should see the same extension when you try to save the state again.

**Comment by josh1400** [comment]
Good to know :)

**Comment by vnijs** [comment]
OK. Closing for now
