### ISSUE TITLE
Uploading single sheet from Excel file on SharePoint

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#88]
Is it possible to use csv (url) to load a specific sheet from an Excel file with multiple sheets that is saved on SharePoint?

**Comment by vnijs** [comment]
If the sharepoint drive is mounted you can use readxl. Use the "Read files" button in Report > Rmd and then adjust the code as needed. See also https://readxl.tidyverse.org/

Even better ... don't store data in Excel :)

**Comment by josh1400** [comment]
Your preaching to the choir about not storing data in Excel haha

Good to know it's possible.
