### ISSUE TITLE
What's the code to remove data from memory?

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#89]
It doesn't appear in the manage area when "Show R-Code" is selected.

**Comment by vnijs** [comment]
Add `rm(my_df)` in _Report > Rmd_ or _Report > R_. Only code for loading and saving data is currently shown in "Show R-code"

**Comment by josh1400** [comment]
That was my first thought, but knitting
```{r}
rm(Demand0)
```
in the Rmd area doesn't remove that dataset.  What seems to be the problem?

**Comment by vnijs** [comment]
It does remove the dataset from memory but you are correct that it doesn't remove it from the dataset dropdown. I'll add a function `deregister` that does this type of cleanup soon. Thanks for the suggestion

**Comment by vnijs** [comment]
New version posted. Use 'deregister' on report > rmd to remove loaded dataset

**Comment by josh1400** [comment]
How does deregister work?  It seems to only delete the last registered dataset.  How would I remove 'exam'

```{r}
deregister("exam")
```

Running the above removes the last dataset registered.

**Comment by josh1400** [comment]
I'm attempting to remove a dataset that I registered, but it only removes the last dataset registered.

**Comment by vnijs** [comment]
Ah. Cleary didn't do enough testing on this one. Please update and try again. 

FYI you can now also load a state file directly from a URL when you start radiant:

```
radiant::radiant("https://github.com/radiant-rstats/docs/raw/gh-pages/examples/demo-dvd-rnd.state.rda")
```

Not sure it works with OneDrive or Dropbox however as I haven't tested that yet.

**Comment by vnijs** [comment]
This should be resolved. If you still see any issues here let me know
