### ISSUE TITLE
Cant find radiant in 'add-ins' after installation 

### ISSUE THREAD

**Issue by yangt92** [radiant-rstats/radiant#90]
Having trouble with Radiant installation on windows - i restarted my comp and when i opened R-studio, the radiant add-in could not be found. Can anyone advise on how i can troubleshoot this issue? Thanks!

**Comment by vnijs** [comment]
Try the command `radiant::radiant()` in the Rstudio console. If that opens Radiant in your default browser, the install was successful and restarting Rstudio should be all you need to do. If radiant does not start, run the commands below and restart Rstudio. 

```
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```

**Comment by yangt92** [comment]
It works now, thanks a ton!

**Comment by vnijs** [comment]
Glad to hear it!
