### ISSUE TITLE
Error : package 'radiant.data' 0.9.7 was found, but >= 0.9.7.4 is required by 'radiant'

### ISSUE THREAD

**Issue by malcook** [radiant-rstats/radiant#94]
in RStudio Version 1.1.456 – © 2009-2018 RStudio, Inc.
with R version 3.5.1 (2018-07-02) -- "Feather Spray"
addins > addin Manager > radiant
```
* installing *source* package 'radiant' ...
** R
** inst
** byte-compile and prepare package for lazy loading
Error : package 'radiant.data' 0.9.7 was found, but >= 0.9.7.4 is required by 'radiant'
ERROR: lazy loading failed for package 'radiant'
* removing 'C:/Program Files/R/R-3.5.1/library/radiant'
In R CMD INSTALL

```

occurs whether installing from CRAN or github

**Comment by vnijs** [comment]
Full install instructions are here: https://radiant-rstats.github.io/docs/install.html

Use the commands below to makes sure all relevant packages are up-to-date. After installing `radiant.udpate` you will also be able to update Radiant from the Addins dropdown in Rstudio

```
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```
