### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#95]
Testing if Radiant can be loaded ...
Failed with error:  ‘there is no package called ‘ggplot2’’

Radiant update attempt was unsuccessful. Please restart R(studio) and run the update (radiant.update::radiant.update()) or sync (radiant.update::sync_packages()) command again. If update (sync) is still not successful, please send an email to radiant@rady.ucsd.edu with screen shots of the output shown in R(studio).

**Comment by josh1400** [comment]
Manually installed ggplot2 and got the following error.

Testing if Radiant can be loaded ...
Failed with error:  ‘there is no package called ‘radiant.data’’

**Comment by josh1400** [comment]
Installed radiant.data manually, but still get the same error.

Testing if Radiant can be loaded ...
Failed with error:  ‘there is no package called ‘radiant.data’’

**Comment by josh1400** [comment]
I reinstalled everything and it works now.

**Comment by vnijs** [comment]
Glad to hear it!
