### ISSUE TITLE
Adjust where visual studio 2015 and radiant.sessions folders save

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#96]
I moved my working directory to a folder called RStudio.  Radiant loads and saves files in this folder, but a radiant.sessions folder and a visual studio 2015 folder still save directly in Documents.

I'd prefer they saved in the RStudio folder.

**Comment by vnijs** [comment]
The radiant.session directory is only for emergency backups in case of a crash or incorrect closing of the application. This has to go in the computers home directory which, in your case, is the Documents folder. Sorry. Not much to do about this
