### ISSUE TITLE
Radiant failing to start on a Shiny Server

### ISSUE THREAD

**Issue by jharris0** [radiant-rstats/radiant#97]
Hello! I am attempting to run Radiant on Shiny Server open source (Ubuntu 16.04). I installed Radiant per the instructions at https://radiant-rstats.github.io/docs/, and cloned the repo on Nov. 29, 2018. The Radiant-related portion of my shiny-server.conf looks like this:

```
  location /radiant {

    app_dir /srv/shiny-server/radiant/inst/app;

    log_dir /var/log/shiny-server;

  }
```

When I access the radiant URL from my browser, I get the following error:

```
An error has occurred
The application failed to start.
The application exited during initialization.
```

Log file shows the following:

```
Attaching package: ‘lubridate’

The following object is masked from ‘package:base’:

    date


Attaching package: ‘tidyr’

The following object is masked from ‘package:magrittr’:

    extract


Attaching package: ‘dplyr’

The following objects are masked from ‘package:lubridate’:

    intersect, setdiff, union

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Attaching package: ‘glue’

The following object is masked from ‘package:dplyr’:

    collapse

Error in value[[3L]](cond) :
  Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'figures_model'; `directoryPath` = '/app/tools/help/figures/'
Calls: runApp ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Stopped Radiant

Execution halted
```

Versions involved are as follows:

```
> packageVersion("radiant.basics")
[1] ‘0.9.7.5’
> packageVersion("radiant.data")
[1] ‘0.9.7.10’
> packageVersion("radiant.design")
[1] ‘0.9.7.5’
> packageVersion("shiny")
[1] ‘1.1.0’
> system('shiny-server --version', intern = TRUE)
[1] "Shiny Server v1.5.5.872" "Node.js v6.10.3"
```

Not sure if I messed something up with the installation?

**Comment by vnijs** [comment]
Unfortunately I can't reproduce the issue so I'm not sure what the issue is in your setup @jharris0. Perhaps you could try updating all packages radiant needs as root using the commands below? Also, perhaps a more recent shiny-server version (e.g., 1.5.9.923)?

```
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```

FYI Radiant is also available as a docker container (with rstudio server). See the links below:

https://hub.docker.com/r/vnijs/radiant/
https://github.com/radiant-rstats/docker

**Comment by jharris0** [comment]
Okay, sounds good. I think I will switch to the docker option. Thanks very much!

**Comment by vnijs** [comment]
Sorry I missed your email Jessie. Radiant should run fine on Ubuntu. Perhaps ensure you have the latest version of all relevant packages using

install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
