### ISSUE TITLE
Remove "DO NOT USE" by searching for it in View

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#98]
Goal: Filter the following data set so that only ID 1 and 4 are showing.

ID | Name | Height
-- | -- | --
1 | Jen | 6'
2 | Jen DO NOT USE | 5' 9"
3 | Jen DO NOT USE | 5' 2"
4 | Joe | 6' 3"
5 | Joe DO NOT USE | 5' 8"
6 | Joe DO NOT USE | 5'

How: Check a box that makes the search criteria disappear.
![image](https://user-images.githubusercontent.com/36533710/49666222-375a0c80-fa0c-11e8-9ec0-d3de84794f90.png)

**Comment by vnijs** [comment]
`grepl` in R returns a logical, TRUE if the pattern exists and FALSE otherwise. Then add '!' which means "not" in R

![image](https://user-images.githubusercontent.com/2998956/49689911-43fa6580-fadd-11e8-81c4-a73f13e2db9c.png)
