### ISSUE TITLE
plotly isn't interactive in Radiant

### ISSUE THREAD

**Issue by josh1400** [radiant-rstats/radiant#99]
Using the following command, I get a graph but it's not interactive.

```{r}
plot_ly(disti_forecasts_fsf, x = ~unit_qty, color = ~Entity, type = "box")
```

Is this an issue with my code or with Radiant?

**Comment by vnijs** [comment]
Does it create an interactive plot in Rstudio?

**Comment by josh1400** [comment]
Yes

**Comment by vnijs** [comment]
Can you try saving report as notebook or HTML? That should work. Inside
radiant you need to render. Will check back in after class

**Comment by josh1400** [comment]
It did not work as a notebook

**Comment by vnijs** [comment]
Here is a reproducible example. The first creates an interactive graph in radiant's "preview" and also in a save Notebook or HTML report. The 2nd will *not* produce an interactive plot in Radiant but *does* in the a save Notebook or HTML report. 

```{r}
plotly::plot_ly(diamonds, x = ~price, color = ~color, type = "box") %>% render()
plotly::plot_ly(diamonds, x = ~price, color = ~color, type = "box")
```
